# PROBLEM STATEMENT

With the covid 19 impact in the market, we have seen lot of changes in the car market. Now some 
cars are in demand hence making them costly and some are not in demand hence cheaper. One 
of our clients works with small traders, who sell used cars. With the change in market due to covid 
19 impact, our client is facing problems with their previous car price valuation machine learning 
models. So, they are looking for new machine learning models from new data. We have to make 
car price valuation model.

In [1]:
#Firstly we will scrape the data & will make a dataframe

In [2]:
#Importing the libraries

!pip install selenium

Requirement already satisfied: selenium in c:\users\asus\anaconda3\lib\site-packages (4.1.0)
Requirement already satisfied: urllib3[secure]~=1.26 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (1.26.7)
Requirement already satisfied: trio~=0.17 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (0.19.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: sortedcontainers in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: cffi>=1.14 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.14.6)
Requirement already satisfied: idna in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.2)
Requirement already satisfied: outcome in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: sniffio in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.2.0)
Requirement already satisfied: pycparser in c:\users\asus\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\asus\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.0.0)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\asus\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (21.0.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\asus\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (3.4.8)
Requirement already satisfied: certifi in c:\users\asus\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (2021.10.8)
Requirement already satisfied: six>=1.5.2 in c:\users\asus\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure]~=1.26->selenium) (1.16.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\asus\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.12.0)

# FIRST WE WILL SCRAPE THE DATA OF 5000 USED CARS & THEN WILL MERGE THE DATA INTO ONE CSV FILE

In [3]:
#Importing the needed libraries

import pandas as pd
import selenium
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')

In [4]:
#Creating an instance of the chrome driver to get to the url

driver = webdriver.Chrome(r'E:/CHROME-DRIVER/chromedriver_win32/chromedriver.exe')

In [5]:
#Getting into the website

driver.get('https://www.olx.in/en-in/mumbai_g4058997/cars_c84?isSearchCall=false')

In [7]:
#Creating empty lists so that we can fetch the data

Price=[]
Year=[]
Km=[]
Company=[]
Location=[]
Date=[]

In [8]:
#Fetching the data from olx for Price

for p in driver.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/span"):
    Price.append(p.text.replace("â‚¹","").replace(",",""))

In [9]:
#Printing the price

Price

[' 1095001',
 ' 595000',
 ' 475000',
 ' 320000',
 ' 825000',
 ' 599000',
 ' 395000',
 ' 198000',
 ' 90000',
 ' 410000',
 ' 999000',
 ' 650000',
 ' 1055000',
 ' 949999',
 ' 1890000',
 ' 350000',
 ' 394000',
 ' 399000',
 ' 210000',
 ' 535000',
 ' 295000',
 ' 460000',
 ' 1650000',
 ' 600000',
 ' 200000',
 ' 275000',
 ' 120000',
 ' 33000',
 ' 335000',
 ' 900000',
 ' 825000',
 ' 435000',
 ' 555000',
 ' 550000',
 ' 495000',
 ' 725000',
 ' 885000',
 ' 310000',
 ' 210000',
 ' 1540000',
 ' 361000',
 ' 2650000',
 ' 130000',
 ' 170000',
 ' 380000',
 ' 230000',
 ' 600000',
 ' 995000',
 ' 1175000',
 ' 435000',
 ' 1699999',
 ' 650000',
 ' 595000',
 ' 7990000',
 ' 2499000',
 ' 485000',
 ' 165000',
 ' 12200000',
 ' 299999',
 ' 535000',
 ' 849000',
 ' 2075000',
 ' 1290000',
 ' 180000',
 ' 170000',
 ' 280000',
 ' 1600000',
 ' 580000',
 ' 50000',
 ' 264000',
 ' 330000',
 ' 105000',
 ' 50000',
 ' 575000',
 ' 518000',
 ' 350000',
 ' 285000',
 ' 210000',
 ' 475000',
 ' 865000',
 ' 7700000',
 ' 425000',
 ' 1425000',
 ' 85000',
 ' 780000',
 ' 2148000',
 ' 225000',
 ' 368000',
 ' 460000',
 ' 410000',
 ' 100000',
 ' 3000000',
 ' 225000',
 ' 1250000',
 ' 325000',
 ' 250000',
 ' 497000',
 ' 4900000',
 ' 199999',
 ' 299999',
 ' 765000',
 ' 890000',
 ' 415000',
 ' 280000',
 ' 100000',
 ' 1090000',
 ' 388000',
 ' 321000',
 ' 499000',
 ' 649000',
 ' 1560000',
 ' 410000',
 ' 185000',
 ' 485000',
 ' 628000',
 ' 510000',
 ' 1750000',
 ' 425000',
 ' 70000',
 ' 910000',
 ' 485000',
 ' 375000',
 ' 545000',
 ' 130000',
 ' 425000',
 ' 398000',
 ' 486000',
 ' 361000',
 ' 1249000',
 ' 95000',
 ' 12500000',
 ' 265000',
 ' 400000',
 ' 350000',
 ' 475000',
 ' 375000',
 ' 1700000',
 ' 345000',
 ' 725000',
 ' 125000',
 ' 111000',
 ' 1599000',
 ' 1275000',
 ' 450000',
 ' 385000',
 ' 145000',
 ' 155000',
 ' 348000',
 ' 450000',
 ' 427000',
 ' 397000',
 ' 175000',
 ' 136000',
 ' 895000',
 ' 200000',
 ' 155000',
 ' 125000',
 ' 149000',
 ' 289000',
 ' 555000',
 ' 1075000',
 ' 345000',
 ' 1650000',
 ' 130000',
 ' 120000',
 ' 199999',
 ' 290000',
 ' 229000',
 ' 369000',
 ' 333000',
 ' 5400000',
 ' 300000',
 ' 1099000',
 ' 145000',
 ' 1199000',
 ' 375000',
 ' 1099000',
 ' 350000',
 ' 799000',
 ' 230000',
 ' 875000',
 ' 245000',
 ' 751000',
 ' 130000',
 ' 280000',
 ' 390000',
 ' 3200000',
 ' 1650000',
 ' 775000',
 ' 735000',
 ' 355000',
 ' 650000',
 ' 2290000',
 ' 5800000',
 ' 950000',
 ' 1199999',
 ' 1050000',
 ' 175000',
 ' 215000',
 ' 260000',
 ' 250000',
 ' 400000',
 ' 959999',
 ' 195000',
 ' 625000',
 ' 690000',
 ' 694000',
 ' 198000',
 ' 320000',
 ' 160000',
 ' 2775000',
 ' 2750000',
 ' 115000',
 ' 90000',
 ' 1349999',
 ' 3400000',
 ' 2500000',
 ' 255000',
 ' 2150000',
 ' 110000',
 ' 2350000',
 ' 890000',
 ' 1375000',
 ' 230000',
 ' 107000',
 ' 700000',
 ' 7700000',
 ' 2255000',
 ' 755000',
 ' 165000',
 ' 692000',
 ' 765000',
 ' 275000',
 ' 1299000',
 ' 1645000',
 ' 205000',
 ' 400000',
 ' 240000',
 ' 250000',
 ' 225000',
 ' 2221000',
 ' 1850000',
 ' 666970',
 ' 245000',
 ' 150000',
 ' 690000',
 ' 125000',
 ' 1385000',
 ' 475000',
 ' 1125000',
 ' 850000',
 ' 595000',
 ' 751000',
 ' 1025000',
 ' 750000',
 ' 840000',
 ' 1075000',
 ' 935000',
 ' 555000',
 ' 1625000',
 ' 349000',
 ' 875000',
 ' 1490000',
 ' 375000',
 ' 195000',
 ' 899000',
 ' 5600000',
 ' 160000',
 ' 349000',
 ' 270000',
 ' 324000',
 ' 255000',
 ' 139000',
 ' 1299000',
 ' 575000',
 ' 750000',
 ' 290000',
 ' 899999',
 ' 245000',
 ' 475000',
 ' 750000',
 ' 600000',
 ' 400000',
 ' 350000',
 ' 350000',
 ' 799000',
 ' 1099999',
 ' 1024999',
 ' 225000',
 ' 145000',
 ' 1350000',
 ' 2400000',
 ' 550000',
 ' 225000',
 ' 499000',
 ' 425000',
 ' 625000',
 ' 3600000',
 ' 795000',
 ' 1250000',
 ' 235000',
 ' 1199999',
 ' 2675000',
 ' 95000',
 ' 140000',
 ' 1925000',
 ' 1925000',
 ' 1755000',
 ' 850000',
 ' 120000',
 ' 229000',
 ' 650000',
 ' 174000',
 ' 430000',
 ' 1000000',
 ' 2150000',
 ' 2150000',
 ' 611000',
 ' 331000',
 ' 425000',
 ' 2800000',
 ' 800000',
 ' 1050000',
 ' 100000',
 ' 290000',
 ' 89000',
 ' 829000',
 ' 339000',
 ' 189000',
 ' 99999',
 ' 650000',
 ' 1945000',
 ' 299000',
 ' 495000',
 ' 675000',
 ' 4875000',
 ' 265000',
 ' 181000',
 ' 549000',
 ' 395000',
 ' 199000',
 ' 575000',
 ' 3200000',
 ' 113000',
 ' 65000',
 ' 3300000',
 ' 1350000',
 ' 1895000',
 ' 745000',
 ' 7900000',
 ' 445000',
 ' 325000',
 ' 270000',
 ' 995000',
 ' 445000',
 ' 545000',
 ' 1145000',
 ' 375000',
 ' 675000',
 ' 495000',
 ' 375000',
 ' 2299999',
 ' 425000',
 ' 280000',
 ' 330001',
 ' 775000',
 ' 435000',
 ' 210000',
 ' 185000',
 ' 720000',
 ' 2500000',
 ' 295000',
 ' 275000',
 ' 649000',
 ' 1075000',
 ' 325000',
 ' 525000',
 ' 395000',
 ' 295000',
 ' 335000',
 ' 200000',
 ' 2499999',
 ' 490000',
 ' 100000',
 ' 155000',
 ' 295000',
 ' 555000',
 ' 165000',
 ' 735000',
 ' 340000',
 ' 375001',
 ' 1375000',
 ' 775000',
 ' 1675000',
 ' 1250000',
 ' 735000',
 ' 425000',
 ' 875000',
 ' 945000',
 ' 625000',
 ' 635000',
 ' 485000',
 ' 645000',
 ' 580000',
 ' 185000',
 ' 2925000',
 ' 750000',
 ' 215000',
 ' 525000',
 ' 550000',
 ' 265000',
 ' 615000',
 ' 340000',
 ' 450000',
 ' 699000',
 ' 250000',
 ' 575000',
 ' 725000',
 ' 375000',
 ' 711000',
 ' 1950000',
 ' 115000',
 ' 675000',
 ' 395000',
 ' 249000',
 ' 225001',
 ' 660001',
 ' 450000',
 ' 170000',
 ' 441000',
 ' 398000',
 ' 120000',
 ' 635000',
 ' 1500000',
 ' 799000',
 ' 290000',
 ' 525000',
 ' 625000',
 ' 325000',
 ' 1345000',
 ' 699999',
 ' 760786',
 ' 360000',
 ' 210000',
 ' 325000',
 ' 1050000',
 ' 135000',
 ' 347000',
 ' 245000',
 ' 600000',
 ' 475000',
 ' 1725000',
 ' 141000',
 ' 500000',
 ' 1651000',
 ' 358000',
 ' 445000',
 ' 2145000',
 ' 745000',
 ' 1250000',
 ' 170000',
 ' 2250000',
 ' 875000',
 ' 220000',
 ' 420000',
 ' 305000',
 ' 377000',
 ' 290000',
 ' 1250000',
 ' 368000',
 ' 2599000',
 ' 499000',
 ' 2990000',
 ' 215000',
 ' 2700000',
 ' 35000',
 ' 20000',
 ' 20000',
 ' 20000',
 ' 20000',
 ' 1650000',
 ' 695000',
 ' 595000',
 ' 545000',
 ' 650000',
 ' 20000',
 ' 944000',
 ' 15000',
 ' 15000',
 ' 20000',
 ' 200000',
 ' 3990000',
 ' 190000',
 ' 3000000',
 ' 944000',
 ' 795000',
 ' 296000',
 ' 751000',
 ' 225000',
 ' 695000']

In [11]:
#Converting the column into integer type

for i in range(0, len(Price)):
    Price[i] = int(Price[i])

In [12]:
#Printing the Price

Price

[1095001,
 595000,
 475000,
 320000,
 825000,
 599000,
 395000,
 198000,
 90000,
 410000,
 999000,
 650000,
 1055000,
 949999,
 1890000,
 350000,
 394000,
 399000,
 210000,
 535000,
 295000,
 460000,
 1650000,
 600000,
 200000,
 275000,
 120000,
 33000,
 335000,
 900000,
 825000,
 435000,
 555000,
 550000,
 495000,
 725000,
 885000,
 310000,
 210000,
 1540000,
 361000,
 2650000,
 130000,
 170000,
 380000,
 230000,
 600000,
 995000,
 1175000,
 435000,
 1699999,
 650000,
 595000,
 7990000,
 2499000,
 485000,
 165000,
 12200000,
 299999,
 535000,
 849000,
 2075000,
 1290000,
 180000,
 170000,
 280000,
 1600000,
 580000,
 50000,
 264000,
 330000,
 105000,
 50000,
 575000,
 518000,
 350000,
 285000,
 210000,
 475000,
 865000,
 7700000,
 425000,
 1425000,
 85000,
 780000,
 2148000,
 225000,
 368000,
 460000,
 410000,
 100000,
 3000000,
 225000,
 1250000,
 325000,
 250000,
 497000,
 4900000,
 199999,
 299999,
 765000,
 890000,
 415000,
 280000,
 100000,
 1090000,
 388000,
 321000,
 499000,
 649000,
 1560000,
 410000,
 185000,
 485000,
 628000,
 510000,
 1750000,
 425000,
 70000,
 910000,
 485000,
 375000,
 545000,
 130000,
 425000,
 398000,
 486000,
 361000,
 1249000,
 95000,
 12500000,
 265000,
 400000,
 350000,
 475000,
 375000,
 1700000,
 345000,
 725000,
 125000,
 111000,
 1599000,
 1275000,
 450000,
 385000,
 145000,
 155000,
 348000,
 450000,
 427000,
 397000,
 175000,
 136000,
 895000,
 200000,
 155000,
 125000,
 149000,
 289000,
 555000,
 1075000,
 345000,
 1650000,
 130000,
 120000,
 199999,
 290000,
 229000,
 369000,
 333000,
 5400000,
 300000,
 1099000,
 145000,
 1199000,
 375000,
 1099000,
 350000,
 799000,
 230000,
 875000,
 245000,
 751000,
 130000,
 280000,
 390000,
 3200000,
 1650000,
 775000,
 735000,
 355000,
 650000,
 2290000,
 5800000,
 950000,
 1199999,
 1050000,
 175000,
 215000,
 260000,
 250000,
 400000,
 959999,
 195000,
 625000,
 690000,
 694000,
 198000,
 320000,
 160000,
 2775000,
 2750000,
 115000,
 90000,
 1349999,
 3400000,
 2500000,
 255000,
 2150000,
 110000,
 2350000,
 890000,
 1375000,
 230000,
 107000,
 700000,
 7700000,
 2255000,
 755000,
 165000,
 692000,
 765000,
 275000,
 1299000,
 1645000,
 205000,
 400000,
 240000,
 250000,
 225000,
 2221000,
 1850000,
 666970,
 245000,
 150000,
 690000,
 125000,
 1385000,
 475000,
 1125000,
 850000,
 595000,
 751000,
 1025000,
 750000,
 840000,
 1075000,
 935000,
 555000,
 1625000,
 349000,
 875000,
 1490000,
 375000,
 195000,
 899000,
 5600000,
 160000,
 349000,
 270000,
 324000,
 255000,
 139000,
 1299000,
 575000,
 750000,
 290000,
 899999,
 245000,
 475000,
 750000,
 600000,
 400000,
 350000,
 350000,
 799000,
 1099999,
 1024999,
 225000,
 145000,
 1350000,
 2400000,
 550000,
 225000,
 499000,
 425000,
 625000,
 3600000,
 795000,
 1250000,
 235000,
 1199999,
 2675000,
 95000,
 140000,
 1925000,
 1925000,
 1755000,
 850000,
 120000,
 229000,
 650000,
 174000,
 430000,
 1000000,
 2150000,
 2150000,
 611000,
 331000,
 425000,
 2800000,
 800000,
 1050000,
 100000,
 290000,
 89000,
 829000,
 339000,
 189000,
 99999,
 650000,
 1945000,
 299000,
 495000,
 675000,
 4875000,
 265000,
 181000,
 549000,
 395000,
 199000,
 575000,
 3200000,
 113000,
 65000,
 3300000,
 1350000,
 1895000,
 745000,
 7900000,
 445000,
 325000,
 270000,
 995000,
 445000,
 545000,
 1145000,
 375000,
 675000,
 495000,
 375000,
 2299999,
 425000,
 280000,
 330001,
 775000,
 435000,
 210000,
 185000,
 720000,
 2500000,
 295000,
 275000,
 649000,
 1075000,
 325000,
 525000,
 395000,
 295000,
 335000,
 200000,
 2499999,
 490000,
 100000,
 155000,
 295000,
 555000,
 165000,
 735000,
 340000,
 375001,
 1375000,
 775000,
 1675000,
 1250000,
 735000,
 425000,
 875000,
 945000,
 625000,
 635000,
 485000,
 645000,
 580000,
 185000,
 2925000,
 750000,
 215000,
 525000,
 550000,
 265000,
 615000,
 340000,
 450000,
 699000,
 250000,
 575000,
 725000,
 375000,
 711000,
 1950000,
 115000,
 675000,
 395000,
 249000,
 225001,
 660001,
 450000,
 170000,
 441000,
 398000,
 120000,
 635000,
 1500000,
 799000,
 290000,
 525000,
 625000,
 325000,
 1345000,
 699999,
 760786,
 360000,
 210000,
 325000,
 1050000,
 135000,
 347000,
 245000,
 600000,
 475000,
 1725000,
 141000,
 500000,
 1651000,
 358000,
 445000,
 2145000,
 745000,
 1250000,
 170000,
 2250000,
 875000,
 220000,
 420000,
 305000,
 377000,
 290000,
 1250000,
 368000,
 2599000,
 499000,
 2990000,
 215000,
 2700000,
 35000,
 20000,
 20000,
 20000,
 20000,
 1650000,
 695000,
 595000,
 545000,
 650000,
 20000,
 944000,
 15000,
 15000,
 20000,
 200000,
 3990000,
 190000,
 3000000,
 944000,
 795000,
 296000,
 751000,
 225000,
 695000]

In [13]:
#Fetching data from olx for Year

for y in driver.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Year.append(y.text.split('-')[0])

In [14]:
#Converting the column into integer type

for i in range(0, len(Year)):
    Year[i] = int(Year[i])

In [15]:
#Converting year into integer type

Year

[2019,
 2016,
 2011,
 2018,
 2014,
 2016,
 2012,
 2008,
 2007,
 2014,
 2016,
 2017,
 2016,
 2018,
 2018,
 2013,
 2015,
 2012,
 2012,
 2016,
 2011,
 2013,
 2018,
 2019,
 2007,
 2011,
 2005,
 2021,
 2012,
 2019,
 2017,
 2014,
 2015,
 2017,
 1996,
 2015,
 2011,
 2010,
 2009,
 2012,
 2011,
 2014,
 2005,
 2010,
 2008,
 2005,
 2020,
 2017,
 2019,
 2017,
 2017,
 2014,
 2007,
 2018,
 2013,
 2013,
 2009,
 2020,
 2012,
 2016,
 2014,
 2021,
 2020,
 2008,
 2010,
 2011,
 2015,
 2015,
 2021,
 2011,
 2016,
 2008,
 2021,
 2015,
 2015,
 2014,
 2014,
 2009,
 2018,
 2012,
 2017,
 2012,
 2018,
 2006,
 2016,
 2016,
 2012,
 2016,
 2010,
 2017,
 2021,
 2017,
 2012,
 2011,
 2008,
 2014,
 2014,
 2018,
 2009,
 2010,
 2015,
 2011,
 2012,
 2010,
 2008,
 2013,
 2016,
 2010,
 2015,
 2017,
 2016,
 2011,
 2009,
 2013,
 2016,
 2018,
 2015,
 2013,
 2021,
 2018,
 2014,
 2008,
 2012,
 2007,
 2017,
 2014,
 2017,
 2007,
 2012,
 2005,
 2012,
 2011,
 2013,
 2008,
 2013,
 2012,
 2018,
 2012,
 2015,
 2007,
 2007,
 2017,
 2019,
 2015,
 2012,
 2009,
 2009,
 2013,
 2007,
 2015,
 2017,
 2011,
 2008,
 2012,
 2010,
 2007,
 2006,
 2005,
 2008,
 2017,
 2020,
 2012,
 2013,
 2016,
 2016,
 2007,
 2010,
 2012,
 2010,
 2007,
 2017,
 2014,
 2008,
 2008,
 2010,
 2008,
 2011,
 2006,
 2012,
 2006,
 2019,
 2010,
 2012,
 2007,
 2017,
 2008,
 2018,
 2017,
 2019,
 2020,
 2010,
 2015,
 2015,
 2019,
 2010,
 2014,
 2010,
 2010,
 2010,
 2015,
 2010,
 2012,
 2019,
 2010,
 2012,
 2012,
 2015,
 2008,
 2012,
 2010,
 2017,
 2010,
 2009,
 2008,
 2016,
 2018,
 2014,
 2012,
 2021,
 2006,
 2016,
 2018,
 2015,
 2016,
 2010,
 2021,
 2021,
 2018,
 2017,
 2009,
 2013,
 2010,
 2009,
 2014,
 2017,
 2009,
 2011,
 2012,
 2010,
 2008,
 2019,
 2015,
 2021,
 2016,
 2006,
 2021,
 2006,
 2020,
 2010,
 2014,
 2018,
 2015,
 2014,
 2017,
 2019,
 2019,
 2021,
 2019,
 2014,
 2015,
 2015,
 2014,
 2018,
 2015,
 2007,
 2018,
 2019,
 2009,
 2013,
 2011,
 2009,
 2011,
 2012,
 2018,
 2016,
 2015,
 2011,
 2010,
 2012,
 2012,
 2018,
 2011,
 2012,
 2012,
 2007,
 2017,
 2013,
 2015,
 2009,
 2008,
 2012,
 2010,
 2008,
 2009,
 2015,
 2014,
 2015,
 2020,
 2017,
 2019,
 2009,
 2011,
 2017,
 2007,
 2011,
 2019,
 2019,
 2019,
 2014,
 2008,
 2008,
 2016,
 2008,
 2015,
 2011,
 2017,
 2014,
 2010,
 2014,
 2014,
 2016,
 2017,
 2019,
 2014,
 2012,
 2008,
 2017,
 2012,
 2009,
 2008,
 2017,
 2013,
 2010,
 2011,
 2017,
 2016,
 2010,
 2013,
 2015,
 2015,
 2010,
 2014,
 2015,
 2008,
 2008,
 2018,
 2012,
 2016,
 2018,
 2018,
 2013,
 2012,
 2010,
 2017,
 2015,
 2016,
 2019,
 2017,
 2017,
 2014,
 2016,
 2015,
 2016,
 2014,
 2017,
 2008,
 2015,
 2011,
 2011,
 2018,
 2018,
 2008,
 2011,
 2018,
 2010,
 2012,
 2012,
 2012,
 2014,
 2011,
 2011,
 2011,
 2020,
 2007,
 2016,
 2011,
 2016,
 2009,
 2017,
 2013,
 2010,
 2002,
 2017,
 2019,
 2011,
 2017,
 2017,
 2012,
 2018,
 2013,
 2015,
 2017,
 2017,
 2018,
 2010,
 2017,
 2016,
 2009,
 2015,
 2015,
 2010,
 2015,
 2014,
 2016,
 2017,
 2010,
 2010,
 2016,
 2015,
 2018,
 2020,
 2009,
 2020,
 2009,
 2017,
 2011,
 2011,
 2012,
 2008,
 2011,
 2013,
 2008,
 2013,
 2015,
 2017,
 2013,
 2012,
 2014,
 2009,
 2017,
 2011,
 2016,
 2015,
 2008,
 2011,
 2016,
 2008,
 2012,
 2009,
 2018,
 2018,
 2014,
 2007,
 2008,
 2015,
 2013,
 2014,
 2016,
 2017,
 2018,
 2009,
 2017,
 2018,
 2012,
 2013,
 2011,
 2012,
 2011,
 2015,
 2011,
 2019,
 2016,
 2012,
 2011,
 2017,
 2017,
 1990,
 1991,
 1989,
 1987,
 2016,
 2017,
 2013,
 2016,
 2012,
 1990,
 2018,
 1985,
 1983,
 1984,
 2010,
 2017,
 2012,
 2015,
 2015,
 2007,
 2011,
 2019,
 2011,
 2017]

In [47]:
#Fetching data from olx for Km used, Company, Location, Date of posting

for k in driver.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Km.append(k.text.split('-')[1])
for c in driver.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[2]"):
    Company.append(c.text)
for l in driver.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]"):
    Location.append(l.text)
for d in driver.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]/span"):
    Date.append(d.text)

In [48]:
#Making a dataframe named Cars storing 500 data into that

CARS=pd.DataFrame({})
CARS['PRICE']=Price[0:500]
CARS['YEAR']=Year[0:500]
CARS['KM']=Km[0:500]
CARS['COMPANY']=Company[0:500]
CARS['LOCATION']=Location[0:500]
CARS['POSTED-DATE']=Date[0:500]

In [49]:
#Printing the dataframe of CARS that we have created 

CARS

,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE
0,1095001,2019,"18,000 km",Maruti Suzuki Ertiga,Vile Parle East\n6 days ago,6 days ago
1,595000,2016,"38,000 km",Toyota Etios,Chembur\nDec 23,Dec 23
2,475000,2011,"67,000 km",Toyota Corolla Altis,Chembur\nDec 23,Dec 23
3,320000,2018,"90,000 km",Maruti Suzuki Wagon R,Dharavi\nToday,Today
4,825000,2014,"90,000 km",Toyota Corolla Altis,Chembur\nToday,Today
...,...,...,...,...,...,...
495,795000,2007,"136,210 km",Mitsubishi Montero,Bandra West\nYesterday,Yesterday
496,296000,2011,"61,000 km",Hyundai i10,Wadala West\nYesterday,Yesterday
497,751000,2019,"12,347 km",Maruti Suzuki Swift Dzire,Khar West\nYesterday,Yesterday
498,225000,2011,"119,000 km",Maruti Suzuki Ritz,Vinobha Bhave Nagar\nYesterday,Yesterday
499,695000,2017,"55,000 km",Maruti Suzuki Vitara Brezza,Sion West\nYesterday,Yesterday

In [50]:
#Printing the information of the dataset
#Here we can see 2 columns are of integer type & others are of object datatype

CARS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRICE        500 non-null    int64
 1   YEAR         500 non-null    int64
 2   KM           500 non-null    object
 3   COMPANY      500 non-null    object
 4   LOCATION     500 non-null    object
 5   POSTED-DATE  500 non-null    object
dtypes: int64(2), object(4)
memory usage: 23.6+ KB

In [51]:
#Closing the driver

driver.close()

# WE HAVE SCRAPED 500 DATA FROM OLX

In [52]:
#Creating second instance for CHROME

driver2 = webdriver.Chrome(r'E:/CHROME-DRIVER/chromedriver_win32/chromedriver.exe')

In [53]:
#Getting to the website

driver2.get('https://www.olx.in/en-in/madhya-pradesh_g2001162/cars_c84')

In [78]:
#Creating empty lists so that we can fetch the data

Price_2=[]
Year_2=[]
Km_2=[]
Company_2=[]
Location_2=[]
Date_2=[]

In [60]:
#Fething the data from olx from Price

for p2 in driver2.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/span"):
    Price_2.append(p2.text.replace("â‚¹","").replace(",",""))

In [61]:
#Printintg the Price

Price_2

[' 565000',
 ' 790000',
 ' 415000',
 ' 115000',
 ' 865000',
 ' 595000',
 ' 435000',
 ' 140000',
 ' 690000',
 ' 260000',
 ' 525000',
 ' 1100000',
 ' 610000',
 ' 350000',
 ' 625000',
 ' 225000',
 ' 425000',
 ' 475000',
 ' 250000',
 ' 551000',
 ' 750000',
 ' 325000',
 ' 425000',
 ' 350000',
 ' 450000',
 ' 680000',
 ' 325000',
 ' 825000',
 ' 645000',
 ' 285000',
 ' 380000',
 ' 540000',
 ' 230000',
 ' 160000',
 ' 200000',
 ' 175000',
 ' 160000',
 ' 60000',
 ' 325000',
 ' 140000',
 ' 1400000',
 ' 725000',
 ' 580000',
 ' 775000',
 ' 1050000',
 ' 1590000',
 ' 300000',
 ' 125000',
 ' 260000',
 ' 121000',
 ' 150000',
 ' 130000',
 ' 195000',
 ' 250000',
 ' 750000',
 ' 355000',
 ' 450000',
 ' 750000',
 ' 28000',
 ' 450000',
 ' 390000',
 ' 650000',
 ' 550000',
 ' 350000',
 ' 470000',
 ' 700000',
 ' 550000',
 ' 675000',
 ' 555000',
 ' 315000',
 ' 310000',
 ' 130000',
 ' 1450000',
 ' 270000',
 ' 135000',
 ' 510000',
 ' 350000',
 ' 110000',
 ' 43000',
 ' 354000',
 ' 340000',
 ' 700000',
 ' 425000',
 ' 355000',
 ' 2400000',
 ' 225000',
 ' 510000',
 ' 650000',
 ' 490000',
 ' 85000',
 ' 825000',
 ' 825000',
 ' 915000',
 ' 650000',
 ' 230000',
 ' 430000',
 ' 490000',
 ' 255000',
 ' 290000',
 ' 465000',
 ' 390000',
 ' 540000',
 ' 321000',
 ' 349999',
 ' 685000',
 ' 240000',
 ' 611000',
 ' 1050000',
 ' 500000',
 ' 500000',
 ' 380000',
 ' 400000',
 ' 425000',
 ' 750000',
 ' 700000',
 ' 495000',
 ' 320000',
 ' 160000',
 ' 375000',
 ' 380000',
 ' 625000',
 ' 370000',
 ' 425000',
 ' 85000',
 ' 180000',
 ' 1050000',
 ' 400000',
 ' 75999',
 ' 330000',
 ' 100000',
 ' 380000',
 ' 120000',
 ' 385000',
 ' 130000',
 ' 150000',
 ' 165000',
 ' 88000',
 ' 660000',
 ' 485000',
 ' 275000',
 ' 440000',
 ' 450000',
 ' 995000',
 ' 415000',
 ' 125000',
 ' 400000',
 ' 365000',
 ' 645000',
 ' 965000',
 ' 265000',
 ' 700000',
 ' 115000',
 ' 130000',
 ' 590000',
 ' 175000',
 ' 325000',
 ' 825000',
 ' 1695000',
 ' 120000',
 ' 410000',
 ' 885000',
 ' 1800000',
 ' 310000',
 ' 165000',
 ' 560000',
 ' 1100000',
 ' 255000',
 ' 80000',
 ' 100000',
 ' 90000',
 ' 685000',
 ' 295000',
 ' 165000',
 ' 550000',
 ' 165000',
 ' 395000',
 ' 100000',
 ' 350000',
 ' 110000',
 ' 410000',
 ' 390000',
 ' 425000',
 ' 690000',
 ' 395000',
 ' 655000',
 ' 849000',
 ' 575000',
 ' 385000',
 ' 85000',
 ' 1350000',
 ' 55000',
 ' 115000',
 ' 125000',
 ' 360000',
 ' 280000',
 ' 725000',
 ' 400000',
 ' 510000',
 ' 515000',
 ' 285000',
 ' 1125000',
 ' 875000',
 ' 330000',
 ' 311000',
 ' 4000000',
 ' 140000',
 ' 280000',
 ' 190000',
 ' 490000',
 ' 320000',
 ' 1000000',
 ' 325000',
 ' 420000',
 ' 1100000',
 ' 365000',
 ' 590000',
 ' 525000',
 ' 645000',
 ' 95000',
 ' 3000000',
 ' 550000',
 ' 675000',
 ' 485000',
 ' 650000',
 ' 750000',
 ' 150000',
 ' 721000',
 ' 120000',
 ' 315000',
 ' 220000',
 ' 350000',
 ' 360000',
 ' 390000',
 ' 365000',
 ' 705000',
 ' 841000',
 ' 1350000',
 ' 450000',
 ' 79000',
 ' 1700000',
 ' 390000',
 ' 965000',
 ' 450000',
 ' 265000',
 ' 1850000',
 ' 865000',
 ' 451000',
 ' 475000',
 ' 380000',
 ' 925000',
 ' 680000',
 ' 135000',
 ' 399990',
 ' 135000',
 ' 240000',
 ' 590000',
 ' 430000',
 ' 285000',
 ' 650000',
 ' 285000',
 ' 375000',
 ' 580000',
 ' 565000',
 ' 975000',
 ' 310000',
 ' 775000',
 ' 600000',
 ' 285000',
 ' 580000',
 ' 680000',
 ' 140000',
 ' 210000',
 ' 200000',
 ' 55000',
 ' 365000',
 ' 360000',
 ' 400000',
 ' 821000',
 ' 165000',
 ' 500000',
 ' 600000',
 ' 1500000',
 ' 460000',
 ' 440000',
 ' 1775000',
 ' 345000',
 ' 225000',
 ' 350000',
 ' 250000',
 ' 850000',
 ' 325000',
 ' 500000',
 ' 285000',
 ' 600000',
 ' 450000',
 ' 180000',
 ' 515000',
 ' 1000000',
 ' 270000',
 ' 260000',
 ' 250000',
 ' 450000',
 ' 270000',
 ' 120000',
 ' 181000',
 ' 450000',
 ' 625000',
 ' 250000',
 ' 350000',
 ' 425000',
 ' 425000',
 ' 720000',
 ' 329000',
 ' 185000',
 ' 215000',
 ' 285000',
 ' 520000',
 ' 390000',
 ' 510000',
 ' 1400000',
 ' 525000',
 ' 540000',
 ' 390000',
 ' 69000',
 ' 900000',
 ' 149999',
 ' 250000',
 ' 350000',
 ' 220000',
 ' 1590000',
 ' 825000',
 ' 490000',
 ' 175000',
 ' 350000',
 ' 100000',
 ' 450000',
 ' 990000',
 ' 590000',
 ' 680000',
 ' 280000',
 ' 895000',
 ' 325000',
 ' 890000',
 ' 485000',
 ' 250000',
 ' 740000',
 ' 610000',
 ' 575000',
 ' 110000',
 ' 200000',
 ' 460000',
 ' 650000',
 ' 245000',
 ' 715000',
 ' 625000',
 ' 180000',
 ' 1325000',
 ' 950000',
 ' 450000',
 ' 311000',
 ' 120000',
 ' 95000',
 ' 191000',
 ' 1975000',
 ' 609000',
 ' 750000',
 ' 815000',
 ' 265000',
 ' 890000',
 ' 195000',
 ' 157000',
 ' 495000',
 ' 390000',
 ' 325000',
 ' 2650000',
 ' 2950000',
 ' 335000',
 ' 280000',
 ' 550000',
 ' 325000',
 ' 180000',
 ' 420000',
 ' 990000',
 ' 140000',
 ' 430000',
 ' 700000',
 ' 490999',
 ' 450000',
 ' 819999',
 ' 800000',
 ' 1925000',
 ' 750000',
 ' 200000',
 ' 520000',
 ' 700000',
 ' 1400000',
 ' 380000',
 ' 650000',
 ' 600000',
 ' 1325000',
 ' 1290000',
 ' 50000',
 ' 170000',
 ' 260000',
 ' 115000',
 ' 325000',
 ' 130000',
 ' 325000',
 ' 360000',
 ' 170000',
 ' 400000',
 ' 850000',
 ' 175000',
 ' 500000',
 ' 499999',
 ' 875000',
 ' 450000',
 ' 650000',
 ' 50000',
 ' 235000',
 ' 670000',
 ' 150000',
 ' 665000',
 ' 1600000',
 ' 85000',
 ' 250000',
 ' 725000',
 ' 850000',
 ' 1700000',
 ' 2200000',
 ' 40000',
 ' 600000',
 ' 1050000',
 ' 1975000',
 ' 210000',
 ' 1000000',
 ' 285000',
 ' 1150000',
 ' 675000',
 ' 675000',
 ' 650000',
 ' 650000',
 ' 1311000',
 ' 800000',
 ' 260000',
 ' 525000',
 ' 650000',
 ' 1550000',
 ' 550000',
 ' 650000',
 ' 750000',
 ' 2750000',
 ' 2800000',
 ' 375000',
 ' 595000',
 ' 710000',
 ' 211000',
 ' 375000',
 ' 375000',
 ' 1400000',
 ' 1400000',
 ' 130000',
 ' 675000',
 ' 675000',
 ' 490000',
 ' 300000',
 ' 115000',
 ' 1075000',
 ' 1950000',
 ' 450000',
 ' 65000',
 ' 450000',
 ' 421000',
 ' 750000',
 ' 260000',
 ' 775000',
 ' 455000',
 ' 700000',
 ' 480000',
 ' 435000',
 ' 200000',
 ' 2950000',
 ' 780000',
 ' 380000',
 ' 950000',
 ' 660000',
 ' 1000000',
 ' 790000',
 ' 275000',
 ' 765000',
 ' 165000',
 ' 625000',
 ' 575000',
 ' 1325000',
 ' 240000',
 ' 640000',
 ' 450000',
 ' 285000',
 ' 380000',
 ' 525000',
 ' 400000',
 ' 725000',
 ' 755000',
 ' 50000',
 ' 680000',
 ' 180000',
 ' 375000',
 ' 450000',
 ' 265000',
 ' 270000',
 ' 111000',
 ' 220000',
 ' 610000',
 ' 1100000',
 ' 299000',
 ' 50000',
 ' 250000',
 ' 430000',
 ' 340000',
 ' 180000',
 ' 610000',
 ' 625000',
 ' 350000',
 ' 370000',
 ' 235000',
 ' 360000',
 ' 540000',
 ' 310000',
 ' 430000',
 ' 450000',
 ' 195000',
 ' 85000',
 ' 510000',
 ' 560000',
 ' 685000',
 ' 525000',
 ' 105000',
 ' 500000',
 ' 450000',
 ' 1000000',
 ' 145000',
 ' 40000',
 ' 382500',
 ' 580000',
 ' 240000',
 ' 485000',
 ' 285000',
 ' 570000',
 ' 999000',
 ' 2700000',
 ' 375000',
 ' 190000',
 ' 960000',
 ' 125000',
 ' 675000',
 ' 20000',
 ' 700000',
 ' 580000',
 ' 150000',
 ' 440000',
 ' 295000',
 ' 65000',
 ' 70000',
 ' 330000',
 ' 260000',
 ' 160000',
 ' 300000',
 ' 230000',
 ' 635000',
 ' 695000',
 ' 675000',
 ' 250000',
 ' 450000',
 ' 320000',
 ' 160000',
 ' 151000',
 ' 311000',
 ' 150000',
 ' 65000',
 ' 410000',
 ' 485000',
 ' 389000',
 ' 130000',
 ' 450000',
 ' 185000',
 ' 235000',
 ' 470000',
 ' 110000',
 ' 1400000',
 ' 425000',
 ' 460000',
 ' 250000',
 ' 370000',
 ' 290000',
 ' 1000000',
 ' 620000',
 ' 1050000',
 ' 450000',
 ' 340000',
 ' 265000',
 ' 305000',
 ' 685000',
 ' 455000',
 ' 1100000',
 ' 875000',
 ' 615000',
 ' 285000',
 ' 525000',
 ' 125000',
 ' 325000',
 ' 450000',
 ' 625000',
 ' 210000',
 ' 375000',
 ' 1950000',
 ' 400000',
 ' 700000',
 ' 4100000',
 ' 280000',
 ' 620000',
 ' 100000',
 ' 621000',
 ' 2800000',
 ' 245000',
 ' 69999',
 ' 200000',
 ' 775000',
 ' 685000',
 ' 390000',
 ' 205000',
 ' 490000',
 ' 150000',
 ' 590000',
 ' 185000',
 ' 135000',
 ' 590000',
 ' 150000',
 ' 1450000',
 ' 160000',
 ' 469000',
 ' 100000',
 ' 29500',
 ' 320000',
 ' 1175000',
 ' 610000',
 ' 425000',
 ' 235000',
 ' 165000',
 ' 329999',
 ' 499000',
 ' 325000',
 ' 525000',
 ' 275000',
 ' 730000',
 ' 925000',
 ' 560000',
 ' 695000',
 ' 2200000',
 ' 650000',
 ' 1575000',
 ' 625000',
 ' 210000',
 ' 300000',
 ' 410000',
 ' 575000',
 ' 790000',
 ' 1300000',
 ' 300000',
 ' 170000',
 ' 240000',
 ' 810000',
 ' 200000',
 ' 72500',
 ' 180000',
 ' 195000',
 ' 695000',
 ' 1100000',
 ' 1550000',
 ' 665000',
 ' 475000',
 ' 695000',
 ' 465000',
 ' 100000',
 ' 495000',
 ' 265000',
 ' 490000',
 ' 950000',
 ' 415000',
 ' 40000',
 ' 825000',
 ' 550000',
 ' 500000',
 ' 4100000',
 ' 15000',
 ' 425000',
 ' 290000',
 ' 55000',
 ' 425000',
 ' 2750000',
 ' 450000',
 ' 190000',
 ' 1750000',
 ' 650000',
 ' 825000',
 ' 1600000',
 ' 260000',
 ' 350000',
 ' 300000',
 ' 800000',
 ' 220000',
 ' 110000',
 ' 750000',
 ' 375000',
 ' 650000',
 ' 1025000',
 ' 280000',
 ' 170000',
 ' 230000',
 ' 750000',
 ' 285000',
 ' 550000',
 ' 265000',
 ' 375000',
 ' 650000',
 ' 650000',
 ' 100000',
 ' 325000',
 ' 465000',
 ' 45000',
 ' 50000',
 ' 615000',
 ' 1195000',
 ' 610000',
 ' 610000',
 ' 575000',
 ' 875000',
 ' 320000',
 ' 75000',
 ' 675000',
 ' 800000',
 ' 490000',
 ' 325000',
 ' 750000',
 ' 66000',
 ' 170000',
 ' 580000',
 ' 510000',
 ' 950000',
 ' 725000',
 ' 100000',
 ' 745000',
 ' 450000',
 ' 430000',
 ' 625000',
 ' 875000',
 ' 860000',
 ' 1011000',
 ' 950000',
 ' 940000',
 ' 299000',
 ' 350000',
 ' 100000',
 ' 165000',
 ' 3000000',
 ' 330000',
 ' 500000',
 ' 480000',
 ' 80000',
 ' 375000',
 ' 440000',
 ' 1590000',
 ' 2250000',
 ' 255000',
 ' 875000',
 ' 230000',
 ' 425000',
 ' 495000',
 ' 120000',
 ' 15000',
 ' 225000',
 ' 710000',
 ' 225000',
 ' 230000',
 ' 150000',
 ' 425000',
 ' 150000',
 ' 300000',
 ' 105000',
 ' 35000',
 ' 85000',
 ' 425000',
 ' 170000',
 ' 475000',
 ' 1025000',
 ' 455000',
 ' 275000',
 ' 450000',
 ' 735000',
 ' 585000',
 ' 340000',
 ' 625000',
 ' 290000',
 ' 425000',
 ' 1390000',
 ' 525000',
 ' 711000',
 ' 540000',
 ' 850000',
 ' 450000',
 ' 3551000',
 ' 411000',
 ' 255000',
 ' 125000',
 ' 650000',
 ' 540000',
 ' 500000',
 ' 500000',
 ' 450000',
 ' 440000',
 ' 650000',
 ' 2200000',
 ' 350000',
 ' 1700000',
 ' 4000000',
 ' 200000',
 ' 630000',
 ' 660000',
 ' 321000',
 ' 95000',
 ' 151000',
 ' 450000',
 ' 790000',
 ' 395000',
 ' 300000',
 ' 295000',
 ' 390000',
 ' 500000',
 ' 590000',
 ' 85000',
 ' 310000',
 ' 250000',
 ' 380000',
 ' 540000',
 ' 460000',
 ' 500000',
 ' 265000',
 ' 300000',
 ' 325000',
 ' 240000',
 ' 345000',
 ' 390000',
 ' 345000',
 ' 180000',
 ' 380000',
 ' 95000',
 ' 275000',
 ' 3600000',
 ' 725000',
 ' 650000',
 ' 925000',
 ' 950000',
 ' 1050000',
 ' 700000',
 ' 330000',
 ' 350000',
 ' 320000',
 ' 535000',
 ' 410000',
 ' 735000',
 ' 550000',
 ' 425000',
 ' 85000',
 ' 425000',
 ' 525000',
 ' 825000',
 ' 665000',
 ' 420000',
 ' 475000',
 ' 135000',
 ' 590000',
 ' 295000',
 ' 200000',
 ' 850000',
 ' 250000',
 ' 100000',
 ' 570000',
 ' 710000',
 ' 449000',
 ' 999000',
 ' 655000',
 ' 750000',
 ' 425000',
 ' 300000',
 ' 410000',
 ' 180000',
 ' 340000',
 ' 170000',
 ' 885000',
 ' 795000',
 ' 875000',
 ' 435000',
 ' 975000',
 ' 160000',
 ' 375000',
 ' 530000',
 ' 750000',
 ' 150000',
 ' 550000',
 ' 670000',
 ' 900000',
 ' 1725000',
 ' 275000',
 ' 140000',
 ' 90000',
 ' 410000',
 ' 190000',
 ' 220000',
 ' 160000',
 ' 2850000',
 ' 300000',
 ' 450000',
 ' 590000',
 ' 301000',
 ' 299999',
 ' 375000',
 ' 140000',
 ' 430000',
 ' 1850000',
 ' 500000',
 ' 72000',
 ' 580000',
 ' 189999',
 ' 130000',
 ' 400000',
 ' 275000',
 ' 450000',
 ' 300000',
 ' 350000',
 ' 450000',
 ' 550000',
 ' 245000',
 ' 310000',
 ' 400000',
 ' 495000',
 ' 270000',
 ' 645000',
 ' 415000',
 ' 250000',
 ' 90000',
 ' 350000',
 ' 235000',
 ' 85000',
 ' 190000',
 ' 175000',
 ' 45000',
 ' 15000',
 ' 250000',
 ' 110000',
 ' 310000',
 ' 160000',
 ' 630000',
 ' 550000',
 ' 590000',
 ' 425000',
 ' 725000',
 ' 475000',
 ' 75000',
 ' 240000',
 ' 75000',
 ' 815000',
 ' 730000',
 ' 1500000']

In [62]:
#Converting the datatype of the variable to int

for i in range(0, len(Price_2)):
    Price_2[i] = int(Price_2[i])

In [63]:
#Printing the variable after conversion

Price_2

[565000,
 790000,
 415000,
 115000,
 865000,
 595000,
 435000,
 140000,
 690000,
 260000,
 525000,
 1100000,
 610000,
 350000,
 625000,
 225000,
 425000,
 475000,
 250000,
 551000,
 750000,
 325000,
 425000,
 350000,
 450000,
 680000,
 325000,
 825000,
 645000,
 285000,
 380000,
 540000,
 230000,
 160000,
 200000,
 175000,
 160000,
 60000,
 325000,
 140000,
 1400000,
 725000,
 580000,
 775000,
 1050000,
 1590000,
 300000,
 125000,
 260000,
 121000,
 150000,
 130000,
 195000,
 250000,
 750000,
 355000,
 450000,
 750000,
 28000,
 450000,
 390000,
 650000,
 550000,
 350000,
 470000,
 700000,
 550000,
 675000,
 555000,
 315000,
 310000,
 130000,
 1450000,
 270000,
 135000,
 510000,
 350000,
 110000,
 43000,
 354000,
 340000,
 700000,
 425000,
 355000,
 2400000,
 225000,
 510000,
 650000,
 490000,
 85000,
 825000,
 825000,
 915000,
 650000,
 230000,
 430000,
 490000,
 255000,
 290000,
 465000,
 390000,
 540000,
 321000,
 349999,
 685000,
 240000,
 611000,
 1050000,
 500000,
 500000,
 380000,
 400000,
 425000,
 750000,
 700000,
 495000,
 320000,
 160000,
 375000,
 380000,
 625000,
 370000,
 425000,
 85000,
 180000,
 1050000,
 400000,
 75999,
 330000,
 100000,
 380000,
 120000,
 385000,
 130000,
 150000,
 165000,
 88000,
 660000,
 485000,
 275000,
 440000,
 450000,
 995000,
 415000,
 125000,
 400000,
 365000,
 645000,
 965000,
 265000,
 700000,
 115000,
 130000,
 590000,
 175000,
 325000,
 825000,
 1695000,
 120000,
 410000,
 885000,
 1800000,
 310000,
 165000,
 560000,
 1100000,
 255000,
 80000,
 100000,
 90000,
 685000,
 295000,
 165000,
 550000,
 165000,
 395000,
 100000,
 350000,
 110000,
 410000,
 390000,
 425000,
 690000,
 395000,
 655000,
 849000,
 575000,
 385000,
 85000,
 1350000,
 55000,
 115000,
 125000,
 360000,
 280000,
 725000,
 400000,
 510000,
 515000,
 285000,
 1125000,
 875000,
 330000,
 311000,
 4000000,
 140000,
 280000,
 190000,
 490000,
 320000,
 1000000,
 325000,
 420000,
 1100000,
 365000,
 590000,
 525000,
 645000,
 95000,
 3000000,
 550000,
 675000,
 485000,
 650000,
 750000,
 150000,
 721000,
 120000,
 315000,
 220000,
 350000,
 360000,
 390000,
 365000,
 705000,
 841000,
 1350000,
 450000,
 79000,
 1700000,
 390000,
 965000,
 450000,
 265000,
 1850000,
 865000,
 451000,
 475000,
 380000,
 925000,
 680000,
 135000,
 399990,
 135000,
 240000,
 590000,
 430000,
 285000,
 650000,
 285000,
 375000,
 580000,
 565000,
 975000,
 310000,
 775000,
 600000,
 285000,
 580000,
 680000,
 140000,
 210000,
 200000,
 55000,
 365000,
 360000,
 400000,
 821000,
 165000,
 500000,
 600000,
 1500000,
 460000,
 440000,
 1775000,
 345000,
 225000,
 350000,
 250000,
 850000,
 325000,
 500000,
 285000,
 600000,
 450000,
 180000,
 515000,
 1000000,
 270000,
 260000,
 250000,
 450000,
 270000,
 120000,
 181000,
 450000,
 625000,
 250000,
 350000,
 425000,
 425000,
 720000,
 329000,
 185000,
 215000,
 285000,
 520000,
 390000,
 510000,
 1400000,
 525000,
 540000,
 390000,
 69000,
 900000,
 149999,
 250000,
 350000,
 220000,
 1590000,
 825000,
 490000,
 175000,
 350000,
 100000,
 450000,
 990000,
 590000,
 680000,
 280000,
 895000,
 325000,
 890000,
 485000,
 250000,
 740000,
 610000,
 575000,
 110000,
 200000,
 460000,
 650000,
 245000,
 715000,
 625000,
 180000,
 1325000,
 950000,
 450000,
 311000,
 120000,
 95000,
 191000,
 1975000,
 609000,
 750000,
 815000,
 265000,
 890000,
 195000,
 157000,
 495000,
 390000,
 325000,
 2650000,
 2950000,
 335000,
 280000,
 550000,
 325000,
 180000,
 420000,
 990000,
 140000,
 430000,
 700000,
 490999,
 450000,
 819999,
 800000,
 1925000,
 750000,
 200000,
 520000,
 700000,
 1400000,
 380000,
 650000,
 600000,
 1325000,
 1290000,
 50000,
 170000,
 260000,
 115000,
 325000,
 130000,
 325000,
 360000,
 170000,
 400000,
 850000,
 175000,
 500000,
 499999,
 875000,
 450000,
 650000,
 50000,
 235000,
 670000,
 150000,
 665000,
 1600000,
 85000,
 250000,
 725000,
 850000,
 1700000,
 2200000,
 40000,
 600000,
 1050000,
 1975000,
 210000,
 1000000,
 285000,
 1150000,
 675000,
 675000,
 650000,
 650000,
 1311000,
 800000,
 260000,
 525000,
 650000,
 1550000,
 550000,
 650000,
 750000,
 2750000,
 2800000,
 375000,
 595000,
 710000,
 211000,
 375000,
 375000,
 1400000,
 1400000,
 130000,
 675000,
 675000,
 490000,
 300000,
 115000,
 1075000,
 1950000,
 450000,
 65000,
 450000,
 421000,
 750000,
 260000,
 775000,
 455000,
 700000,
 480000,
 435000,
 200000,
 2950000,
 780000,
 380000,
 950000,
 660000,
 1000000,
 790000,
 275000,
 765000,
 165000,
 625000,
 575000,
 1325000,
 240000,
 640000,
 450000,
 285000,
 380000,
 525000,
 400000,
 725000,
 755000,
 50000,
 680000,
 180000,
 375000,
 450000,
 265000,
 270000,
 111000,
 220000,
 610000,
 1100000,
 299000,
 50000,
 250000,
 430000,
 340000,
 180000,
 610000,
 625000,
 350000,
 370000,
 235000,
 360000,
 540000,
 310000,
 430000,
 450000,
 195000,
 85000,
 510000,
 560000,
 685000,
 525000,
 105000,
 500000,
 450000,
 1000000,
 145000,
 40000,
 382500,
 580000,
 240000,
 485000,
 285000,
 570000,
 999000,
 2700000,
 375000,
 190000,
 960000,
 125000,
 675000,
 20000,
 700000,
 580000,
 150000,
 440000,
 295000,
 65000,
 70000,
 330000,
 260000,
 160000,
 300000,
 230000,
 635000,
 695000,
 675000,
 250000,
 450000,
 320000,
 160000,
 151000,
 311000,
 150000,
 65000,
 410000,
 485000,
 389000,
 130000,
 450000,
 185000,
 235000,
 470000,
 110000,
 1400000,
 425000,
 460000,
 250000,
 370000,
 290000,
 1000000,
 620000,
 1050000,
 450000,
 340000,
 265000,
 305000,
 685000,
 455000,
 1100000,
 875000,
 615000,
 285000,
 525000,
 125000,
 325000,
 450000,
 625000,
 210000,
 375000,
 1950000,
 400000,
 700000,
 4100000,
 280000,
 620000,
 100000,
 621000,
 2800000,
 245000,
 69999,
 200000,
 775000,
 685000,
 390000,
 205000,
 490000,
 150000,
 590000,
 185000,
 135000,
 590000,
 150000,
 1450000,
 160000,
 469000,
 100000,
 29500,
 320000,
 1175000,
 610000,
 425000,
 235000,
 165000,
 329999,
 499000,
 325000,
 525000,
 275000,
 730000,
 925000,
 560000,
 695000,
 2200000,
 650000,
 1575000,
 625000,
 210000,
 300000,
 410000,
 575000,
 790000,
 1300000,
 300000,
 170000,
 240000,
 810000,
 200000,
 72500,
 180000,
 195000,
 695000,
 1100000,
 1550000,
 665000,
 475000,
 695000,
 465000,
 100000,
 495000,
 265000,
 490000,
 950000,
 415000,
 40000,
 825000,
 550000,
 500000,
 4100000,
 15000,
 425000,
 290000,
 55000,
 425000,
 2750000,
 450000,
 190000,
 1750000,
 650000,
 825000,
 1600000,
 260000,
 350000,
 300000,
 800000,
 220000,
 110000,
 750000,
 375000,
 650000,
 1025000,
 280000,
 170000,
 230000,
 750000,
 285000,
 550000,
 265000,
 375000,
 650000,
 650000,
 100000,
 325000,
 465000,
 45000,
 50000,
 615000,
 1195000,
 610000,
 610000,
 575000,
 875000,
 320000,
 75000,
 675000,
 800000,
 490000,
 325000,
 750000,
 66000,
 170000,
 580000,
 510000,
 950000,
 725000,
 100000,
 745000,
 450000,
 430000,
 625000,
 875000,
 860000,
 1011000,
 950000,
 940000,
 299000,
 350000,
 100000,
 165000,
 3000000,
 330000,
 500000,
 480000,
 80000,
 375000,
 440000,
 1590000,
 2250000,
 255000,
 875000,
 230000,
 425000,
 495000,
 120000,
 15000,
 225000,
 710000,
 225000,
 230000,
 150000,
 425000,
 150000,
 300000,
 105000,
 35000,
 85000,
 425000,
 170000,
 475000,
 1025000,
 455000,
 275000,
 450000,
 735000,
 585000,
 340000,
 625000,
 290000,
 425000,
 1390000,
 525000,
 711000,
 540000,
 850000,
 450000,
 3551000,
 411000,
 255000,
 125000,
 650000,
 540000,
 500000,
 500000,
 450000,
 440000,
 650000,
 2200000,
 350000,
 1700000,
 4000000,
 200000,
 630000,
 660000,
 321000,
 95000,
 151000,
 450000,
 790000,
 395000,
 300000,
 295000,
 390000,
 500000,
 590000,
 85000,
 310000,
 250000,
 380000,
 540000,
 460000,
 500000,
 265000,
 300000,
 325000,
 240000,
 345000,
 390000,
 345000,
 180000,
 380000,
 95000,
 275000,
 3600000,
 725000,
 650000,
 925000,
 950000,
 1050000,
 700000,
 330000,
 350000,
 320000,
 535000,
 410000,
 735000,
 550000,
 425000,
 85000,
 425000,
 525000,
 825000,
 665000,
 420000,
 475000,
 135000,
 590000,
 295000,
 200000,
 850000,
 250000,
 100000,
 570000,
 710000,
 449000,
 999000,
 655000,
 750000,
 425000,
 300000,
 410000,
 180000,
 340000,
 170000,
 885000,
 795000,
 875000,
 435000,
 975000,
 160000,
 375000,
 530000,
 750000,
 150000,
 550000,
 670000,
 900000,
 1725000,
 275000,
 140000,
 90000,
 410000,
 190000,
 220000,
 160000,
 2850000,
 300000,
 450000,
 590000,
 301000,
 299999,
 375000,
 140000,
 430000,
 1850000,
 500000,
 72000,
 580000,
 189999,
 130000,
 400000,
 275000,
 450000,
 300000,
 350000,
 450000,
 550000,
 245000,
 310000,
 400000,
 495000,
 270000,
 645000,
 415000,
 250000,
 90000,
 350000,
 235000,
 85000,
 190000,
 175000,
 45000,
 15000,
 250000,
 110000,
 310000,
 160000,
 630000,
 550000,
 590000,
 425000,
 725000,
 475000,
 75000,
 240000,
 75000,
 815000,
 730000,
 1500000]

In [79]:
#Fetching the data from olx for Year

for y2 in driver2.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Year_2.append(y2.text.split('-')[0])

In [81]:
#Printing year 2

Year_2

[2013,
 2019,
 2014,
 2007,
 2018,
 2018,
 2014,
 2009,
 2018,
 2008,
 2015,
 2018,
 2013,
 2011,
 2015,
 2011,
 2014,
 2016,
 2010,
 2015,
 2017,
 2011,
 2017,
 2013,
 2014,
 2013,
 2015,
 2019,
 2018,
 2011,
 2014,
 2019,
 2014,
 2011,
 2010,
 2012,
 2010,
 2005,
 2017,
 2007,
 2013,
 2017,
 2016,
 2017,
 2018,
 2016,
 2011,
 2007,
 2008,
 2005,
 2006,
 2011,
 2010,
 2009,
 2018,
 2014,
 2013,
 2017,
 1999,
 2012,
 2012,
 2016,
 2018,
 2014,
 2014,
 2014,
 2015,
 2018,
 2017,
 2011,
 2010,
 2012,
 2016,
 2012,
 2010,
 2015,
 2018,
 2013,
 2000,
 2019,
 2007,
 2016,
 2012,
 2019,
 2017,
 2009,
 2014,
 2016,
 2015,
 2007,
 2015,
 2013,
 2020,
 2016,
 2010,
 2016,
 2017,
 2013,
 2012,
 2018,
 2012,
 2019,
 2013,
 2010,
 2019,
 2008,
 2015,
 2013,
 2011,
 2010,
 2012,
 2015,
 2013,
 2017,
 2015,
 2012,
 2010,
 2011,
 2017,
 2011,
 2019,
 2019,
 2016,
 2004,
 2011,
 2020,
 2015,
 2003,
 2013,
 2010,
 2012,
 2005,
 2012,
 2008,
 2006,
 2010,
 2006,
 2017,
 2013,
 2008,
 2014,
 2015,
 2020,
 2012,
 2007,
 2018,
 2016,
 2017,
 2020,
 2007,
 2020,
 2005,
 2009,
 2019,
 2010,
 2012,
 2014,
 2019,
 2007,
 2013,
 2015,
 2014,
 2011,
 2010,
 2012,
 2014,
 2010,
 2007,
 2012,
 2004,
 2019,
 2017,
 2007,
 2019,
 2005,
 2020,
 2004,
 2015,
 2011,
 2014,
 2015,
 2013,
 2016,
 2011,
 2018,
 2014,
 2011,
 2008,
 1985,
 2013,
 2002,
 2015,
 2009,
 2014,
 2012,
 2020,
 2014,
 2021,
 2018,
 2013,
 2011,
 2018,
 2013,
 2016,
 2017,
 2012,
 2016,
 2010,
 2013,
 2016,
 2020,
 2019,
 2014,
 2011,
 2013,
 2016,
 2015,
 2014,
 2012,
 2013,
 2015,
 2018,
 2015,
 2015,
 2016,
 2008,
 2018,
 2008,
 2016,
 2011,
 2016,
 2013,
 2012,
 2014,
 2015,
 2017,
 2021,
 2015,
 2009,
 2021,
 2015,
 2016,
 2012,
 2010,
 2020,
 2019,
 2012,
 2013,
 2014,
 2018,
 2020,
 2008,
 2013,
 2012,
 2012,
 2013,
 2013,
 2010,
 2017,
 2019,
 2012,
 2017,
 2012,
 2010,
 2008,
 2017,
 2019,
 2012,
 2015,
 2017,
 2006,
 2010,
 2012,
 2008,
 2011,
 2012,
 2012,
 2018,
 2011,
 2010,
 2019,
 2012,
 2011,
 2016,
 2020,
 2013,
 2010,
 2017,
 2011,
 2018,
 2012,
 2017,
 2013,
 2012,
 2016,
 2012,
 2016,
 2014,
 2011,
 2010,
 2007,
 2012,
 2010,
 2009,
 2010,
 2020,
 2013,
 2007,
 2011,
 2011,
 2010,
 2011,
 2014,
 2009,
 2012,
 2011,
 2017,
 2017,
 2015,
 2013,
 2017,
 2016,
 2017,
 2006,
 2019,
 2009,
 2008,
 2009,
 2008,
 2018,
 2020,
 2018,
 2009,
 2016,
 2005,
 2013,
 2016,
 2015,
 2016,
 2015,
 2019,
 2012,
 2018,
 2018,
 2011,
 2018,
 2013,
 2019,
 2005,
 2008,
 2012,
 2018,
 2011,
 2017,
 2010,
 2009,
 2012,
 2011,
 2014,
 2013,
 2008,
 2004,
 2009,
 2016,
 2015,
 2018,
 2015,
 2009,
 2013,
 2009,
 2008,
 2015,
 2013,
 2012,
 2018,
 2015,
 2012,
 2011,
 2017,
 2006,
 2012,
 2014,
 2016,
 2007,
 2016,
 2020,
 2015,
 2014,
 2016,
 2018,
 2008,
 2017,
 1997,
 2016,
 2018,
 2012,
 2012,
 2014,
 2015,
 2012,
 2017,
 2008,
 2008,
 2013,
 2006,
 2008,
 2005,
 2012,
 2009,
 2009,
 2012,
 2019,
 2006,
 2013,
 2015,
 2020,
 2012,
 2016,
 2000,
 2010,
 2019,
 2007,
 2019,
 2014,
 2000,
 2014,
 2017,
 2019,
 2021,
 2012,
 2000,
 2013,
 2013,
 2016,
 2016,
 2020,
 2014,
 2019,
 2018,
 2018,
 2017,
 2018,
 2013,
 2010,
 2011,
 2017,
 2021,
 2019,
 2015,
 2017,
 2018,
 2018,
 2017,
 2012,
 2014,
 2018,
 2008,
 2012,
 2012,
 2013,
 2013,
 2012,
 2019,
 2019,
 2017,
 2012,
 2006,
 2017,
 2012,
 2015,
 2004,
 2015,
 2008,
 2019,
 2007,
 2017,
 2012,
 2015,
 2013,
 2018,
 2014,
 2015,
 2018,
 2013,
 2020,
 2017,
 2016,
 2018,
 2012,
 2018,
 2008,
 2017,
 2015,
 2013,
 2015,
 2015,
 2014,
 2015,
 2012,
 2017,
 2012,
 2017,
 2018,
 2005,
 2020,
 2008,
 2012,
 2016,
 2016,
 2009,
 2004,
 2010,
 2018,
 2018,
 2010,
 2003,
 2011,
 2020,
 2016,
 2015,
 2013,
 2015,
 2013,
 2012,
 2015,
 2016,
 2017,
 2018,
 2017,
 2018,
 2012,
 2007,
 2019,
 2016,
 2016,
 2017,
 2007,
 2015,
 2014,
 2011,
 2008,
 2007,
 2013,
 2018,
 2015,
 2015,
 2012,
 2013,
 2012,
 2016,
 2016,
 2009,
 2018,
 2007,
 2016,
 2010,
 2019,
 2017,
 2012,
 2015,
 2011,
 2005,
 2005,
 2013,
 2012,
 2012,
 2013,
 2009,
 2014,
 2007,
 2016,
 2009,
 2012,
 2008,
 2006,
 2010,
 2009,
 2007,
 2008,
 2015,
 2019,
 2013,
 2009,
 2017,
 2010,
 2010,
 2019,
 2007,
 2013,
 2017,
 2014,
 2016,
 2014,
 2012,
 2018,
 2018,
 2015,
 2016,
 2015,
 2012,
 2009,
 2020,
 2016,
 2018,
 2017,
 2014,
 2014,
 2017,
 2005,
 2017,
 2016,
 2019,
 2012,
 2011,
 2018,
 2014,
 2014,
 2021,
 2010,
 2015,
 2006,
 2017,
 2017,
 2008,
 2010,
 2008,
 2018,
 2016,
 2015,
 2013,
 2012,
 2014,
 2013,
 2011,
 2006,
 2014,
 2012,
 2017,
 2011,
 2014,
 2021,
 1997,
 2010,
 2018,
 2013,
 2016,
 2007,
 2015,
 2012,
 2016,
 2012,
 2014,
 2012,
 2014,
 2018,
 2016,
 2018,
 2016,
 2007,
 2017,
 2017,
 2009,
 2016,
 2018,
 2013,
 2017,
 2011,
 2014,
 2010,
 2009,
 2018,
 2014,
 2009,
 2014,
 2008,
 2013,
 2019,
 2021,
 2018,
 2015,
 2018,
 2013,
 2021,
 2012,
 2011,
 2018,
 2017,
 2011,
 2001,
 2016,
 2013,
 2012,
 2011,
 2001,
 2009,
 2008,
 1997,
 2007,
 2017,
 2013,
 2009,
 2016,
 2013,
 2019,
 2013,
 2003,
 2017,
 2008,
 2018,
 2010,
 2014,
 2014,
 2019,
 2017,
 2019,
 2010,
 1983,
 2015,
 2018,
 2015,
 2012,
 2013,
 2015,
 2010,
 2021,
 2009,
 2016,
 2012,
 2016,
 2009,
 2015,
 2018,
 2018,
 2013,
 2019,
 2019,
 2014,
 2006,
 2016,
 2008,
 2021,
 2012,
 2017,
 2002,
 2014,
 2016,
 2021,
 2017,
 2019,
 2007,
 2018,
 '2010.0 ',
 '2011 ',
 '2018 ',
 '2020 ',
 '2018 ',
 '2018 ',
 '2015 ',
 '2016 ',
 '2010 ',
 '2011 ',
 '2004 ',
 '2009 ',
 '2015 ',
 '2013 ',
 '2013 ',
 '2016 ',
 '2007 ',
 '2013 ',
 '2013 ',
 '2018 ',
 '2015 ',
 '2012 ',
 '2016 ',
 '2010 ',
 '2017 ',
 '2017 ',
 '2012 ',
 '2012 ',
 '2008 ',
 '2019 ',
 '2013 ',
 '2007 ',
 '2013 ',
 '2018 ',
 '2010 ',
 '2017 ',
 '2012 ',
 '1900 ',
 '2020 ',
 '2015 ',
 '2011 ',
 '2008 ',
 '2015 ',
 '2018 ',
 '2010 ',
 '2014 ',
 '2018 ',
 '2019 ',
 '2013 ',
 '2019 ',
 '2015 ',
 '2013 ',
 '2018 ',
 '2016 ',
 '2016 ',
 '2014 ',
 '2019 ',
 '2014 ',
 '2019 ',
 '2012 ',
 '2013 ',
 '2008 ',
 '2018 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2015 ',
 '2016 ',
 '2014 ',
 '2014 ',
 '2009 ',
 '2012 ',
 '2018 ',
 '2013 ',
 '2019 ',
 '2018 ',
 '2011 ',
 '2012 ',
 '2011 ',
 '2018 ',
 '2017 ',
 '2015 ',
 '2013 ',
 '2011 ',
 '2011 ',
 '2016 ',
 '2014 ',
 '2013 ',
 '2015 ',
 '2009 ',
 '2017 ',
 '2016 ',
 '2014 ',
 '2016 ',
 '2011 ',
 '2017 ',
 '2000 ',
 '2005 ',
 '2012 ',
 '2014 ',
 '2013 ',
 '2007 ',
 '2011 ',
 '2015 ',
 '2011 ',
 '2018 ',
 '2017 ',
 '2015 ',
 '2019 ',
 '2018 ',
 '2021 ',
 '2019 ',
 '2015 ',
 '2011 ',
 '2011 ',
 '2015 ',
 '2018 ',
 '2019 ',
 '2015 ',
 '2008 ',
 '2007 ',
 '2013 ',
 '2014 ',
 '2020 ',
 '2016 ',
 '2014 ',
 '2009 ',
 '2012 ',
 '2017 ',
 '2013 ',
 '2015 ',
 '2015 ',
 '2012 ',
 '2006 ',
 '2016 ',
 '2013 ',
 '2018 ',
 '2020 ',
 '2014 ',
 '2020 ',
 '2017 ',
 '2016 ',
 '2012 ',
 '2011 ',
 '2016 ',
 '1998 ',
 '2021 ',
 '2018 ',
 '2014 ',
 '2017 ',
 '2019 ',
 '2008 ',
 '2011 ',
 '2017 ',
 '2018 ',
 '2009 ',
 '2018 ',
 '2017 ',
 '2018 ',
 '2015 ',
 '2017 ',
 '2011 ',
 '2008 ',
 '2016 ',
 '2013 ',
 '2012 ',
 '2008 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2018 ',
 '2010 ',
 '2014 ',
 '2012 ',
 '2012 ',
 '2008 ',
 '2016 ',
 '2011 ',
 '2006 ',
 '2018 ',
 '2017 ',
 '2010 ',
 '2011 ',
 '2011 ',
 '2012 ',
 '2012 ',
 '2011 ',
 '1963 ',
 '2017 ',
 '2016 ',
 '2019 ',
 '2015 ',
 '2014 ',
 '2014 ',
 '2018 ',
 '2010 ',
 '2011 ',
 '1999 ',
 '2012 ',
 '2013 ',
 '2007 ',
 '2011 ',
 '2018 ',
 '2000 ',
 '2018 ',
 '2011 ',
 '2010 ',
 '2017 ',
 '2010 ',
 '2021 ',
 '2011 ',
 '2013 ',
 '2013 ',
 '2018 ',
 '2017 ',
 '2004 ',
 '2012 ',
 '2005 ',
 '2014 ',
 '2020 ',
 '2019 ']

In [83]:
#Fetching data from olx for Km used, Company, Location, Date of posting

for k2 in driver2.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Km_2.append(k2.text.split('-')[1])
for c2 in driver2.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[2]"):
    Company_2.append(c2.text)
for l2 in driver2.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]"):
    Location_2.append(l2.text)
for d2 in driver2.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]/span"):
    Date_2.append(d2.text)

In [84]:
#Making a dataframe named Cars storing 500 data into that

CARS2=pd.DataFrame({})
CARS2['PRICE']=Price_2[0:500]
CARS2['YEAR']=Year_2[0:500]
CARS2['KM']=Km_2[0:500]
CARS2['COMPANY']=Company_2[0:500]
CARS2['LOCATION']=Location_2[0:500]
CARS2['POSTED-DATE']=Date_2[0:500]

In [85]:
#Printing the datframe that we have just made

CARS2

,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE
0,NaN,2013,"40,000 km",Hyundai Verna,Narila Shankari Chatrashal Nagar\nYesterday,Yesterday
1,NaN,2019,"39,000 km",Maruti Suzuki Swift Dzire,Bhawarkua\n4 days ago,4 days ago
2,NaN,2014,"58,990 km",Hyundai Grand i10,Piplani\nDec 27,Dec 27
3,NaN,2007,"59,000 km",Maruti Suzuki Alto,Maa Vidhar Colony\nToday,Today
4,NaN,2018,"65,000 km",Maruti Suzuki Ertiga,Cheevani Phlamad Nagar\nToday,Today
...,...,...,...,...,...,...
495,NaN,2015,"49,300 km",Skoda Rapid,Bhawarkua\n2 days ago,2 days ago
496,NaN,2014,"55,552 km",Maruti Suzuki Swift,Talawali Chanda\n2 days ago,2 days ago
497,NaN,2015,"43,000 km",Maruti Suzuki Alto 800,Talawali Chanda\n2 days ago,2 days ago
498,NaN,2012,"58,000 km",Maruti Suzuki Swift,Master Ali Mohd\n2 days ago,2 days ago
499,NaN,2017,"65,000 km",Hyundai Grand i10,Noor Sabah\n2 days ago,2 days ago

In [86]:
#Getting the information for the CARS2 Dataset

CARS2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRICE        0 non-null      float64
 1   YEAR         500 non-null    int64
 2   KM           500 non-null    object
 3   COMPANY      500 non-null    object
 4   LOCATION     500 non-null    object
 5   POSTED-DATE  500 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 23.6+ KB

In [87]:
#Closing the driver

driver2.close()

# NOW WE HAVE COLLECTED 1000 DATA

In [88]:
#Creating an instance of the chrome driver to get to the url

driver3 = webdriver.Chrome(r'E:/CHROME-DRIVER/chromedriver_win32/chromedriver.exe')

In [90]:
#Getting into the website

driver3.get('https://www.olx.in/en-in/maharashtra_g2001163/cars_c84')

In [91]:
#Creating empty lists so that we can fetch the data

Price_3=[]
Year_3=[]
Km_3=[]
Company_3=[]
Location_3=[]
Date_3=[]

In [94]:
#Fetching the data from olx for Price

for p3 in driver3.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/span"):
    Price_3.append(p3.text.replace("â‚¹","").replace(",",""))

In [95]:
#Printing the price

Price_3

[' 575000',
 ' 125000',
 ' 1050000',
 ' 150000',
 ' 550000',
 ' 350000',
 ' 279000',
 ' 155000',
 ' 575000',
 ' 545000',
 ' 545000',
 ' 774000',
 ' 1750000',
 ' 1375000',
 ' 90000',
 ' 1375000',
 ' 395000',
 ' 450000',
 ' 1285000',
 ' 155000',
 ' 1399000',
 ' 925000',
 ' 1851000',
 ' 275000',
 ' 170000',
 ' 495000',
 ' 1829000',
 ' 275000',
 ' 145000',
 ' 515000',
 ' 290000',
 ' 246000',
 ' 274000',
 ' 235000',
 ' 2875000',
 ' 495000',
 ' 335000',
 ' 525000',
 ' 695000',
 ' 485000',
 ' 211000',
 ' 575000',
 ' 241000',
 ' 390000',
 ' 310000',
 ' 635000',
 ' 725000',
 ' 425000',
 ' 415000',
 ' 260000',
 ' 540000',
 ' 210000',
 ' 210000',
 ' 1350000',
 ' 490000',
 ' 200000',
 ' 300000',
 ' 235000',
 ' 75000',
 ' 260000',
 ' 1295000',
 ' 850000',
 ' 1400000',
 ' 140000',
 ' 100000',
 ' 215000',
 ' 389999',
 ' 1590000',
 ' 1405000',
 ' 271000',
 ' 135000',
 ' 360000',
 ' 611000',
 ' 225000',
 ' 365000',
 ' 421000',
 ' 950000',
 ' 90000',
 ' 245000',
 ' 225000',
 ' 455000',
 ' 310000',
 ' 799999',
 ' 210000',
 ' 200000',
 ' 236000',
 ' 675000',
 ' 785000',
 ' 120000',
 ' 450000',
 ' 250000',
 ' 179000',
 ' 550000',
 ' 1045000',
 ' 170000',
 ' 4500000',
 ' 2600000',
 ' 225000',
 ' 540000',
 ' 425000',
 ' 155000',
 ' 365000',
 ' 675000',
 ' 42000',
 ' 130000',
 ' 115000',
 ' 300000',
 ' 225000',
 ' 240000',
 ' 395000',
 ' 285000',
 ' 250000',
 ' 58000',
 ' 300000',
 ' 600000',
 ' 285000',
 ' 375000',
 ' 599000',
 ' 365000',
 ' 349000',
 ' 825000',
 ' 260000',
 ' 945000',
 ' 135000',
 ' 150000',
 ' 51000',
 ' 334000',
 ' 120000',
 ' 750000',
 ' 485000',
 ' 425000',
 ' 335000',
 ' 235000',
 ' 1498000',
 ' 1151000',
 ' 2400000',
 ' 1151000',
 ' 751000',
 ' 575000',
 ' 425000',
 ' 2149000',
 ' 4351000',
 ' 2050000',
 ' 70000',
 ' 70000',
 ' 721000',
 ' 386000',
 ' 1250000',
 ' 795000',
 ' 1541000',
 ' 455000',
 ' 399000',
 ' 595000',
 ' 125000',
 ' 1150000',
 ' 775000',
 ' 851000',
 ' 1330000',
 ' 625000',
 ' 710000',
 ' 2725000',
 ' 449000',
 ' 351000',
 ' 220000',
 ' 185000',
 ' 450000',
 ' 325000',
 ' 300000',
 ' 815000',
 ' 475000',
 ' 890000',
 ' 810000',
 ' 285000',
 ' 325000',
 ' 590000',
 ' 695000',
 ' 675000',
 ' 225000',
 ' 690000',
 ' 315000',
 ' 611000',
 ' 449000',
 ' 491000',
 ' 230000',
 ' 170000',
 ' 225000',
 ' 120000',
 ' 390000',
 ' 285000',
 ' 386500',
 ' 375000',
 ' 1695000',
 ' 375000',
 ' 395000',
 ' 270000',
 ' 690000',
 ' 145000',
 ' 620000',
 ' 360000',
 ' 610000',
 ' 525000',
 ' 835000',
 ' 650000',
 ' 100000',
 ' 270000',
 ' 265000',
 ' 599000',
 ' 295000',
 ' 5175000',
 ' 845000',
 ' 385000',
 ' 385000',
 ' 485000',
 ' 235000',
 ' 625000',
 ' 1025000',
 ' 150000',
 ' 510000',
 ' 165000',
 ' 850000',
 ' 750000',
 ' 750000',
 ' 490000',
 ' 750000',
 ' 145000',
 ' 325000',
 ' 35000',
 ' 350000',
 ' 419000',
 ' 690000',
 ' 995000',
 ' 525000',
 ' 355000',
 ' 190000',
 ' 250000',
 ' 30000',
 ' 1000000',
 ' 245000',
 ' 2700000',
 ' 230000',
 ' 545000',
 ' 2200000',
 ' 298000',
 ' 300000',
 ' 190000',
 ' 510000',
 ' 160000',
 ' 248000',
 ' 1450000',
 ' 645000',
 ' 625000',
 ' 495000',
 ' 370000',
 ' 260000',
 ' 249000',
 ' 244000',
 ' 28500',
 ' 210000',
 ' 475000',
 ' 145000',
 ' 365000',
 ' 855000',
 ' 790000',
 ' 399000',
 ' 170000',
 ' 239000',
 ' 279000',
 ' 1425000',
 ' 320000',
 ' 325000',
 ' 260000',
 ' 575000',
 ' 260000',
 ' 100000',
 ' 324999',
 ' 325000',
 ' 575000',
 ' 425000',
 ' 575000',
 ' 480000',
 ' 495000',
 ' 435000',
 ' 260000',
 ' 195000',
 ' 99000',
 ' 370000',
 ' 290000',
 ' 200000',
 ' 200000',
 ' 200000',
 ' 865000',
 ' 1200000',
 ' 360000',
 ' 375000',
 ' 475000',
 ' 875000',
 ' 260000',
 ' 325000',
 ' 150000',
 ' 421000',
 ' 3600000',
 ' 1149000',
 ' 355000',
 ' 220000',
 ' 1050000',
 ' 290000',
 ' 395000',
 ' 275000',
 ' 275000',
 ' 565000',
 ' 415000',
 ' 645000',
 ' 590000',
 ' 995000',
 ' 690000',
 ' 1500000',
 ' 150000',
 ' 250000',
 ' 690000',
 ' 179000',
 ' 225000',
 ' 950000',
 ' 1051000',
 ' 1600000',
 ' 350000',
 ' 425000',
 ' 600000',
 ' 1825000',
 ' 1585000',
 ' 635000',
 ' 775000',
 ' 230000',
 ' 1745000',
 ' 1345000',
 ' 295000',
 ' 350000',
 ' 365000',
 ' 1325000',
 ' 325000',
 ' 875000',
 ' 995000',
 ' 691000',
 ' 175000',
 ' 285000',
 ' 295000',
 ' 155000',
 ' 145000',
 ' 60000',
 ' 650000',
 ' 85000',
 ' 249999',
 ' 230000',
 ' 250000',
 ' 61000',
 ' 570000',
 ' 750000',
 ' 540000',
 ' 2175111',
 ' 1070000',
 ' 2220000',
 ' 165000',
 ' 4800000',
 ' 479999',
 ' 170000',
 ' 750000',
 ' 400000',
 ' 2175111',
 ' 140000',
 ' 2175111',
 ' 190000',
 ' 135000',
 ' 275000',
 ' 210000',
 ' 575000',
 ' 700000',
 ' 1050000',
 ' 440000',
 ' 140000',
 ' 575000',
 ' 175000',
 ' 341000',
 ' 211000',
 ' 185000',
 ' 265555',
 ' 400000',
 ' 190000',
 ' 280000',
 ' 365000',
 ' 289000',
 ' 100000',
 ' 349000',
 ' 599000',
 ' 399000',
 ' 189000',
 ' 379000',
 ' 699000',
 ' 849000',
 ' 711000',
 ' 875000',
 ' 190000',
 ' 365000',
 ' 595000',
 ' 385000',
 ' 285000',
 ' 445000',
 ' 421000',
 ' 365000',
 ' 599999',
 ' 999999',
 ' 411000',
 ' 749000',
 ' 1125000',
 ' 1590000',
 ' 235000',
 ' 535000',
 ' 445000',
 ' 675000',
 ' 211000',
 ' 1295000',
 ' 175000',
 ' 1849999',
 ' 450000',
 ' 1695000',
 ' 120000',
 ' 110000',
 ' 725000',
 ' 360000',
 ' 849999',
 ' 15000',
 ' 325000',
 ' 180000',
 ' 325000',
 ' 2175000',
 ' 235000',
 ' 235000',
 ' 190000',
 ' 825000',
 ' 635000',
 ' 1800000',
 ' 225000',
 ' 335000',
 ' 325000',
 ' 485000',
 ' 380000',
 ' 699000',
 ' 1045000',
 ' 1095000',
 ' 199000',
 ' 1095001',
 ' 1925000',
 ' 479000',
 ' 1275000',
 ' 1499000',
 ' 450000',
 ' 769000',
 ' 228000',
 ' 299000',
 ' 999999',
 ' 845000',
 ' 745000',
 ' 620000',
 ' 650000',
 ' 680000',
 ' 155000',
 ' 300000',
 ' 450000',
 ' 451111',
 ' 125000',
 ' 275000',
 ' 490000',
 ' 81000',
 ' 690000',
 ' 180000',
 ' 90000',
 ' 451111',
 ' 240000',
 ' 900005',
 ' 451111',
 ' 399000',
 ' 249000',
 ' 290000',
 ' 450000',
 ' 1050000',
 ' 350000',
 ' 90000',
 ' 490000',
 ' 99000',
 ' 675000',
 ' 135000',
 ' 699000',
 ' 589000',
 ' 499000',
 ' 189000',
 ' 279000',
 ' 289000',
 ' 249000',
 ' 399000',
 ' 1299000']

In [96]:
#Converting the column into integer type

for i in range(0, len(Price_3)):
    Price_3[i] = int(Price_3[i])

In [97]:
#Printing aftewr conversion

Price_3

[575000,
 125000,
 1050000,
 150000,
 550000,
 350000,
 279000,
 155000,
 575000,
 545000,
 545000,
 774000,
 1750000,
 1375000,
 90000,
 1375000,
 395000,
 450000,
 1285000,
 155000,
 1399000,
 925000,
 1851000,
 275000,
 170000,
 495000,
 1829000,
 275000,
 145000,
 515000,
 290000,
 246000,
 274000,
 235000,
 2875000,
 495000,
 335000,
 525000,
 695000,
 485000,
 211000,
 575000,
 241000,
 390000,
 310000,
 635000,
 725000,
 425000,
 415000,
 260000,
 540000,
 210000,
 210000,
 1350000,
 490000,
 200000,
 300000,
 235000,
 75000,
 260000,
 1295000,
 850000,
 1400000,
 140000,
 100000,
 215000,
 389999,
 1590000,
 1405000,
 271000,
 135000,
 360000,
 611000,
 225000,
 365000,
 421000,
 950000,
 90000,
 245000,
 225000,
 455000,
 310000,
 799999,
 210000,
 200000,
 236000,
 675000,
 785000,
 120000,
 450000,
 250000,
 179000,
 550000,
 1045000,
 170000,
 4500000,
 2600000,
 225000,
 540000,
 425000,
 155000,
 365000,
 675000,
 42000,
 130000,
 115000,
 300000,
 225000,
 240000,
 395000,
 285000,
 250000,
 58000,
 300000,
 600000,
 285000,
 375000,
 599000,
 365000,
 349000,
 825000,
 260000,
 945000,
 135000,
 150000,
 51000,
 334000,
 120000,
 750000,
 485000,
 425000,
 335000,
 235000,
 1498000,
 1151000,
 2400000,
 1151000,
 751000,
 575000,
 425000,
 2149000,
 4351000,
 2050000,
 70000,
 70000,
 721000,
 386000,
 1250000,
 795000,
 1541000,
 455000,
 399000,
 595000,
 125000,
 1150000,
 775000,
 851000,
 1330000,
 625000,
 710000,
 2725000,
 449000,
 351000,
 220000,
 185000,
 450000,
 325000,
 300000,
 815000,
 475000,
 890000,
 810000,
 285000,
 325000,
 590000,
 695000,
 675000,
 225000,
 690000,
 315000,
 611000,
 449000,
 491000,
 230000,
 170000,
 225000,
 120000,
 390000,
 285000,
 386500,
 375000,
 1695000,
 375000,
 395000,
 270000,
 690000,
 145000,
 620000,
 360000,
 610000,
 525000,
 835000,
 650000,
 100000,
 270000,
 265000,
 599000,
 295000,
 5175000,
 845000,
 385000,
 385000,
 485000,
 235000,
 625000,
 1025000,
 150000,
 510000,
 165000,
 850000,
 750000,
 750000,
 490000,
 750000,
 145000,
 325000,
 35000,
 350000,
 419000,
 690000,
 995000,
 525000,
 355000,
 190000,
 250000,
 30000,
 1000000,
 245000,
 2700000,
 230000,
 545000,
 2200000,
 298000,
 300000,
 190000,
 510000,
 160000,
 248000,
 1450000,
 645000,
 625000,
 495000,
 370000,
 260000,
 249000,
 244000,
 28500,
 210000,
 475000,
 145000,
 365000,
 855000,
 790000,
 399000,
 170000,
 239000,
 279000,
 1425000,
 320000,
 325000,
 260000,
 575000,
 260000,
 100000,
 324999,
 325000,
 575000,
 425000,
 575000,
 480000,
 495000,
 435000,
 260000,
 195000,
 99000,
 370000,
 290000,
 200000,
 200000,
 200000,
 865000,
 1200000,
 360000,
 375000,
 475000,
 875000,
 260000,
 325000,
 150000,
 421000,
 3600000,
 1149000,
 355000,
 220000,
 1050000,
 290000,
 395000,
 275000,
 275000,
 565000,
 415000,
 645000,
 590000,
 995000,
 690000,
 1500000,
 150000,
 250000,
 690000,
 179000,
 225000,
 950000,
 1051000,
 1600000,
 350000,
 425000,
 600000,
 1825000,
 1585000,
 635000,
 775000,
 230000,
 1745000,
 1345000,
 295000,
 350000,
 365000,
 1325000,
 325000,
 875000,
 995000,
 691000,
 175000,
 285000,
 295000,
 155000,
 145000,
 60000,
 650000,
 85000,
 249999,
 230000,
 250000,
 61000,
 570000,
 750000,
 540000,
 2175111,
 1070000,
 2220000,
 165000,
 4800000,
 479999,
 170000,
 750000,
 400000,
 2175111,
 140000,
 2175111,
 190000,
 135000,
 275000,
 210000,
 575000,
 700000,
 1050000,
 440000,
 140000,
 575000,
 175000,
 341000,
 211000,
 185000,
 265555,
 400000,
 190000,
 280000,
 365000,
 289000,
 100000,
 349000,
 599000,
 399000,
 189000,
 379000,
 699000,
 849000,
 711000,
 875000,
 190000,
 365000,
 595000,
 385000,
 285000,
 445000,
 421000,
 365000,
 599999,
 999999,
 411000,
 749000,
 1125000,
 1590000,
 235000,
 535000,
 445000,
 675000,
 211000,
 1295000,
 175000,
 1849999,
 450000,
 1695000,
 120000,
 110000,
 725000,
 360000,
 849999,
 15000,
 325000,
 180000,
 325000,
 2175000,
 235000,
 235000,
 190000,
 825000,
 635000,
 1800000,
 225000,
 335000,
 325000,
 485000,
 380000,
 699000,
 1045000,
 1095000,
 199000,
 1095001,
 1925000,
 479000,
 1275000,
 1499000,
 450000,
 769000,
 228000,
 299000,
 999999,
 845000,
 745000,
 620000,
 650000,
 680000,
 155000,
 300000,
 450000,
 451111,
 125000,
 275000,
 490000,
 81000,
 690000,
 180000,
 90000,
 451111,
 240000,
 900005,
 451111,
 399000,
 249000,
 290000,
 450000,
 1050000,
 350000,
 90000,
 490000,
 99000,
 675000,
 135000,
 699000,
 589000,
 499000,
 189000,
 279000,
 289000,
 249000,
 399000,
 1299000]

In [99]:
#Fetching data from olx for Year

for y3 in driver3.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Year_3.append(y3.text.split('-')[0])

In [100]:
#Converting the column into integer type

for i in range(0, len(Year_3)):
    Year_3[i] = int(Year_3[i])

In [101]:
#Printing after conversion

Year_3

[2014,
 2007,
 2015,
 2016,
 2018,
 2018,
 2014,
 2008,
 2014,
 2015,
 2012,
 2011,
 2014,
 2013,
 2021,
 2013,
 2013,
 2013,
 2012,
 2009,
 2018,
 2018,
 2013,
 2017,
 2016,
 2017,
 2019,
 2013,
 2011,
 2014,
 2014,
 2012,
 2010,
 2011,
 2016,
 2017,
 2016,
 2014,
 2016,
 2018,
 2011,
 2010,
 2011,
 2018,
 2012,
 2018,
 2016,
 2010,
 2016,
 2010,
 2014,
 2010,
 2009,
 2017,
 2013,
 2021,
 2021,
 2009,
 2015,
 2009,
 2016,
 2013,
 2019,
 2015,
 2011,
 2010,
 2015,
 2014,
 2018,
 2010,
 2008,
 2010,
 2016,
 2008,
 2011,
 2012,
 2015,
 2005,
 2010,
 2011,
 2016,
 2010,
 2014,
 2009,
 2009,
 2010,
 2018,
 2017,
 2015,
 2012,
 2012,
 2010,
 2019,
 2010,
 2008,
 2017,
 2017,
 2012,
 2016,
 2015,
 2007,
 2013,
 2015,
 2010,
 2006,
 2008,
 2013,
 2011,
 2011,
 2013,
 2011,
 2012,
 2021,
 2013,
 2018,
 2011,
 2012,
 2021,
 2014,
 2013,
 2017,
 2011,
 2016,
 2008,
 2007,
 2021,
 2013,
 2009,
 2018,
 2017,
 2016,
 2013,
 2011,
 2018,
 2011,
 2017,
 2011,
 2010,
 2014,
 2011,
 2021,
 2018,
 2019,
 2004,
 2010,
 2014,
 2016,
 2013,
 2016,
 2021,
 2016,
 2016,
 2016,
 2009,
 2019,
 2016,
 2015,
 2012,
 2015,
 2019,
 2016,
 2013,
 2011,
 2007,
 2008,
 2012,
 2016,
 2012,
 2019,
 2013,
 2018,
 2016,
 2010,
 2012,
 2014,
 2018,
 2018,
 2013,
 2016,
 2011,
 2016,
 2013,
 2012,
 2005,
 2016,
 2012,
 2008,
 2014,
 2010,
 2013,
 2013,
 2020,
 2014,
 2011,
 2010,
 2016,
 2009,
 2013,
 2013,
 2013,
 2019,
 2016,
 2017,
 2001,
 2011,
 2010,
 2016,
 2014,
 2018,
 2017,
 2012,
 2012,
 2015,
 2012,
 2014,
 2019,
 2009,
 2017,
 2011,
 2019,
 2018,
 2018,
 2014,
 2013,
 2009,
 2011,
 2007,
 2018,
 2013,
 2017,
 2016,
 2016,
 2016,
 2012,
 2012,
 2010,
 2020,
 2008,
 2014,
 2010,
 2016,
 2021,
 2010,
 2009,
 2013,
 2014,
 2007,
 2013,
 2016,
 2016,
 2016,
 2012,
 2013,
 2010,
 2014,
 2010,
 2008,
 2009,
 2015,
 2002,
 2016,
 2011,
 2019,
 2014,
 2016,
 2014,
 2011,
 2018,
 2011,
 2012,
 2010,
 2014,
 2010,
 2021,
 2011,
 2011,
 2013,
 2011,
 2016,
 2017,
 2015,
 2016,
 2011,
 2011,
 2007,
 2011,
 2011,
 2021,
 2021,
 2021,
 2019,
 2011,
 2015,
 2016,
 2018,
 2014,
 2010,
 2011,
 2008,
 2015,
 2016,
 2020,
 2012,
 2009,
 2015,
 2010,
 2011,
 2009,
 2011,
 2015,
 2015,
 2021,
 2012,
 2018,
 2013,
 2016,
 2011,
 2011,
 2013,
 2009,
 2001,
 2018,
 2011,
 2016,
 2018,
 2012,
 2017,
 2019,
 2019,
 2020,
 2017,
 2010,
 2017,
 2018,
 2010,
 2015,
 2013,
 2018,
 2013,
 2017,
 2019,
 2012,
 2006,
 2012,
 2012,
 2009,
 2009,
 2008,
 2015,
 2006,
 2013,
 2008,
 2012,
 2007,
 2019,
 2017,
 2015,
 2019,
 2016,
 2021,
 2009,
 2021,
 2013,
 2009,
 2012,
 2013,
 2019,
 2010,
 2019,
 2011,
 2009,
 2010,
 2009,
 2014,
 2017,
 2019,
 2017,
 2008,
 2015,
 2008,
 2012,
 2012,
 2009,
 2010,
 2019,
 2010,
 2016,
 2014,
 2012,
 2006,
 2016,
 2013,
 2013,
 2009,
 2014,
 2016,
 2015,
 2017,
 2017,
 2011,
 2013,
 2013,
 2015,
 2017,
 2014,
 2012,
 2013,
 2010,
 2013,
 2014,
 2016,
 2021,
 2017,
 2009,
 2014,
 2013,
 2016,
 2008,
 2012,
 2009,
 2015,
 2015,
 2020,
 2008,
 2007,
 2018,
 2013,
 2018,
 1982,
 2012,
 2010,
 2013,
 2021,
 2010,
 2010,
 2011,
 2011,
 2019,
 2017,
 2010,
 2013,
 2017,
 2017,
 2008,
 2016,
 2018,
 2017,
 2007,
 2019,
 2012,
 2014,
 2019,
 2013,
 2018,
 2017,
 2011,
 2008,
 2010,
 2018,
 2017,
 2016,
 2014,
 2016,
 2013,
 2011,
 2013,
 2013,
 2007,
 2011,
 2014,
 2005,
 2016,
 2011,
 2007,
 2013,
 2013,
 2019,
 2013,
 2014,
 2010,
 2014,
 2017,
 2020,
 2012,
 2007,
 2015,
 2006,
 2015,
 2006,
 2017,
 2016,
 2013,
 2010,
 2012,
 2015,
 2014,
 2014,
 2019]

In [103]:
#Fetching data from olx for Km used, Company, Location, Date of posting

for k3 in driver3.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Km_3.append(k3.text.split('-')[1])
for c3 in driver3.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[2]"):
    Company_3.append(c3.text)
for l3 in driver3.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]"):
    Location_3.append(l3.text)
for d3 in driver3.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]/span"):
    Date_3.append(d3.text)

In [104]:
#Making a dataframe named Cars storing 500 data into that

CARS3=pd.DataFrame({})
CARS3['PRICE']=Price_3[0:500]
CARS3['YEAR']=Year_3[0:500]
CARS3['KM']=Km_3[0:500]
CARS3['COMPANY']=Company_3[0:500]
CARS3['LOCATION']=Location_3[0:500]
CARS3['POSTED-DATE']=Date_3[0:500]

In [105]:
#Printing the dataframe

CARS3

,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE
0,575000,2014,"86,000 km",Renault Duster,Satpur MIDC\nJan 12,Jan 12
1,125000,2007,"55,000 km",Maruti Suzuki Alto,Yewlekar Mala\nDec 17,Dec 17
2,1050000,2015,"65,000 km",Toyota Innova,Dombivli\n2 days ago,2 days ago
3,150000,2016,"70,000 km",Nissan GTR,Naro Nagar\nToday,Today
4,550000,2018,"20,000 km",Mahindra Bolero Pik-Up,Vazira\nToday,Today
...,...,...,...,...,...,...
493,279000,2012,"49,407 km",Hyundai i10,Mulund West\nToday,Today
494,289000,2015,30 km,Renault KWID,Mulund West\nToday,Today
495,249000,2014,"87,986 km",Maruti Suzuki Alto 800,Mulund West\nToday,Today
496,399000,2014,"56,665 km",Hyundai Grand i10,Mulund West\nToday,Today
497,1299000,2019,"35,000 km",Hyundai Creta,Kharghar\nToday,Today

In [106]:
#Getting the information about the dataset

CARS3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRICE        498 non-null    int64
 1   YEAR         498 non-null    int64
 2   KM           498 non-null    object
 3   COMPANY      498 non-null    object
 4   LOCATION     498 non-null    object
 5   POSTED-DATE  498 non-null    object
dtypes: int64(2), object(4)
memory usage: 23.5+ KB

In [107]:
#Closing the driver3

driver3.close()

# 1498 DATA COLLECTED NOW

In [108]:
#Creating an instance of the chrome driver to get to the url

driver4 = webdriver.Chrome(r'E:/CHROME-DRIVER/chromedriver_win32/chromedriver.exe')

In [110]:
#Getting into the website

driver4.get('https://www.olx.in/en-in/gujarat_g2001154/cars_c84?isSearchCall=false')

In [111]:
#Creating empty lists so that we can fetch the data

Price_4=[]
Year_4=[]
Km_4=[]
Company_4=[]
Location_4=[]
Date_4=[]

In [112]:
#Fetching the data from olx for Price

for p4 in driver4.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/span"):
    Price_4.append(p4.text.replace("â‚¹","").replace(",",""))

In [113]:
#Printing the price

Price_4

[' 575000',
 ' 265000',
 ' 215000',
 ' 155000',
 ' 540000',
 ' 168000',
 ' 595000',
 ' 450000',
 ' 440000',
 ' 325000',
 ' 325000',
 ' 1850000',
 ' 745000',
 ' 1575000',
 ' 225000',
 ' 575000',
 ' 251000',
 ' 115000',
 ' 450000',
 ' 3751000',
 ' 825000',
 ' 620000',
 ' 665000',
 ' 950000',
 ' 877000',
 ' 145000',
 ' 1280000',
 ' 950000',
 ' 385000',
 ' 325000',
 ' 125000',
 ' 480000',
 ' 675000',
 ' 210000',
 ' 560000',
 ' 145000',
 ' 265000',
 ' 339000',
 ' 270000',
 ' 195000',
 ' 298000',
 ' 325000',
 ' 235000',
 ' 150000',
 ' 1250000',
 ' 425000',
 ' 280000',
 ' 565000',
 ' 255000',
 ' 125000',
 ' 260000',
 ' 2151000',
 ' 365000',
 ' 225000',
 ' 150000',
 ' 550000',
 ' 650000',
 ' 625000',
 ' 890000',
 ' 155000',
 ' 165000',
 ' 471000',
 ' 290000',
 ' 500000',
 ' 235000',
 ' 291000',
 ' 851000',
 ' 475000',
 ' 475001',
 ' 250000',
 ' 350000',
 ' 681000',
 ' 325000',
 ' 230000',
 ' 275000',
 ' 690000',
 ' 300000',
 ' 790000',
 ' 1300000',
 ' 1650000',
 ' 575000',
 ' 285000',
 ' 3900000',
 ' 111500',
 ' 350000',
 ' 211000',
 ' 145000',
 ' 315000',
 ' 965000',
 ' 141000',
 ' 535000',
 ' 595000',
 ' 451000',
 ' 159000',
 ' 365000',
 ' 380000',
 ' 1350000',
 ' 450000',
 ' 399000',
 ' 275000',
 ' 1431000',
 ' 139000',
 ' 225000',
 ' 480000',
 ' 400000',
 ' 580000',
 ' 849000',
 ' 1090000',
 ' 650000',
 ' 1375000',
 ' 2775000',
 ' 925000',
 ' 125000',
 ' 230000',
 ' 270000',
 ' 125000',
 ' 3450000',
 ' 690000',
 ' 128000',
 ' 725000',
 ' 2000002',
 ' 325000',
 ' 775000',
 ' 155000',
 ' 150000',
 ' 650000',
 ' 625000',
 ' 725000',
 ' 142000',
 ' 185000',
 ' 1451000',
 ' 211000',
 ' 185000',
 ' 465000',
 ' 340000',
 ' 311000',
 ' 751000',
 ' 625000',
 ' 875000',
 ' 260000',
 ' 530000',
 ' 195000',
 ' 1245000',
 ' 355000',
 ' 190000',
 ' 190000',
 ' 270000',
 ' 1750000',
 ' 625000',
 ' 625000',
 ' 270000',
 ' 350000',
 ' 200000',
 ' 211000',
 ' 125000',
 ' 200000',
 ' 351000',
 ' 350000',
 ' 148500',
 ' 690000',
 ' 1290000',
 ' 1950000',
 ' 505000',
 ' 295000',
 ' 725786',
 ' 450000',
 ' 400000',
 ' 550000',
 ' 690000',
 ' 485000',
 ' 680000',
 ' 1135000',
 ' 475000',
 ' 200000',
 ' 675000',
 ' 495000',
 ' 725000',
 ' 1650000',
 ' 820000',
 ' 235000',
 ' 585000',
 ' 735000',
 ' 1390000',
 ' 775000',
 ' 70000',
 ' 161000',
 ' 135000',
 ' 291000',
 ' 225000',
 ' 390000',
 ' 240000',
 ' 360000',
 ' 575000',
 ' 1205000',
 ' 210000',
 ' 675000',
 ' 551000',
 ' 150000',
 ' 95000',
 ' 935000',
 ' 625000',
 ' 750000',
 ' 210000',
 ' 420000',
 ' 280000',
 ' 310000',
 ' 405000',
 ' 440000',
 ' 380000',
 ' 355000',
 ' 475000',
 ' 560000',
 ' 550000',
 ' 570000',
 ' 560000',
 ' 699000',
 ' 450000',
 ' 655000',
 ' 115000',
 ' 1200000',
 ' 260000',
 ' 1700000',
 ' 2200000',
 ' 250000',
 ' 450000',
 ' 780000',
 ' 1199999',
 ' 425000',
 ' 669999',
 ' 142786',
 ' 1500000',
 ' 750000',
 ' 200000',
 ' 1200000',
 ' 580000',
 ' 250000',
 ' 475000',
 ' 460000',
 ' 700000',
 ' 550000',
 ' 590000',
 ' 925000',
 ' 751000',
 ' 521000',
 ' 410000',
 ' 525000',
 ' 625000',
 ' 411000',
 ' 235000',
 ' 575000',
 ' 385000',
 ' 150000',
 ' 1285000',
 ' 195000',
 ' 1800000',
 ' 270000',
 ' 511000',
 ' 390000',
 ' 60000',
 ' 685000',
 ' 235000',
 ' 521000',
 ' 500000',
 ' 431000',
 ' 185000',
 ' 835000',
 ' 540000',
 ' 360000',
 ' 435000',
 ' 511000',
 ' 290000',
 ' 465000',
 ' 545000',
 ' 251000',
 ' 850000',
 ' 461000',
 ' 541000',
 ' 275000',
 ' 311000',
 ' 630000',
 ' 925000',
 ' 375000',
 ' 2875000',
 ' 200000',
 ' 549000',
 ' 560000',
 ' 1375000',
 ' 1375000',
 ' 325000',
 ' 385000',
 ' 411000',
 ' 1625000',
 ' 215000',
 ' 250000',
 ' 595000',
 ' 790000',
 ' 851000',
 ' 580000',
 ' 360000',
 ' 750000',
 ' 611000',
 ' 861000',
 ' 295000',
 ' 200000',
 ' 1500000',
 ' 885000',
 ' 340000',
 ' 470000',
 ' 345000',
 ' 1290000',
 ' 240000',
 ' 640000',
 ' 245000',
 ' 745000',
 ' 875000',
 ' 375000',
 ' 555000',
 ' 321000',
 ' 215000',
 ' 330000',
 ' 285000',
 ' 2600000',
 ' 775000',
 ' 250000',
 ' 1650000',
 ' 1515000',
 ' 560000',
 ' 1975000',
 ' 5800000',
 ' 800000',
 ' 135000',
 ' 75000',
 ' 690000',
 ' 380000',
 ' 460000',
 ' 1250000',
 ' 55000',
 ' 670000',
 ' 425000',
 ' 230000',
 ' 355000',
 ' 1450000',
 ' 350000',
 ' 125000',
 ' 360000',
 ' 690143',
 ' 171000',
 ' 201000',
 ' 340000',
 ' 96000',
 ' 250000',
 ' 525000',
 ' 550000',
 ' 965000',
 ' 575000',
 ' 275000',
 ' 450786',
 ' 300000',
 ' 435143',
 ' 690000',
 ' 675000',
 ' 1161000',
 ' 399999',
 ' 450000',
 ' 85000',
 ' 440000',
 ' 1250000',
 ' 130000',
 ' 580000',
 ' 270000',
 ' 155000',
 ' 150000',
 ' 1250000',
 ' 850000',
 ' 1250000',
 ' 740000',
 ' 70000',
 ' 191000',
 ' 490143',
 ' 265000',
 ' 351000',
 ' 541000',
 ' 3300000',
 ' 120000',
 ' 825000',
 ' 1499000',
 ' 575000',
 ' 3950000',
 ' 3650000',
 ' 1550000',
 ' 250000',
 ' 475000',
 ' 850000',
 ' 2250000',
 ' 750000',
 ' 1250000',
 ' 215000',
 ' 700000',
 ' 120000',
 ' 1450000',
 ' 745000',
 ' 230000',
 ' 451000',
 ' 465000',
 ' 125000',
 ' 445143',
 ' 400000',
 ' 520000',
 ' 300000',
 ' 475000',
 ' 395000',
 ' 635000',
 ' 475000',
 ' 385000',
 ' 1150000',
 ' 3250000',
 ' 775000',
 ' 365000',
 ' 575000',
 ' 350000',
 ' 185000',
 ' 675000',
 ' 110000',
 ' 750000',
 ' 350000',
 ' 690000',
 ' 525000',
 ' 1700000',
 ' 560000',
 ' 875000',
 ' 271000',
 ' 230000',
 ' 355000',
 ' 550000',
 ' 400000',
 ' 450000',
 ' 25000',
 ' 1711000',
 ' 550000',
 ' 850000',
 ' 1875000',
 ' 3285000',
 ' 431000',
 ' 80000',
 ' 130000',
 ' 231000',
 ' 1050000',
 ' 179000',
 ' 575000',
 ' 60000',
 ' 85000',
 ' 155000',
 ' 875000',
 ' 975000',
 ' 140000',
 ' 551000',
 ' 1650000',
 ' 250000',
 ' 635000',
 ' 635000',
 ' 2051000',
 ' 375000',
 ' 600000',
 ' 332000',
 ' 250000',
 ' 875000',
 ' 560000',
 ' 975000',
 ' 975000',
 ' 225000',
 ' 700000',
 ' 830000',
 ' 450000',
 ' 200000',
 ' 270000',
 ' 389000',
 ' 195000',
 ' 700000',
 ' 245000',
 ' 185000',
 ' 2000000',
 ' 1490000',
 ' 550000',
 ' 370000',
 ' 225000',
 ' 440000',
 ' 985000',
 ' 351000',
 ' 520000',
 ' 750000',
 ' 275000',
 ' 750000',
 ' 550000',
 ' 475000',
 ' 2450000',
 ' 160000',
 ' 540000',
 ' 495000',
 ' 1150000',
 ' 499000']

In [114]:
#Converting the column into integer type

for i in range(0, len(Price_4)):
    Price_4[i] = int(Price_4[i])

In [115]:
#Printing after conversion

Price_4

[575000,
 265000,
 215000,
 155000,
 540000,
 168000,
 595000,
 450000,
 440000,
 325000,
 325000,
 1850000,
 745000,
 1575000,
 225000,
 575000,
 251000,
 115000,
 450000,
 3751000,
 825000,
 620000,
 665000,
 950000,
 877000,
 145000,
 1280000,
 950000,
 385000,
 325000,
 125000,
 480000,
 675000,
 210000,
 560000,
 145000,
 265000,
 339000,
 270000,
 195000,
 298000,
 325000,
 235000,
 150000,
 1250000,
 425000,
 280000,
 565000,
 255000,
 125000,
 260000,
 2151000,
 365000,
 225000,
 150000,
 550000,
 650000,
 625000,
 890000,
 155000,
 165000,
 471000,
 290000,
 500000,
 235000,
 291000,
 851000,
 475000,
 475001,
 250000,
 350000,
 681000,
 325000,
 230000,
 275000,
 690000,
 300000,
 790000,
 1300000,
 1650000,
 575000,
 285000,
 3900000,
 111500,
 350000,
 211000,
 145000,
 315000,
 965000,
 141000,
 535000,
 595000,
 451000,
 159000,
 365000,
 380000,
 1350000,
 450000,
 399000,
 275000,
 1431000,
 139000,
 225000,
 480000,
 400000,
 580000,
 849000,
 1090000,
 650000,
 1375000,
 2775000,
 925000,
 125000,
 230000,
 270000,
 125000,
 3450000,
 690000,
 128000,
 725000,
 2000002,
 325000,
 775000,
 155000,
 150000,
 650000,
 625000,
 725000,
 142000,
 185000,
 1451000,
 211000,
 185000,
 465000,
 340000,
 311000,
 751000,
 625000,
 875000,
 260000,
 530000,
 195000,
 1245000,
 355000,
 190000,
 190000,
 270000,
 1750000,
 625000,
 625000,
 270000,
 350000,
 200000,
 211000,
 125000,
 200000,
 351000,
 350000,
 148500,
 690000,
 1290000,
 1950000,
 505000,
 295000,
 725786,
 450000,
 400000,
 550000,
 690000,
 485000,
 680000,
 1135000,
 475000,
 200000,
 675000,
 495000,
 725000,
 1650000,
 820000,
 235000,
 585000,
 735000,
 1390000,
 775000,
 70000,
 161000,
 135000,
 291000,
 225000,
 390000,
 240000,
 360000,
 575000,
 1205000,
 210000,
 675000,
 551000,
 150000,
 95000,
 935000,
 625000,
 750000,
 210000,
 420000,
 280000,
 310000,
 405000,
 440000,
 380000,
 355000,
 475000,
 560000,
 550000,
 570000,
 560000,
 699000,
 450000,
 655000,
 115000,
 1200000,
 260000,
 1700000,
 2200000,
 250000,
 450000,
 780000,
 1199999,
 425000,
 669999,
 142786,
 1500000,
 750000,
 200000,
 1200000,
 580000,
 250000,
 475000,
 460000,
 700000,
 550000,
 590000,
 925000,
 751000,
 521000,
 410000,
 525000,
 625000,
 411000,
 235000,
 575000,
 385000,
 150000,
 1285000,
 195000,
 1800000,
 270000,
 511000,
 390000,
 60000,
 685000,
 235000,
 521000,
 500000,
 431000,
 185000,
 835000,
 540000,
 360000,
 435000,
 511000,
 290000,
 465000,
 545000,
 251000,
 850000,
 461000,
 541000,
 275000,
 311000,
 630000,
 925000,
 375000,
 2875000,
 200000,
 549000,
 560000,
 1375000,
 1375000,
 325000,
 385000,
 411000,
 1625000,
 215000,
 250000,
 595000,
 790000,
 851000,
 580000,
 360000,
 750000,
 611000,
 861000,
 295000,
 200000,
 1500000,
 885000,
 340000,
 470000,
 345000,
 1290000,
 240000,
 640000,
 245000,
 745000,
 875000,
 375000,
 555000,
 321000,
 215000,
 330000,
 285000,
 2600000,
 775000,
 250000,
 1650000,
 1515000,
 560000,
 1975000,
 5800000,
 800000,
 135000,
 75000,
 690000,
 380000,
 460000,
 1250000,
 55000,
 670000,
 425000,
 230000,
 355000,
 1450000,
 350000,
 125000,
 360000,
 690143,
 171000,
 201000,
 340000,
 96000,
 250000,
 525000,
 550000,
 965000,
 575000,
 275000,
 450786,
 300000,
 435143,
 690000,
 675000,
 1161000,
 399999,
 450000,
 85000,
 440000,
 1250000,
 130000,
 580000,
 270000,
 155000,
 150000,
 1250000,
 850000,
 1250000,
 740000,
 70000,
 191000,
 490143,
 265000,
 351000,
 541000,
 3300000,
 120000,
 825000,
 1499000,
 575000,
 3950000,
 3650000,
 1550000,
 250000,
 475000,
 850000,
 2250000,
 750000,
 1250000,
 215000,
 700000,
 120000,
 1450000,
 745000,
 230000,
 451000,
 465000,
 125000,
 445143,
 400000,
 520000,
 300000,
 475000,
 395000,
 635000,
 475000,
 385000,
 1150000,
 3250000,
 775000,
 365000,
 575000,
 350000,
 185000,
 675000,
 110000,
 750000,
 350000,
 690000,
 525000,
 1700000,
 560000,
 875000,
 271000,
 230000,
 355000,
 550000,
 400000,
 450000,
 25000,
 1711000,
 550000,
 850000,
 1875000,
 3285000,
 431000,
 80000,
 130000,
 231000,
 1050000,
 179000,
 575000,
 60000,
 85000,
 155000,
 875000,
 975000,
 140000,
 551000,
 1650000,
 250000,
 635000,
 635000,
 2051000,
 375000,
 600000,
 332000,
 250000,
 875000,
 560000,
 975000,
 975000,
 225000,
 700000,
 830000,
 450000,
 200000,
 270000,
 389000,
 195000,
 700000,
 245000,
 185000,
 2000000,
 1490000,
 550000,
 370000,
 225000,
 440000,
 985000,
 351000,
 520000,
 750000,
 275000,
 750000,
 550000,
 475000,
 2450000,
 160000,
 540000,
 495000,
 1150000,
 499000]

In [117]:
#Fetching data from olx for Year

for y4 in driver4.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Year_4.append(y4.text.split('-')[0])

In [118]:
#Converting the column into integer type

for i in range(0, len(Year_4)):
    Year_4[i] = int(Year_4[i])

In [119]:
#Printing after conversion

Year_4

[2014,
 2013,
 2014,
 2007,
 2012,
 2001,
 2018,
 2020,
 2015,
 2013,
 2013,
 2013,
 2020,
 2017,
 2010,
 2015,
 2012,
 2010,
 2019,
 2018,
 2015,
 2016,
 2016,
 2016,
 2015,
 2007,
 2014,
 2016,
 2009,
 2018,
 2007,
 2016,
 2018,
 2010,
 2017,
 2009,
 2013,
 2013,
 2011,
 2010,
 2013,
 2012,
 2010,
 2012,
 2020,
 2014,
 2019,
 2015,
 2008,
 2006,
 2016,
 2017,
 1913,
 2014,
 2007,
 2012,
 2015,
 2015,
 2017,
 2006,
 2009,
 2012,
 2014,
 2020,
 2005,
 2011,
 2015,
 2013,
 2013,
 2004,
 2019,
 2012,
 2016,
 2012,
 2011,
 2013,
 2011,
 2016,
 2018,
 2016,
 2015,
 2017,
 2017,
 1990,
 2013,
 2011,
 2008,
 2012,
 2017,
 2009,
 2019,
 2020,
 2018,
 2014,
 2005,
 2015,
 2013,
 2019,
 2014,
 2013,
 2015,
 2010,
 2007,
 2018,
 2017,
 2011,
 2021,
 2019,
 2016,
 2018,
 2017,
 2020,
 2018,
 2011,
 2015,
 2011,
 2017,
 2013,
 2007,
 2012,
 2021,
 2014,
 2017,
 2011,
 2011,
 2017,
 2015,
 2012,
 2014,
 2011,
 2013,
 2010,
 2009,
 2016,
 2014,
 2017,
 2019,
 2018,
 2019,
 2011,
 2019,
 2009,
 2016,
 2017,
 2011,
 2008,
 2015,
 2014,
 2014,
 2016,
 2010,
 2013,
 2011,
 2011,
 2006,
 2010,
 2013,
 2016,
 2009,
 2013,
 2016,
 2019,
 2021,
 2011,
 2020,
 2012,
 2015,
 2016,
 2013,
 2015,
 2017,
 2016,
 2013,
 2011,
 2020,
 2017,
 2012,
 2013,
 2017,
 2012,
 2015,
 2018,
 2014,
 2019,
 1998,
 2014,
 2009,
 2012,
 2008,
 2012,
 2007,
 2019,
 2016,
 2014,
 2010,
 2018,
 2014,
 2009,
 2001,
 2016,
 2016,
 2019,
 2013,
 2015,
 2010,
 2011,
 2013,
 2014,
 2013,
 2012,
 2017,
 2015,
 2016,
 2015,
 2016,
 2017,
 2015,
 2013,
 2007,
 2011,
 2010,
 2019,
 2017,
 2012,
 2014,
 2013,
 2010,
 2016,
 2017,
 2013,
 2013,
 2016,
 2015,
 2016,
 2015,
 2013,
 2014,
 2018,
 2013,
 2014,
 2015,
 2020,
 2020,
 2010,
 2014,
 2014,
 2016,
 2016,
 2011,
 2015,
 2013,
 2007,
 2019,
 2009,
 2011,
 2017,
 2014,
 2010,
 2011,
 2019,
 2011,
 2015,
 2015,
 2016,
 2008,
 2020,
 2014,
 2016,
 2014,
 2012,
 2012,
 2015,
 2019,
 2016,
 2019,
 2020,
 2017,
 2011,
 2014,
 2017,
 2019,
 2017,
 2018,
 2007,
 2014,
 2015,
 2018,
 2018,
 2011,
 2015,
 2012,
 2021,
 2013,
 2010,
 2018,
 2014,
 2015,
 2016,
 2015,
 2018,
 2016,
 2017,
 2011,
 2012,
 2011,
 2017,
 2014,
 2014,
 2017,
 2012,
 2010,
 2014,
 2012,
 2020,
 2018,
 2012,
 2016,
 2008,
 2011,
 2013,
 2013,
 2017,
 2008,
 2012,
 2014,
 2015,
 2018,
 2019,
 2021,
 2018,
 2012,
 2007,
 2013,
 2015,
 2018,
 2013,
 2006,
 2019,
 2017,
 2012,
 2009,
 2015,
 2014,
 2004,
 2017,
 2016,
 2009,
 2011,
 2013,
 2012,
 2011,
 2017,
 2017,
 2016,
 2016,
 2011,
 2017,
 2016,
 2011,
 2018,
 2018,
 2021,
 2013,
 2014,
 2007,
 2011,
 2012,
 2004,
 2020,
 2012,
 2007,
 2010,
 2012,
 2017,
 2012,
 2017,
 2001,
 2008,
 2014,
 2012,
 2010,
 2019,
 2017,
 2008,
 2018,
 2015,
 2016,
 2019,
 2019,
 2019,
 2016,
 2011,
 2018,
 2015,
 2019,
 2008,
 2008,
 2010,
 2008,
 2015,
 2016,
 2010,
 2014,
 2018,
 2005,
 2014,
 2012,
 2015,
 2013,
 2013,
 1968,
 2018,
 2013,
 2015,
 2021,
 2016,
 2014,
 2012,
 2016,
 2014,
 2010,
 2015,
 2010,
 2013,
 2013,
 2016,
 2014,
 2012,
 2016,
 2016,
 2015,
 2010,
 2012,
 2017,
 2015,
 2015,
 2020,
 2014,
 2011,
 2018,
 2017,
 2020,
 2013,
 2006,
 2010,
 2011,
 2017,
 2010,
 2016,
 2008,
 2007,
 2012,
 2015,
 2019,
 2012,
 2015,
 2015,
 2013,
 2015,
 2015,
 2016,
 2015,
 2016,
 2010,
 2007,
 2016,
 2016,
 2019,
 2019,
 2011,
 2009,
 2017,
 2015,
 2010,
 2010,
 2019,
 2009,
 2013,
 2010,
 2009,
 2021,
 2013,
 2015,
 2012,
 2010,
 2014,
 2011,
 2013,
 2016,
 2017,
 2015,
 2017,
 2013,
 2013,
 2018,
 2006,
 2015,
 2015,
 2018,
 2012]

In [121]:
#Fetching data from olx for Km used, Company, Location, Date of posting

for k4 in driver4.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Km_4.append(k4.text.split('-')[1])
for c4 in driver4.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[2]"):
    Company_4.append(c4.text)
for l4 in driver4.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]"):
    Location_4.append(l4.text)
for d4 in driver4.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]/span"):
    Date_4.append(d4.text)

In [122]:
#Making a dataframe named Cars storing 500 data into that

CARS4=pd.DataFrame({})
CARS4['PRICE']=Price_4[0:500]
CARS4['YEAR']=Year_4[0:500]
CARS4['KM']=Km_4[0:500]
CARS4['COMPANY']=Company_4[0:500]
CARS4['LOCATION']=Location_4[0:500]
CARS4['POSTED-DATE']=Date_4[0:500]

In [123]:
#Printing the dataframe

CARS4

,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE
0,575000,2014,"128,000 km",Hyundai Elantra,Vadsar\nDec 28,Dec 28
1,265000,2013,"85,000 km",Maruti Suzuki Ritz,SG Highway\nJan 07,Jan 07
2,215000,2014,"68,150 km",Maruti Suzuki Alto K10,Vadsar\nJan 02,Jan 02
3,155000,2007,"90,000 km",Hyundai Santro,Hussain Tekri\nToday,Today
4,540000,2012,"180,700 km",Volkswagen Passat,Korecha Nagar\nYesterday,Yesterday
...,...,...,...,...,...,...
495,160000,2006,"58,000 km",Maruti Suzuki Wagon R,Naranpura\nToday,Today
496,540000,2015,"81,000 km",Mahindra TUV 300,Vejalpur\nToday,Today
497,495000,2015,"27,500 km",Maruti Suzuki Swift,Navrangpura\nToday,Today
498,1150000,2018,"65,000 km",Jeep Compass,Naranpura\nToday,Today
499,499000,2012,"82,000 km",Mahindra XUV500,Naranpura\nToday,Today

In [124]:
#Getting the information of the dataset

CARS4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRICE        500 non-null    int64
 1   YEAR         500 non-null    int64
 2   KM           500 non-null    object
 3   COMPANY      500 non-null    object
 4   LOCATION     500 non-null    object
 5   POSTED-DATE  500 non-null    object
dtypes: int64(2), object(4)
memory usage: 23.6+ KB

In [125]:
driver4.close()

# 1998 DATA IS WE HAVE ALL IN NOW

In [126]:
#Creating an instance of the chrome driver to get to the url

driver5 = webdriver.Chrome(r'E:/CHROME-DRIVER/chromedriver_win32/chromedriver.exe')

In [127]:
#Getting into the website

driver5.get('https://www.olx.in/en-in/tamil-nadu_g2001173/cars_c84')

In [128]:
#Creating empty lists so that we can fetch the data

Price_5=[]
Year_5=[]
Km_5=[]
Company_5=[]
Location_5=[]
Date_5=[]

In [130]:
#Fetching the data from olx for Price

for p5 in driver5.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/span"):
    Price_5.append(p5.text.replace("â‚¹","").replace(",",""))

In [131]:
#Printing the price

Price_5

[' 325000',
 ' 265000',
 ' 515000',
 ' 275000',
 ' 33000',
 ' 410000',
 ' 20000',
 ' 455000',
 ' 400000',
 ' 2850000',
 ' 249000',
 ' 210000',
 ' 4990000',
 ' 420000',
 ' 465000',
 ' 525000',
 ' 220000',
 ' 290000',
 ' 645000',
 ' 390000',
 ' 1950000',
 ' 400000',
 ' 450000',
 ' 465000',
 ' 815000',
 ' 465000',
 ' 690000',
 ' 295000',
 ' 295000',
 ' 400000',
 ' 630000',
 ' 220000',
 ' 220000',
 ' 630000',
 ' 1550000',
 ' 450000',
 ' 425000',
 ' 660000',
 ' 600000',
 ' 435000',
 ' 520000',
 ' 1900000',
 ' 750000',
 ' 390000',
 ' 390000',
 ' 535000',
 ' 450000',
 ' 575000',
 ' 325000',
 ' 680000',
 ' 565000',
 ' 435000',
 ' 525000',
 ' 695000',
 ' 615000',
 ' 535000',
 ' 415000',
 ' 425000',
 ' 435000',
 ' 795000',
 ' 925000',
 ' 175000',
 ' 740000',
 ' 525000',
 ' 485000',
 ' 1825000',
 ' 48000',
 ' 475000',
 ' 325000',
 ' 390000',
 ' 80000',
 ' 595000',
 ' 575000',
 ' 490000',
 ' 370000',
 ' 240000',
 ' 500000',
 ' 340000',
 ' 130000',
 ' 2700000',
 ' 575000',
 ' 350000',
 ' 850000',
 ' 950000',
 ' 180999',
 ' 285000',
 ' 285000',
 ' 800000',
 ' 1850000',
 ' 1150000',
 ' 1150000',
 ' 495000',
 ' 670000',
 ' 485000',
 ' 535000',
 ' 445000',
 ' 415000',
 ' 490000',
 ' 460000',
 ' 560000',
 ' 1265000',
 ' 300000',
 ' 649999',
 ' 1000000',
 ' 160000',
 ' 449999',
 ' 225000',
 ' 215000',
 ' 245000',
 ' 450000',
 ' 174000',
 ' 195000',
 ' 170000',
 ' 750000',
 ' 145000',
 ' 870000',
 ' 155000',
 ' 355000',
 ' 1645000',
 ' 225000',
 ' 350000',
 ' 240000',
 ' 550000',
 ' 350000',
 ' 120000',
 ' 1800000',
 ' 135000',
 ' 330000',
 ' 2750000',
 ' 465000',
 ' 62000',
 ' 436000',
 ' 55000',
 ' 60000',
 ' 285000',
 ' 345000',
 ' 360000',
 ' 1200000',
 ' 1450000',
 ' 60000',
 ' 875000',
 ' 400000',
 ' 395000',
 ' 850000',
 ' 650000',
 ' 600000',
 ' 160000',
 ' 310000',
 ' 490000',
 ' 220000',
 ' 624000',
 ' 720000',
 ' 260000',
 ' 435000',
 ' 750000',
 ' 315000',
 ' 265000',
 ' 210000',
 ' 360000',
 ' 850000',
 ' 595000',
 ' 699000',
 ' 2150000',
 ' 175000',
 ' 1380000',
 ' 400000',
 ' 480000',
 ' 670000',
 ' 290000',
 ' 615000',
 ' 610000',
 ' 2050000',
 ' 349000',
 ' 810000',
 ' 680000',
 ' 550000',
 ' 400000',
 ' 500000',
 ' 465000',
 ' 725000',
 ' 989000',
 ' 325000',
 ' 420000',
 ' 150000',
 ' 174999',
 ' 95000',
 ' 615000',
 ' 325000',
 ' 525000',
 ' 263000',
 ' 1075000',
 ' 2350000',
 ' 80000',
 ' 1850000',
 ' 380000',
 ' 365000',
 ' 450000',
 ' 175000',
 ' 560000',
 ' 640000',
 ' 186000',
 ' 220000',
 ' 1825000',
 ' 375000',
 ' 575000',
 ' 400000',
 ' 585000',
 ' 850000',
 ' 650000',
 ' 295000',
 ' 90000',
 ' 400000',
 ' 750000',
 ' 825000',
 ' 550000',
 ' 510000',
 ' 1250000',
 ' 1400000',
 ' 199000',
 ' 350000',
 ' 745000',
 ' 390000',
 ' 390000',
 ' 625000',
 ' 475000',
 ' 175000',
 ' 1150000',
 ' 2350000',
 ' 625000',
 ' 500000',
 ' 255000',
 ' 890000',
 ' 325000',
 ' 565000',
 ' 290000',
 ' 510000',
 ' 920000',
 ' 210000',
 ' 485000',
 ' 460000',
 ' 495000',
 ' 600000',
 ' 425000',
 ' 445000',
 ' 275000',
 ' 625000',
 ' 750000',
 ' 270000',
 ' 310000',
 ' 245000',
 ' 300000',
 ' 750000',
 ' 375000',
 ' 545000',
 ' 700000',
 ' 765000',
 ' 320000',
 ' 315000',
 ' 445000',
 ' 825000',
 ' 1145000',
 ' 445000',
 ' 440000',
 ' 525000',
 ' 130000',
 ' 139000',
 ' 220000',
 ' 690000',
 ' 225000',
 ' 169000',
 ' 65000',
 ' 385000',
 ' 1700000',
 ' 175000',
 ' 1099000',
 ' 980000',
 ' 100000',
 ' 170000',
 ' 169000',
 ' 950000',
 ' 295000',
 ' 450000',
 ' 130000',
 ' 290000',
 ' 290000',
 ' 195000',
 ' 695000',
 ' 475000',
 ' 860000',
 ' 550000',
 ' 210000',
 ' 600000',
 ' 600000',
 ' 600000',
 ' 575000',
 ' 525000',
 ' 439000',
 ' 160000',
 ' 550000',
 ' 570000',
 ' 650000',
 ' 290000',
 ' 1177000',
 ' 290000',
 ' 440000',
 ' 335000',
 ' 570000',
 ' 950000',
 ' 460000',
 ' 325000',
 ' 950000',
 ' 515000',
 ' 680000',
 ' 325000',
 ' 415000',
 ' 825000',
 ' 550000',
 ' 175000',
 ' 690000',
 ' 280000',
 ' 575000',
 ' 195000',
 ' 1850000',
 ' 290000',
 ' 535000',
 ' 550000',
 ' 2950000',
 ' 590000',
 ' 1350000',
 ' 75000',
 ' 300000',
 ' 350000',
 ' 165000',
 ' 108000',
 ' 450000',
 ' 830000',
 ' 1750000',
 ' 35000',
 ' 750000',
 ' 210000',
 ' 280000',
 ' 300000',
 ' 78000',
 ' 310000',
 ' 485000',
 ' 160000',
 ' 495000',
 ' 890000',
 ' 649000',
 ' 90000',
 ' 325000',
 ' 550000',
 ' 760000',
 ' 180000',
 ' 575000',
 ' 290000',
 ' 200000',
 ' 235000',
 ' 135000',
 ' 215000',
 ' 150000',
 ' 195000',
 ' 299999',
 ' 195000',
 ' 385000',
 ' 500000',
 ' 890000',
 ' 1250000',
 ' 328000',
 ' 875000',
 ' 250000',
 ' 1170000',
 ' 155000',
 ' 750000',
 ' 380000',
 ' 2475000',
 ' 610000',
 ' 685000',
 ' 610000',
 ' 510000',
 ' 730000',
 ' 475000',
 ' 475000',
 ' 460000',
 ' 645000',
 ' 390000',
 ' 995000',
 ' 1010000',
 ' 1950000',
 ' 750000',
 ' 499000',
 ' 625000',
 ' 560000',
 ' 142000',
 ' 750000',
 ' 1950000',
 ' 7900000',
 ' 175000',
 ' 625000',
 ' 290000',
 ' 395000',
 ' 260000',
 ' 220000',
 ' 280000',
 ' 490000',
 ' 225000',
 ' 1490000',
 ' 740000',
 ' 360000',
 ' 510000',
 ' 595000',
 ' 510000',
 ' 2000000',
 ' 350000',
 ' 680000',
 ' 700000',
 ' 700000',
 ' 730000',
 ' 465000',
 ' 600000',
 ' 290000',
 ' 270000',
 ' 1020000',
 ' 440000',
 ' 335000',
 ' 270000',
 ' 1440000',
 ' 220000',
 ' 650000',
 ' 220000',
 ' 425000',
 ' 575000',
 ' 390000',
 ' 425000',
 ' 360000',
 ' 725000',
 ' 415000',
 ' 680000',
 ' 385000',
 ' 425000',
 ' 1150000',
 ' 2200000',
 ' 150000',
 ' 90000',
 ' 285000',
 ' 380000',
 ' 649999',
 ' 175000',
 ' 290000',
 ' 67000',
 ' 225000',
 ' 235000',
 ' 235000',
 ' 165000',
 ' 200000',
 ' 195000',
 ' 700000',
 ' 92000',
 ' 525000',
 ' 373000',
 ' 1175000',
 ' 730000',
 ' 250000',
 ' 625000',
 ' 450000',
 ' 370000',
 ' 980000',
 ' 380000',
 ' 365000',
 ' 555000',
 ' 650000',
 ' 4300000',
 ' 2700000',
 ' 4250000',
 ' 315000',
 ' 345000',
 ' 248000',
 ' 510000',
 ' 279999',
 ' 290000',
 ' 739000',
 ' 165000',
 ' 550000',
 ' 335000',
 ' 590000',
 ' 515000',
 ' 625000',
 ' 610000',
 ' 870000',
 ' 615000',
 ' 1500000',
 ' 335000',
 ' 290000',
 ' 595000',
 ' 625000',
 ' 300000',
 ' 740000',
 ' 310000',
 ' 420000',
 ' 445000',
 ' 510000',
 ' 395000',
 ' 790000',
 ' 320000',
 ' 950000',
 ' 700000',
 ' 395000',
 ' 270000',
 ' 194500',
 ' 189000',
 ' 265000',
 ' 475000',
 ' 850000']

In [132]:
#Converting the column into integer type

for i in range(0, len(Price_5)):
    Price_5[i] = int(Price_5[i])

In [133]:
#Printing after conversion

Price_5

[325000,
 265000,
 515000,
 275000,
 33000,
 410000,
 20000,
 455000,
 400000,
 2850000,
 249000,
 210000,
 4990000,
 420000,
 465000,
 525000,
 220000,
 290000,
 645000,
 390000,
 1950000,
 400000,
 450000,
 465000,
 815000,
 465000,
 690000,
 295000,
 295000,
 400000,
 630000,
 220000,
 220000,
 630000,
 1550000,
 450000,
 425000,
 660000,
 600000,
 435000,
 520000,
 1900000,
 750000,
 390000,
 390000,
 535000,
 450000,
 575000,
 325000,
 680000,
 565000,
 435000,
 525000,
 695000,
 615000,
 535000,
 415000,
 425000,
 435000,
 795000,
 925000,
 175000,
 740000,
 525000,
 485000,
 1825000,
 48000,
 475000,
 325000,
 390000,
 80000,
 595000,
 575000,
 490000,
 370000,
 240000,
 500000,
 340000,
 130000,
 2700000,
 575000,
 350000,
 850000,
 950000,
 180999,
 285000,
 285000,
 800000,
 1850000,
 1150000,
 1150000,
 495000,
 670000,
 485000,
 535000,
 445000,
 415000,
 490000,
 460000,
 560000,
 1265000,
 300000,
 649999,
 1000000,
 160000,
 449999,
 225000,
 215000,
 245000,
 450000,
 174000,
 195000,
 170000,
 750000,
 145000,
 870000,
 155000,
 355000,
 1645000,
 225000,
 350000,
 240000,
 550000,
 350000,
 120000,
 1800000,
 135000,
 330000,
 2750000,
 465000,
 62000,
 436000,
 55000,
 60000,
 285000,
 345000,
 360000,
 1200000,
 1450000,
 60000,
 875000,
 400000,
 395000,
 850000,
 650000,
 600000,
 160000,
 310000,
 490000,
 220000,
 624000,
 720000,
 260000,
 435000,
 750000,
 315000,
 265000,
 210000,
 360000,
 850000,
 595000,
 699000,
 2150000,
 175000,
 1380000,
 400000,
 480000,
 670000,
 290000,
 615000,
 610000,
 2050000,
 349000,
 810000,
 680000,
 550000,
 400000,
 500000,
 465000,
 725000,
 989000,
 325000,
 420000,
 150000,
 174999,
 95000,
 615000,
 325000,
 525000,
 263000,
 1075000,
 2350000,
 80000,
 1850000,
 380000,
 365000,
 450000,
 175000,
 560000,
 640000,
 186000,
 220000,
 1825000,
 375000,
 575000,
 400000,
 585000,
 850000,
 650000,
 295000,
 90000,
 400000,
 750000,
 825000,
 550000,
 510000,
 1250000,
 1400000,
 199000,
 350000,
 745000,
 390000,
 390000,
 625000,
 475000,
 175000,
 1150000,
 2350000,
 625000,
 500000,
 255000,
 890000,
 325000,
 565000,
 290000,
 510000,
 920000,
 210000,
 485000,
 460000,
 495000,
 600000,
 425000,
 445000,
 275000,
 625000,
 750000,
 270000,
 310000,
 245000,
 300000,
 750000,
 375000,
 545000,
 700000,
 765000,
 320000,
 315000,
 445000,
 825000,
 1145000,
 445000,
 440000,
 525000,
 130000,
 139000,
 220000,
 690000,
 225000,
 169000,
 65000,
 385000,
 1700000,
 175000,
 1099000,
 980000,
 100000,
 170000,
 169000,
 950000,
 295000,
 450000,
 130000,
 290000,
 290000,
 195000,
 695000,
 475000,
 860000,
 550000,
 210000,
 600000,
 600000,
 600000,
 575000,
 525000,
 439000,
 160000,
 550000,
 570000,
 650000,
 290000,
 1177000,
 290000,
 440000,
 335000,
 570000,
 950000,
 460000,
 325000,
 950000,
 515000,
 680000,
 325000,
 415000,
 825000,
 550000,
 175000,
 690000,
 280000,
 575000,
 195000,
 1850000,
 290000,
 535000,
 550000,
 2950000,
 590000,
 1350000,
 75000,
 300000,
 350000,
 165000,
 108000,
 450000,
 830000,
 1750000,
 35000,
 750000,
 210000,
 280000,
 300000,
 78000,
 310000,
 485000,
 160000,
 495000,
 890000,
 649000,
 90000,
 325000,
 550000,
 760000,
 180000,
 575000,
 290000,
 200000,
 235000,
 135000,
 215000,
 150000,
 195000,
 299999,
 195000,
 385000,
 500000,
 890000,
 1250000,
 328000,
 875000,
 250000,
 1170000,
 155000,
 750000,
 380000,
 2475000,
 610000,
 685000,
 610000,
 510000,
 730000,
 475000,
 475000,
 460000,
 645000,
 390000,
 995000,
 1010000,
 1950000,
 750000,
 499000,
 625000,
 560000,
 142000,
 750000,
 1950000,
 7900000,
 175000,
 625000,
 290000,
 395000,
 260000,
 220000,
 280000,
 490000,
 225000,
 1490000,
 740000,
 360000,
 510000,
 595000,
 510000,
 2000000,
 350000,
 680000,
 700000,
 700000,
 730000,
 465000,
 600000,
 290000,
 270000,
 1020000,
 440000,
 335000,
 270000,
 1440000,
 220000,
 650000,
 220000,
 425000,
 575000,
 390000,
 425000,
 360000,
 725000,
 415000,
 680000,
 385000,
 425000,
 1150000,
 2200000,
 150000,
 90000,
 285000,
 380000,
 649999,
 175000,
 290000,
 67000,
 225000,
 235000,
 235000,
 165000,
 200000,
 195000,
 700000,
 92000,
 525000,
 373000,
 1175000,
 730000,
 250000,
 625000,
 450000,
 370000,
 980000,
 380000,
 365000,
 555000,
 650000,
 4300000,
 2700000,
 4250000,
 315000,
 345000,
 248000,
 510000,
 279999,
 290000,
 739000,
 165000,
 550000,
 335000,
 590000,
 515000,
 625000,
 610000,
 870000,
 615000,
 1500000,
 335000,
 290000,
 595000,
 625000,
 300000,
 740000,
 310000,
 420000,
 445000,
 510000,
 395000,
 790000,
 320000,
 950000,
 700000,
 395000,
 270000,
 194500,
 189000,
 265000,
 475000,
 850000]

In [134]:
#Fetching data from olx for Year

for y5 in driver5.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Year_5.append(y5.text.split('-')[0])

In [135]:
#Converting the column into integer type

for i in range(0, len(Year_5)):
    Year_5[i] = int(Year_5[i])

In [136]:
#Printing after conversion

Year_5

[2011,
 2009,
 2015,
 2012,
 1997,
 2013,
 2014,
 2013,
 2007,
 2018,
 2010,
 2009,
 2016,
 2011,
 2014,
 2014,
 2003,
 2013,
 2015,
 2011,
 2017,
 2012,
 2013,
 2013,
 2018,
 2011,
 2015,
 2017,
 2013,
 2010,
 2019,
 2017,
 2017,
 2019,
 2014,
 2012,
 2009,
 2018,
 2018,
 2008,
 2018,
 2017,
 2008,
 2011,
 2011,
 2015,
 2016,
 2014,
 2018,
 2017,
 2016,
 2015,
 2019,
 2016,
 2016,
 2012,
 2014,
 2011,
 2015,
 2016,
 2014,
 2012,
 2014,
 2016,
 2014,
 2017,
 1998,
 2013,
 2017,
 2014,
 2004,
 2019,
 2019,
 2010,
 2009,
 2012,
 2018,
 2012,
 2006,
 2014,
 2016,
 2006,
 2018,
 2019,
 2006,
 2012,
 2009,
 2011,
 2018,
 2019,
 2019,
 2017,
 2019,
 2013,
 2015,
 2014,
 2014,
 2012,
 2017,
 2016,
 2014,
 2009,
 2019,
 2018,
 2014,
 2012,
 2010,
 2008,
 2008,
 2013,
 2013,
 2011,
 2007,
 2015,
 2007,
 2019,
 2012,
 2012,
 2016,
 2010,
 2015,
 2010,
 2017,
 2009,
 2012,
 2018,
 2003,
 2019,
 2020,
 2020,
 2000,
 2021,
 2002,
 2003,
 2012,
 2013,
 2013,
 2014,
 2013,
 2002,
 2012,
 2017,
 2016,
 2017,
 2017,
 2017,
 2012,
 2011,
 2013,
 2017,
 2018,
 2017,
 2006,
 2008,
 2018,
 2016,
 2014,
 2008,
 2009,
 2018,
 2016,
 2008,
 2017,
 2011,
 2014,
 2019,
 2016,
 2016,
 2013,
 2015,
 2012,
 2018,
 2012,
 2016,
 2019,
 2012,
 2018,
 2016,
 2013,
 2020,
 2016,
 2013,
 2010,
 2002,
 2009,
 2006,
 2017,
 2015,
 2011,
 2014,
 2019,
 2021,
 2001,
 2016,
 2010,
 2011,
 2013,
 2014,
 2015,
 2019,
 2005,
 2011,
 2016,
 2014,
 2018,
 2017,
 2016,
 2018,
 2013,
 2016,
 2004,
 2017,
 2019,
 2018,
 2015,
 2010,
 2017,
 2015,
 2005,
 2017,
 2016,
 2010,
 2017,
 2015,
 2011,
 2009,
 2017,
 2020,
 2015,
 2013,
 2012,
 2019,
 2013,
 2015,
 2007,
 2018,
 2018,
 2011,
 2016,
 2013,
 2017,
 2016,
 2011,
 2014,
 2009,
 2014,
 2008,
 2014,
 2010,
 2009,
 2012,
 2017,
 2014,
 2015,
 2015,
 2019,
 2017,
 2009,
 2014,
 2017,
 2016,
 2017,
 2011,
 2018,
 2004,
 2008,
 2013,
 2019,
 2012,
 2010,
 2002,
 2012,
 2012,
 2008,
 2018,
 2020,
 2004,
 2008,
 2003,
 2014,
 2016,
 2019,
 2007,
 2015,
 2014,
 2007,
 2017,
 2014,
 2018,
 2009,
 2009,
 2019,
 2019,
 2019,
 2010,
 2015,
 2016,
 2004,
 2015,
 2016,
 2007,
 2015,
 2020,
 2008,
 2011,
 2016,
 2014,
 2015,
 2016,
 2013,
 2009,
 2011,
 2017,
 2014,
 2014,
 2017,
 2019,
 2009,
 2015,
 2011,
 2016,
 2000,
 2015,
 2007,
 2015,
 2016,
 2017,
 2016,
 2009,
 2000,
 2007,
 2016,
 2010,
 2007,
 2014,
 2019,
 2020,
 1999,
 2017,
 2011,
 2012,
 2012,
 2007,
 2011,
 2017,
 2007,
 2012,
 2011,
 2019,
 2010,
 2010,
 2014,
 2018,
 2010,
 2017,
 2016,
 2010,
 2010,
 2009,
 2010,
 2011,
 2012,
 2012,
 2010,
 2013,
 2016,
 2018,
 2014,
 2015,
 2019,
 2018,
 2016,
 2007,
 2017,
 2018,
 2020,
 2019,
 2017,
 2016,
 2014,
 2013,
 2014,
 2013,
 2015,
 2018,
 2013,
 2008,
 2019,
 2019,
 2013,
 2013,
 2011,
 2018,
 2008,
 2017,
 2014,
 2018,
 2012,
 2016,
 2012,
 2009,
 2006,
 2010,
 2011,
 2016,
 2010,
 2013,
 2017,
 2017,
 2011,
 2018,
 2013,
 2016,
 2012,
 2017,
 2018,
 2016,
 2017,
 2016,
 2017,
 2011,
 2010,
 2018,
 2011,
 2016,
 2010,
 2012,
 2010,
 2014,
 2009,
 2015,
 2016,
 2012,
 2012,
 2008,
 2009,
 2014,
 2017,
 2015,
 2013,
 2011,
 2014,
 2006,
 2012,
 2016,
 2018,
 2015,
 2008,
 2016,
 2002,
 2010,
 2009,
 2012,
 2012,
 2012,
 2011,
 2017,
 2006,
 2011,
 2011,
 2019,
 2018,
 2012,
 2018,
 2015,
 2014,
 2016,
 2018,
 2011,
 2015,
 2008,
 2018,
 2014,
 2018,
 2015,
 2013,
 2012,
 2020,
 2010,
 2009,
 2012,
 2011,
 2014,
 2014,
 2015,
 2015,
 2016,
 2016,
 2017,
 2016,
 2012,
 2017,
 2016,
 2015,
 2017,
 2010,
 2014,
 2011,
 2018,
 2014,
 2013,
 2013,
 2014,
 2009,
 2019,
 2011,
 2017,
 2011,
 2005,
 2011,
 2009,
 2014,
 2016]

In [137]:
#Fetching data from olx for Km used, Company, Location, Date of posting

for k5 in driver5.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Km_5.append(k5.text.split('-')[1])
for c5 in driver5.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[2]"):
    Company_5.append(c5.text)
for l5 in driver5.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]"):
    Location_5.append(l5.text)
for d5 in driver5.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]/span"):
    Date_5.append(d5.text)

In [138]:
#Making a dataframe named Cars storing 500 data into that

CARS5=pd.DataFrame({})
CARS5['PRICE']=Price_5[0:500]
CARS5['YEAR']=Year_5[0:500]
CARS5['KM']=Km_5[0:500]
CARS5['COMPANY']=Company_5[0:500]
CARS5['LOCATION']=Location_5[0:500]
CARS5['POSTED-DATE']=Date_5[0:500]

In [139]:
#Printing the dataframe

CARS5

,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE
0,325000,2011,"48,530 km",Honda Brio,Tatabad Colony\nNov 25,Nov 25
1,265000,2009,"100,000 km",Hyundai i10,RS Puram\nJan 10,Jan 10
2,515000,2015,"41,000 km",Hyundai Xcent,Goldwins\nOct 16,Oct 16
3,275000,2012,"30,000 km",Chevrolet Optra Magnum,Chennai Central\n2 days ago,2 days ago
4,33000,1997,"10,000 km",Maruti Suzuki Zen,Kozhinjivadi\n3 days ago,3 days ago
...,...,...,...,...,...,...
495,300000,2010,"54,800 km",Hyundai i10,Asher Nagar\nToday,Today
496,740000,2014,"135,000 km",Volkswagen Jetta,Rakiyaplayam\nDec 23,Dec 23
497,310000,2011,"80,000 km",Hyundai i10,Avinash Residential Complex\nJan 07,Jan 07
498,420000,2018,"130,000 km",Tata Zest,Maduravoyal\nToday,Today
499,445000,2014,"67,000 km",Hyundai Xcent,Koyambedu\nToday,Today

In [141]:
#Getting the information of the dataset

CARS5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRICE        500 non-null    int64
 1   YEAR         500 non-null    int64
 2   KM           500 non-null    object
 3   COMPANY      500 non-null    object
 4   LOCATION     500 non-null    object
 5   POSTED-DATE  500 non-null    object
dtypes: int64(2), object(4)
memory usage: 23.6+ KB

In [142]:
driver5.close()

# 2498 IN TOTAL NOW

In [143]:
#Creating an instance of the chrome driver to get to the url

driver6 = webdriver.Chrome(r'E:/CHROME-DRIVER/chromedriver_win32/chromedriver.exe')

In [144]:
#Getting into the website

driver6.get('https://www.olx.in/en-in/chennai_g4059162/cars_c84')

In [145]:
#Creating empty lists so that we can fetch the data

Price_6=[]
Year_6=[]
Km_6=[]
Company_6=[]
Location_6=[]
Date_6=[]

In [147]:
#Fetching the data from olx for Price

for p6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/span"):
    Price_6.append(p6.text.replace("â‚¹","").replace(",",""))

In [148]:
Price_6

[' 6800000',
 ' 710000',
 ' 775000',
 ' 275000',
 ' 350000',
 ' 295000',
 ' 410000',
 ' 249000',
 ' 210000',
 ' 420000',
 ' 465000',
 ' 220000',
 ' 645000',
 ' 390000',
 ' 465000',
 ' 690000',
 ' 600000',
 ' 265000',
 ' 174000',
 ' 170000',
 ' 950000',
 ' 700000',
 ' 4400000',
 ' 263000',
 ' 155000',
 ' 355000',
 ' 225000',
 ' 1450000',
 ' 615000',
 ' 535000',
 ' 415000',
 ' 425000',
 ' 435000',
 ' 795000',
 ' 525000',
 ' 485000',
 ' 325000',
 ' 390000',
 ' 490000',
 ' 230000',
 ' 740000',
 ' 495000',
 ' 370000',
 ' 340000',
 ' 450000',
 ' 375000',
 ' 460000',
 ' 320000',
 ' 315000',
 ' 445000',
 ' 825000',
 ' 1145000',
 ' 445000',
 ' 440000',
 ' 139000',
 ' 175000',
 ' 1099000',
 ' 415000',
 ' 2250000',
 ' 1400000',
 ' 195000',
 ' 290000',
 ' 535000',
 ' 280000',
 ' 310000',
 ' 560000',
 ' 750000',
 ' 680000',
 ' 225000',
 ' 380000',
 ' 365000',
 ' 555000',
 ' 650000',
 ' 248000',
 ' 510000',
 ' 4000000',
 ' 730000',
 ' 950000',
 ' 395000',
 ' 950000',
 ' 395000',
 ' 265000',
 ' 340000',
 ' 345000',
 ' 650000',
 ' 360000',
 ' 1899000',
 ' 550000',
 ' 325000',
 ' 550000',
 ' 490000',
 ' 595000',
 ' 310000',
 ' 380000',
 ' 490000',
 ' 975000',
 ' 53000',
 ' 540000',
 ' 165000',
 ' 625000',
 ' 625000',
 ' 335000',
 ' 590000',
 ' 395000',
 ' 670000',
 ' 130000',
 ' 165000',
 ' 325000',
 ' 2490000',
 ' 615000',
 ' 390000',
 ' 750000',
 ' 680000',
 ' 1250000',
 ' 550000',
 ' 290000',
 ' 649000',
 ' 300000',
 ' 600000',
 ' 425000',
 ' 390000',
 ' 365000',
 ' 730000',
 ' 750000',
 ' 215000',
 ' 370000',
 ' 325000',
 ' 399999',
 ' 500000',
 ' 410000',
 ' 900000',
 ' 600000',
 ' 575000',
 ' 350000',
 ' 265000',
 ' 575000',
 ' 750000',
 ' 2500000',
 ' 510000',
 ' 555000',
 ' 335000',
 ' 585000',
 ' 850000',
 ' 1850000',
 ' 1200000',
 ' 375000',
 ' 280000',
 ' 535000',
 ' 995000',
 ' 630000',
 ' 145000',
 ' 165000',
 ' 650000',
 ' 165000',
 ' 170000',
 ' 820000',
 ' 1148000',
 ' 1360000',
 ' 375000',
 ' 135000',
 ' 1675000',
 ' 180000',
 ' 265000',
 ' 590000',
 ' 360000',
 ' 4500000',
 ' 750000',
 ' 375000',
 ' 575000',
 ' 395003',
 ' 360000',
 ' 220000',
 ' 295004',
 ' 300000',
 ' 225000',
 ' 450000',
 ' 625000',
 ' 600000',
 ' 770000',
 ' 510000',
 ' 410000',
 ' 165000',
 ' 335000',
 ' 440000',
 ' 850000',
 ' 725000',
 ' 560000',
 ' 325000',
 ' 600000',
 ' 700000',
 ' 440000',
 ' 980000',
 ' 765000',
 ' 265000',
 ' 340000',
 ' 540000',
 ' 270000',
 ' 3700000',
 ' 640000',
 ' 1350000',
 ' 525000',
 ' 375000',
 ' 390000',
 ' 400000',
 ' 440000',
 ' 655000',
 ' 450000',
 ' 297000',
 ' 1750000',
 ' 1250000',
 ' 275000',
 ' 410000',
 ' 475000',
 ' 369000',
 ' 700000',
 ' 450000',
 ' 565000',
 ' 550000',
 ' 220000',
 ' 445000',
 ' 220000',
 ' 9700000',
 ' 390000',
 ' 485000',
 ' 595000',
 ' 290000',
 ' 424000',
 ' 250000',
 ' 113000',
 ' 320000',
 ' 220000',
 ' 395000',
 ' 350000',
 ' 665000',
 ' 155000',
 ' 310000',
 ' 350000',
 ' 400000',
 ' 1100000',
 ' 620000',
 ' 4690000',
 ' 699999',
 ' 295000',
 ' 425000',
 ' 350000',
 ' 775000',
 ' 525000',
 ' 225000',
 ' 575000',
 ' 450000',
 ' 210000',
 ' 265000',
 ' 625000',
 ' 470000',
 ' 2700000',
 ' 825000',
 ' 1250000',
 ' 1050000',
 ' 325000',
 ' 1000000',
 ' 530000',
 ' 260000',
 ' 175000',
 ' 410000',
 ' 475000',
 ' 525000',
 ' 625000',
 ' 1500000',
 ' 375000',
 ' 2490000',
 ' 525000',
 ' 370000',
 ' 225000',
 ' 1425000',
 ' 1750000',
 ' 249000',
 ' 5390000',
 ' 395000',
 ' 135000',
 ' 325000',
 ' 210000',
 ' 380000',
 ' 170000',
 ' 390000',
 ' 410000',
 ' 160000',
 ' 845000',
 ' 670000',
 ' 960000',
 ' 130000',
 ' 520000',
 ' 215000',
 ' 225000',
 ' 265000',
 ' 115000',
 ' 275000',
 ' 265000',
 ' 225000',
 ' 190000',
 ' 240000',
 ' 1300000',
 ' 490000',
 ' 700000',
 ' 8300000',
 ' 1900000',
 ' 1100000',
 ' 2590000',
 ' 540000',
 ' 4200000',
 ' 1200000',
 ' 570000',
 ' 570000',
 ' 129000',
 ' 1990000',
 ' 1800000',
 ' 1190000',
 ' 375000',
 ' 1650000',
 ' 7950000',
 ' 725000',
 ' 1850000',
 ' 315000',
 ' 239000',
 ' 785000',
 ' 1650000',
 ' 240000',
 ' 7200000',
 ' 229000',
 ' 490000',
 ' 155000',
 ' 200000',
 ' 175000',
 ' 275000',
 ' 365000',
 ' 265000',
 ' 265000',
 ' 280000',
 ' 220000',
 ' 499999',
 ' 5490000',
 ' 1500000',
 ' 189999',
 ' 425000',
 ' 370000',
 ' 2290000',
 ' 1899000',
 ' 560000',
 ' 620000',
 ' 465000',
 ' 375000',
 ' 390000',
 ' 650000',
 ' 12800000',
 ' 74000',
 ' 2300000',
 ' 6800000',
 ' 825000',
 ' 590000',
 ' 460000',
 ' 900000',
 ' 220000',
 ' 220000',
 ' 740000',
 ' 220000',
 ' 285000',
 ' 750000',
 ' 690000',
 ' 625000',
 ' 360000',
 ' 1265000',
 ' 1200000',
 ' 260000',
 ' 370000',
 ' 690000',
 ' 425000',
 ' 345000',
 ' 350000',
 ' 145000',
 ' 250000',
 ' 1500000',
 ' 295000',
 ' 360000',
 ' 275000',
 ' 460000',
 ' 600000',
 ' 450000',
 ' 1310000',
 ' 25000',
 ' 230000',
 ' 150000',
 ' 300000',
 ' 690000',
 ' 675000',
 ' 575000',
 ' 1950000',
 ' 220000',
 ' 1500000',
 ' 485000',
 ' 765000',
 ' 620000',
 ' 230000',
 ' 230000',
 ' 650000',
 ' 1275000',
 ' 260000',
 ' 370000',
 ' 770000',
 ' 795000',
 ' 750000',
 ' 750000',
 ' 300000',
 ' 180000',
 ' 1140000',
 ' 790000',
 ' 390000',
 ' 375000',
 ' 235000',
 ' 4350000',
 ' 320000',
 ' 495000',
 ' 945000',
 ' 310000',
 ' 630000',
 ' 1180000',
 ' 635000',
 ' 640000',
 ' 350000',
 ' 220000',
 ' 2100000',
 ' 1350000',
 ' 600000',
 ' 625000',
 ' 199999',
 ' 655000',
 ' 575000',
 ' 345000',
 ' 390000',
 ' 340000',
 ' 445000',
 ' 370000',
 ' 820000',
 ' 360000',
 ' 2500000',
 ' 1000000',
 ' 390000',
 ' 325000',
 ' 395000',
 ' 550000',
 ' 205000',
 ' 925000',
 ' 225000',
 ' 325000',
 ' 1180000',
 ' 899999',
 ' 180000',
 ' 575000',
 ' 795000',
 ' 35000',
 ' 4790000',
 ' 425000',
 ' 4250000',
 ' 285000',
 ' 390000',
 ' 415000',
 ' 370000',
 ' 380000',
 ' 435000',
 ' 765000',
 ' 730000',
 ' 15000',
 ' 485000',
 ' 595000',
 ' 815000',
 ' 499999',
 ' 120000',
 ' 850000',
 ' 220000',
 ' 370000',
 ' 600000',
 ' 55000',
 ' 2275000',
 ' 380000',
 ' 825000',
 ' 300000',
 ' 800000',
 ' 675000',
 ' 7990000',
 ' 349000',
 ' 395000',
 ' 675000',
 ' 5590000',
 ' 310000',
 ' 155000',
 ' 250000',
 ' 159000',
 ' 140000',
 ' 415000',
 ' 560000',
 ' 425000',
 ' 1380000',
 ' 255000',
 ' 210000',
 ' 90000',
 ' 875000',
 ' 750000',
 ' 1000000',
 ' 650000',
 ' 500000',
 ' 1075000',
 ' 295000',
 ' 245000',
 ' 300000',
 ' 595000',
 ' 950000',
 ' 150000',
 ' 300000']

In [149]:
#Converting the column into integer type

for i in range(0, len(Price_6)):
    Price_6[i] = int(Price_6[i])

In [150]:
#Printing after conversion

Price_6

[6800000,
 710000,
 775000,
 275000,
 350000,
 295000,
 410000,
 249000,
 210000,
 420000,
 465000,
 220000,
 645000,
 390000,
 465000,
 690000,
 600000,
 265000,
 174000,
 170000,
 950000,
 700000,
 4400000,
 263000,
 155000,
 355000,
 225000,
 1450000,
 615000,
 535000,
 415000,
 425000,
 435000,
 795000,
 525000,
 485000,
 325000,
 390000,
 490000,
 230000,
 740000,
 495000,
 370000,
 340000,
 450000,
 375000,
 460000,
 320000,
 315000,
 445000,
 825000,
 1145000,
 445000,
 440000,
 139000,
 175000,
 1099000,
 415000,
 2250000,
 1400000,
 195000,
 290000,
 535000,
 280000,
 310000,
 560000,
 750000,
 680000,
 225000,
 380000,
 365000,
 555000,
 650000,
 248000,
 510000,
 4000000,
 730000,
 950000,
 395000,
 950000,
 395000,
 265000,
 340000,
 345000,
 650000,
 360000,
 1899000,
 550000,
 325000,
 550000,
 490000,
 595000,
 310000,
 380000,
 490000,
 975000,
 53000,
 540000,
 165000,
 625000,
 625000,
 335000,
 590000,
 395000,
 670000,
 130000,
 165000,
 325000,
 2490000,
 615000,
 390000,
 750000,
 680000,
 1250000,
 550000,
 290000,
 649000,
 300000,
 600000,
 425000,
 390000,
 365000,
 730000,
 750000,
 215000,
 370000,
 325000,
 399999,
 500000,
 410000,
 900000,
 600000,
 575000,
 350000,
 265000,
 575000,
 750000,
 2500000,
 510000,
 555000,
 335000,
 585000,
 850000,
 1850000,
 1200000,
 375000,
 280000,
 535000,
 995000,
 630000,
 145000,
 165000,
 650000,
 165000,
 170000,
 820000,
 1148000,
 1360000,
 375000,
 135000,
 1675000,
 180000,
 265000,
 590000,
 360000,
 4500000,
 750000,
 375000,
 575000,
 395003,
 360000,
 220000,
 295004,
 300000,
 225000,
 450000,
 625000,
 600000,
 770000,
 510000,
 410000,
 165000,
 335000,
 440000,
 850000,
 725000,
 560000,
 325000,
 600000,
 700000,
 440000,
 980000,
 765000,
 265000,
 340000,
 540000,
 270000,
 3700000,
 640000,
 1350000,
 525000,
 375000,
 390000,
 400000,
 440000,
 655000,
 450000,
 297000,
 1750000,
 1250000,
 275000,
 410000,
 475000,
 369000,
 700000,
 450000,
 565000,
 550000,
 220000,
 445000,
 220000,
 9700000,
 390000,
 485000,
 595000,
 290000,
 424000,
 250000,
 113000,
 320000,
 220000,
 395000,
 350000,
 665000,
 155000,
 310000,
 350000,
 400000,
 1100000,
 620000,
 4690000,
 699999,
 295000,
 425000,
 350000,
 775000,
 525000,
 225000,
 575000,
 450000,
 210000,
 265000,
 625000,
 470000,
 2700000,
 825000,
 1250000,
 1050000,
 325000,
 1000000,
 530000,
 260000,
 175000,
 410000,
 475000,
 525000,
 625000,
 1500000,
 375000,
 2490000,
 525000,
 370000,
 225000,
 1425000,
 1750000,
 249000,
 5390000,
 395000,
 135000,
 325000,
 210000,
 380000,
 170000,
 390000,
 410000,
 160000,
 845000,
 670000,
 960000,
 130000,
 520000,
 215000,
 225000,
 265000,
 115000,
 275000,
 265000,
 225000,
 190000,
 240000,
 1300000,
 490000,
 700000,
 8300000,
 1900000,
 1100000,
 2590000,
 540000,
 4200000,
 1200000,
 570000,
 570000,
 129000,
 1990000,
 1800000,
 1190000,
 375000,
 1650000,
 7950000,
 725000,
 1850000,
 315000,
 239000,
 785000,
 1650000,
 240000,
 7200000,
 229000,
 490000,
 155000,
 200000,
 175000,
 275000,
 365000,
 265000,
 265000,
 280000,
 220000,
 499999,
 5490000,
 1500000,
 189999,
 425000,
 370000,
 2290000,
 1899000,
 560000,
 620000,
 465000,
 375000,
 390000,
 650000,
 12800000,
 74000,
 2300000,
 6800000,
 825000,
 590000,
 460000,
 900000,
 220000,
 220000,
 740000,
 220000,
 285000,
 750000,
 690000,
 625000,
 360000,
 1265000,
 1200000,
 260000,
 370000,
 690000,
 425000,
 345000,
 350000,
 145000,
 250000,
 1500000,
 295000,
 360000,
 275000,
 460000,
 600000,
 450000,
 1310000,
 25000,
 230000,
 150000,
 300000,
 690000,
 675000,
 575000,
 1950000,
 220000,
 1500000,
 485000,
 765000,
 620000,
 230000,
 230000,
 650000,
 1275000,
 260000,
 370000,
 770000,
 795000,
 750000,
 750000,
 300000,
 180000,
 1140000,
 790000,
 390000,
 375000,
 235000,
 4350000,
 320000,
 495000,
 945000,
 310000,
 630000,
 1180000,
 635000,
 640000,
 350000,
 220000,
 2100000,
 1350000,
 600000,
 625000,
 199999,
 655000,
 575000,
 345000,
 390000,
 340000,
 445000,
 370000,
 820000,
 360000,
 2500000,
 1000000,
 390000,
 325000,
 395000,
 550000,
 205000,
 925000,
 225000,
 325000,
 1180000,
 899999,
 180000,
 575000,
 795000,
 35000,
 4790000,
 425000,
 4250000,
 285000,
 390000,
 415000,
 370000,
 380000,
 435000,
 765000,
 730000,
 15000,
 485000,
 595000,
 815000,
 499999,
 120000,
 850000,
 220000,
 370000,
 600000,
 55000,
 2275000,
 380000,
 825000,
 300000,
 800000,
 675000,
 7990000,
 349000,
 395000,
 675000,
 5590000,
 310000,
 155000,
 250000,
 159000,
 140000,
 415000,
 560000,
 425000,
 1380000,
 255000,
 210000,
 90000,
 875000,
 750000,
 1000000,
 650000,
 500000,
 1075000,
 295000,
 245000,
 300000,
 595000,
 950000,
 150000,
 300000]

In [152]:
#Fetching data from olx for Year

for y6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Year_6.append(y6.text.split('-')[0])

In [153]:
#Converting the column into integer type

for i in range(0, len(Year_6)):
    Year_6[i] = int(Year_6[i])

In [154]:
#Printing after conversion

Year_6

[2020,
 2018,
 2014,
 2012,
 2009,
 2014,
 2013,
 2010,
 2009,
 2011,
 2014,
 2003,
 2015,
 2011,
 2011,
 2015,
 2018,
 2011,
 2013,
 2007,
 2012,
 2018,
 2017,
 2014,
 2012,
 2012,
 2010,
 2013,
 2016,
 2012,
 2014,
 2011,
 2015,
 2016,
 2016,
 2014,
 2017,
 2014,
 2010,
 2011,
 2014,
 2016,
 2009,
 2012,
 2013,
 2014,
 2013,
 2017,
 2009,
 2014,
 2017,
 2016,
 2017,
 2011,
 2008,
 2008,
 2018,
 2018,
 2014,
 2017,
 2007,
 2007,
 2015,
 2012,
 2011,
 2018,
 2017,
 2017,
 2010,
 2018,
 2011,
 2015,
 2008,
 2012,
 2013,
 2017,
 2012,
 2016,
 2013,
 2019,
 2017,
 2009,
 2010,
 2011,
 2014,
 2009,
 2013,
 2019,
 2011,
 2013,
 2016,
 2016,
 2010,
 2012,
 2018,
 2015,
 2002,
 2012,
 2007,
 2014,
 2014,
 2014,
 2015,
 2016,
 2017,
 2016,
 2005,
 2009,
 2017,
 2016,
 2017,
 2017,
 2020,
 2016,
 2009,
 2013,
 2018,
 2008,
 2014,
 2012,
 2018,
 2015,
 2018,
 2017,
 2008,
 2016,
 2016,
 2009,
 2004,
 2013,
 2019,
 2019,
 2016,
 2010,
 2013,
 2015,
 2017,
 2012,
 2013,
 2013,
 2012,
 2017,
 2016,
 2014,
 2011,
 2011,
 2009,
 2017,
 2008,
 2018,
 2007,
 2006,
 2019,
 2005,
 2017,
 2018,
 2013,
 2011,
 2010,
 2006,
 2019,
 2007,
 2013,
 2016,
 2009,
 2016,
 2017,
 2014,
 2016,
 2016,
 2012,
 2011,
 2016,
 2013,
 2012,
 2014,
 2014,
 2013,
 2016,
 2016,
 2017,
 2008,
 2018,
 2019,
 2019,
 2010,
 2016,
 2011,
 2012,
 2016,
 2011,
 2019,
 2014,
 2013,
 2013,
 2015,
 2013,
 2016,
 2016,
 2012,
 2008,
 2011,
 2017,
 2018,
 2012,
 2016,
 2012,
 2011,
 2017,
 2011,
 2011,
 2015,
 2014,
 2010,
 2018,
 2014,
 2016,
 2013,
 2017,
 2014,
 2017,
 2021,
 2014,
 2018,
 2015,
 2013,
 2012,
 2010,
 2007,
 2013,
 2006,
 2018,
 2013,
 2016,
 2008,
 2011,
 2012,
 2018,
 2018,
 2019,
 2021,
 2005,
 2012,
 2016,
 2011,
 2014,
 2014,
 2008,
 2014,
 2011,
 2005,
 2009,
 2014,
 2014,
 2018,
 2020,
 2014,
 2018,
 2010,
 2011,
 2015,
 2010,
 2011,
 2018,
 2013,
 2017,
 2016,
 2009,
 2010,
 2013,
 2014,
 2013,
 2012,
 2016,
 2017,
 2015,
 2017,
 2016,
 2007,
 2011,
 2008,
 2011,
 2012,
 2014,
 2011,
 2014,
 2013,
 2011,
 2019,
 2007,
 2018,
 2014,
 2015,
 2016,
 2013,
 2011,
 2014,
 2013,
 2011,
 2010,
 2013,
 2013,
 2018,
 2019,
 2020,
 2019,
 2016,
 2018,
 2016,
 2016,
 2018,
 2015,
 2008,
 2013,
 2010,
 2012,
 2010,
 2020,
 2019,
 2018,
 2013,
 2011,
 2012,
 2011,
 2013,
 2010,
 2018,
 2010,
 2015,
 2008,
 2004,
 2012,
 2013,
 2018,
 2012,
 2016,
 2010,
 2005,
 2015,
 2020,
 2014,
 2011,
 2019,
 2018,
 2019,
 2019,
 2018,
 2019,
 2018,
 2010,
 2014,
 2019,
 2015,
 2001,
 2015,
 2017,
 2011,
 2018,
 2018,
 2019,
 2017,
 2017,
 2009,
 2009,
 2012,
 2017,
 2017,
 2016,
 2012,
 2019,
 2016,
 2010,
 2016,
 2014,
 2010,
 2010,
 2009,
 2005,
 2008,
 2011,
 2011,
 2011,
 2011,
 2014,
 2016,
 2012,
 2018,
 2017,
 2012,
 2007,
 2010,
 2013,
 2008,
 2009,
 2014,
 2017,
 2017,
 2014,
 2017,
 2017,
 2009,
 2009,
 2013,
 2012,
 2009,
 2016,
 2016,
 2018,
 2018,
 2018,
 2009,
 2016,
 2020,
 2020,
 2013,
 2011,
 2008,
 2018,
 2012,
 2014,
 2017,
 2016,
 2015,
 2019,
 2017,
 2016,
 2012,
 2016,
 2015,
 2011,
 2019,
 2019,
 2006,
 2018,
 2016,
 2016,
 2012,
 2011,
 2009,
 2014,
 2018,
 2014,
 2012,
 2010,
 2013,
 2016,
 2016,
 2013,
 2008,
 2012,
 2010,
 2011,
 2012,
 2010,
 2007,
 2016,
 2018,
 2014,
 2020,
 2013,
 2019,
 2014,
 2018,
 2013,
 2018,
 2017,
 2015,
 2016,
 2015,
 2021,
 2015,
 2016,
 2016,
 2014,
 2006,
 2015,
 2017,
 2018,
 2012,
 2002,
 2012,
 2018,
 2018,
 2012,
 2010,
 2017,
 2018,
 2012,
 2011,
 2015,
 2019,
 2013,
 2007,
 2006,
 2008,
 2017,
 2013,
 2015,
 2016,
 2014,
 2012,
 2009,
 2010,
 2019,
 2013,
 2018,
 2017,
 2016,
 2019,
 2016,
 2009,
 2012,
 2018,
 2019,
 2002,
 2007]

In [155]:
#Fetching data from olx for Km used, Company, Location, Date of posting

for k6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Km_6.append(k6.text.split('-')[1])
for c6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[2]"):
    Company_6.append(c6.text)
for l6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]"):
    Location_6.append(l6.text)
for d6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]/span"):
    Date_6.append(d6.text)

In [156]:
#Making a dataframe named Cars storing 500 data into that

CARS6=pd.DataFrame({})
CARS6['PRICE']=Price_6[0:500]
CARS6['YEAR']=Year_6[0:500]
CARS6['KM']=Km_6[0:500]
CARS6['COMPANY']=Company_6[0:500]
CARS6['LOCATION']=Location_6[0:500]
CARS6['POSTED-DATE']=Date_6[0:500]

In [157]:
#Printing the dataframe

CARS6

,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE
0,6800000,2020,"20,000 km",BMW X4,Mount Road\nJan 09,Jan 09
1,710000,2018,"76,000 km",Mahindra Xylo,Nungambakkam\nNov 30,Nov 30
2,775000,2014,"174,000 km",Mahindra XUV500,Perambur\n3 days ago,3 days ago
3,275000,2012,"30,000 km",Chevrolet Optra Magnum,Chennai Central\n2 days ago,2 days ago
4,350000,2009,"71,600 km",Toyota Corolla Altis,Choolaimedu RBI Staff Quarters\n6 days ago,6 days ago
...,...,...,...,...,...,...
495,140000,2017,"119,000 km",Tata Indica Ev2,Chennai Central\nYesterday,Yesterday
496,415000,2013,"68,000 km",Honda City,Nungambakkam\nYesterday,Yesterday
497,560000,2015,"480,003 km",Maruti Suzuki Swift,T Nagar Dharmapuram\nYesterday,Yesterday
498,425000,2016,"65,000 km",Maruti Suzuki Celerio,Nungambakkam\nYesterday,Yesterday
499,1380000,2014,"90,000 km",Skoda Superb,Virugambakkam\nJan 15,Jan 15

In [158]:
#Getting the information about the dataset

CARS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRICE        500 non-null    int64
 1   YEAR         500 non-null    int64
 2   KM           500 non-null    object
 3   COMPANY      500 non-null    object
 4   LOCATION     500 non-null    object
 5   POSTED-DATE  500 non-null    object
dtypes: int64(2), object(4)
memory usage: 23.6+ KB

In [159]:
driver6.close()

# 2998 IN TOTAL NOW

In [160]:
#Creating an instance of the chrome driver to get to the url

driver6 = webdriver.Chrome(r'E:/CHROME-DRIVER/chromedriver_win32/chromedriver.exe')

In [161]:
#Getting into the website

driver6.get('https://www.olx.in/en-in/cars_c84')

In [162]:
#Creating empty lists so that we can fetch the data

Price_6=[]
Year_6=[]
Km_6=[]
Company_6=[]
Location_6=[]
Date_6=[]

In [163]:
#Fetching the data from olx for Price

for p6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/span"):
    Price_6.append(p6.text.replace("â‚¹","").replace(",",""))

In [164]:
Price_6

[' 1950000',
 ' 275000',
 ' 1350000',
 ' 545000',
 ' 475000',
 ' 475000',
 ' 475000',
 ' 4900000',
 ' 511000',
 ' 399999',
 ' 275000',
 ' 159013',
 ' 399000',
 ' 475000',
 ' 325000',
 ' 475000',
 ' 270000',
 ' 325000',
 ' 1950000',
 ' 970000',
 ' 1490000',
 ' 525000',
 ' 165000',
 ' 1935000',
 ' 555000',
 ' 311000',
 ' 835000',
 ' 1090000',
 ' 865000',
 ' 635000',
 ' 1600000',
 ' 625000',
 ' 970000',
 ' 260000',
 ' 710000',
 ' 499999',
 ' 969000',
 ' 395000',
 ' 374000',
 ' 199000',
 ' 925000',
 ' 1390000',
 ' 215000',
 ' 185000',
 ' 250000',
 ' 270000',
 ' 299000',
 ' 165000',
 ' 699000',
 ' 510000',
 ' 1749000',
 ' 425000',
 ' 435000',
 ' 575000',
 ' 1365000',
 ' 245000',
 ' 499000',
 ' 525000',
 ' 470000',
 ' 400000',
 ' 700000',
 ' 5500000',
 ' 135000',
 ' 200000',
 ' 300000',
 ' 360000',
 ' 230000',
 ' 750000',
 ' 190000',
 ' 580000',
 ' 445000',
 ' 395000',
 ' 260000',
 ' 555000',
 ' 500000',
 ' 53453',
 ' 390000',
 ' 525000',
 ' 225000',
 ' 815000',
 ' 500000',
 ' 935000',
 ' 159999',
 ' 575000',
 ' 1375000',
 ' 678000',
 ' 379999',
 ' 240000',
 ' 100000',
 ' 515000',
 ' 850000',
 ' 95000',
 ' 1691000',
 ' 620000',
 ' 295000',
 ' 160000',
 ' 300000',
 ' 120000',
 ' 544900',
 ' 399999',
 ' 525000',
 ' 875000',
 ' 495000',
 ' 775000',
 ' 5700000',
 ' 595000',
 ' 255000',
 ' 900000',
 ' 270000',
 ' 490000',
 ' 6200000',
 ' 790000',
 ' 300000',
 ' 360000',
 ' 115000',
 ' 345000',
 ' 2060000',
 ' 875000',
 ' 850000',
 ' 375000',
 ' 370000',
 ' 750000',
 ' 4500000',
 ' 135000',
 ' 3249000',
 ' 295000',
 ' 188000',
 ' 461000',
 ' 365000',
 ' 1030000',
 ' 480000',
 ' 115000',
 ' 70000',
 ' 915000',
 ' 450000',
 ' 2100000',
 ' 725000',
 ' 290000',
 ' 6000000',
 ' 170000',
 ' 160000',
 ' 235000',
 ' 500000',
 ' 155000',
 ' 850000',
 ' 625000',
 ' 225000',
 ' 680000',
 ' 1025000',
 ' 600000',
 ' 475000',
 ' 1065000',
 ' 90000',
 ' 510000',
 ' 655000',
 ' 410000',
 ' 185000',
 ' 721000',
 ' 660000',
 ' 349000',
 ' 875000',
 ' 250000',
 ' 845000',
 ' 2325000',
 ' 575000',
 ' 635000',
 ' 440000',
 ' 1500000',
 ' 625000',
 ' 325000',
 ' 790000',
 ' 149000',
 ' 145000',
 ' 500000',
 ' 1875000',
 ' 800000',
 ' 1350000',
 ' 1075000',
 ' 490000',
 ' 495000',
 ' 895000',
 ' 495000',
 ' 1025000',
 ' 731000',
 ' 475000',
 ' 440000',
 ' 425000',
 ' 850000',
 ' 665000',
 ' 300000',
 ' 550000',
 ' 775000',
 ' 260000',
 ' 340000',
 ' 540000',
 ' 445000',
 ' 515000',
 ' 640000',
 ' 1025000',
 ' 725000',
 ' 640000',
 ' 499000',
 ' 2390000',
 ' 655000',
 ' 890000',
 ' 325000',
 ' 500000',
 ' 360000',
 ' 499000',
 ' 560000',
 ' 695000',
 ' 2951000',
 ' 465000',
 ' 220000',
 ' 1590000',
 ' 605000',
 ' 290000',
 ' 699999',
 ' 345000',
 ' 565000',
 ' 745000',
 ' 3999999',
 ' 255000',
 ' 1181000',
 ' 295000',
 ' 365000',
 ' 750000',
 ' 195000',
 ' 299000',
 ' 325000',
 ' 765000',
 ' 650000',
 ' 400000',
 ' 200000',
 ' 1125000',
 ' 995000',
 ' 260000',
 ' 345000',
 ' 2000000',
 ' 325000',
 ' 890000',
 ' 965000',
 ' 158000',
 ' 1085000',
 ' 725000',
 ' 700000',
 ' 695000',
 ' 650000',
 ' 970000',
 ' 165000',
 ' 705500',
 ' 350000',
 ' 150000',
 ' 150000',
 ' 595000',
 ' 500000',
 ' 465000',
 ' 365000',
 ' 675000',
 ' 625000',
 ' 440000',
 ' 195000',
 ' 650000',
 ' 1666000',
 ' 180000',
 ' 290000',
 ' 145000',
 ' 675000',
 ' 2400000',
 ' 695000',
 ' 2650000',
 ' 351000',
 ' 675000',
 ' 550000',
 ' 120000',
 ' 50000',
 ' 315000',
 ' 390000',
 ' 690000',
 ' 195000',
 ' 300000',
 ' 51000',
 ' 2190000',
 ' 550000',
 ' 1525000',
 ' 82000',
 ' 1550000',
 ' 148000',
 ' 291000',
 ' 2150000',
 ' 349000',
 ' 160000',
 ' 274000',
 ' 825000',
 ' 470000',
 ' 300000',
 ' 160000',
 ' 210000',
 ' 545000',
 ' 290000',
 ' 270000',
 ' 515000',
 ' 900000',
 ' 80000',
 ' 285000',
 ' 395000',
 ' 175000',
 ' 249700',
 ' 1495000',
 ' 2850000',
 ' 630000',
 ' 350000',
 ' 275000',
 ' 55000',
 ' 400000',
 ' 460000',
 ' 130000',
 ' 710000',
 ' 2125000',
 ' 1275000',
 ' 130000',
 ' 949000',
 ' 525000',
 ' 165000',
 ' 825000',
 ' 310000',
 ' 775000',
 ' 220000',
 ' 690000',
 ' 8175000',
 ' 245000',
 ' 170000',
 ' 390000',
 ' 225000',
 ' 400000',
 ' 400000',
 ' 1700000',
 ' 700000',
 ' 180000',
 ' 425000',
 ' 175000',
 ' 515000',
 ' 250000',
 ' 825000',
 ' 170000',
 ' 300000',
 ' 151000',
 ' 150000',
 ' 139000',
 ' 510000',
 ' 421000',
 ' 310000',
 ' 125000',
 ' 95000',
 ' 200000',
 ' 65000',
 ' 175000',
 ' 450000',
 ' 230000',
 ' 2695000',
 ' 378000',
 ' 139000',
 ' 665000',
 ' 599999',
 ' 390000',
 ' 870000',
 ' 480000',
 ' 690000',
 ' 720000',
 ' 550000',
 ' 565000',
 ' 140000',
 ' 100000',
 ' 260000',
 ' 245000',
 ' 270000',
 ' 145000',
 ' 500000',
 ' 385000',
 ' 210000',
 ' 3000000',
 ' 370000',
 ' 365000',
 ' 130000',
 ' 1825000',
 ' 599999',
 ' 155000',
 ' 275000',
 ' 375000',
 ' 755000',
 ' 575000',
 ' 295000',
 ' 460000',
 ' 1248399',
 ' 385000',
 ' 300000',
 ' 280000',
 ' 200000',
 ' 285000',
 ' 180000',
 ' 43000',
 ' 130000',
 ' 460000',
 ' 55000',
 ' 450000',
 ' 685000',
 ' 480000',
 ' 220000',
 ' 1411111',
 ' 570000',
 ' 130000',
 ' 170000',
 ' 125000',
 ' 695000',
 ' 79000',
 ' 850000',
 ' 210000',
 ' 295000',
 ' 220000',
 ' 550000',
 ' 125000',
 ' 180000',
 ' 230000',
 ' 375000',
 ' 99000',
 ' 315000',
 ' 230000',
 ' 142533',
 ' 1395000',
 ' 675000',
 ' 525000',
 ' 210000',
 ' 250000',
 ' 330000',
 ' 530000',
 ' 851000',
 ' 575000',
 ' 390000',
 ' 190000',
 ' 430000',
 ' 695000',
 ' 385000',
 ' 110000',
 ' 920000',
 ' 260000',
 ' 649500',
 ' 5800000',
 ' 40000',
 ' 1250000',
 ' 850000',
 ' 550000',
 ' 200000',
 ' 650000',
 ' 310000',
 ' 1150000',
 ' 55000',
 ' 471000',
 ' 85000',
 ' 250000',
 ' 620000',
 ' 130000',
 ' 140000',
 ' 775000',
 ' 300000',
 ' 60000',
 ' 1350000',
 ' 125000',
 ' 490000',
 ' 1050000',
 ' 510000',
 ' 495000',
 ' 160000',
 ' 42000',
 ' 110000',
 ' 150000',
 ' 290000',
 ' 370000',
 ' 785000',
 ' 125000',
 ' 1975000',
 ' 180000',
 ' 241000',
 ' 227253',
 ' 700000',
 ' 1590000',
 ' 160000',
 ' 600000',
 ' 1700000',
 ' 200000',
 ' 1285000',
 ' 2150000',
 ' 130000',
 ' 750000',
 ' 195000',
 ' 1050000',
 ' 300000',
 ' 135000',
 ' 140000',
 ' 125000',
 ' 99000',
 ' 580000',
 ' 240000',
 ' 379000',
 ' 485000',
 ' 130000',
 ' 545000',
 ' 790000',
 ' 110000',
 ' 500000',
 ' 525000',
 ' 350000',
 ' 180000',
 ' 145000',
 ' 40000',
 ' 300000',
 ' 550000',
 ' 251253',
 ' 215000',
 ' 90000',
 ' 260000',
 ' 550000',
 ' 675000',
 ' 165000',
 ' 460000',
 ' 1065000',
 ' 7500000',
 ' 900000',
 ' 475000']

In [165]:
#Converting the column into integer type

for i in range(0, len(Price_6)):
    Price_6[i] = int(Price_6[i])

In [166]:
#Printing after conversion

Price_6

[1950000,
 275000,
 1350000,
 545000,
 475000,
 475000,
 475000,
 4900000,
 511000,
 399999,
 275000,
 159013,
 399000,
 475000,
 325000,
 475000,
 270000,
 325000,
 1950000,
 970000,
 1490000,
 525000,
 165000,
 1935000,
 555000,
 311000,
 835000,
 1090000,
 865000,
 635000,
 1600000,
 625000,
 970000,
 260000,
 710000,
 499999,
 969000,
 395000,
 374000,
 199000,
 925000,
 1390000,
 215000,
 185000,
 250000,
 270000,
 299000,
 165000,
 699000,
 510000,
 1749000,
 425000,
 435000,
 575000,
 1365000,
 245000,
 499000,
 525000,
 470000,
 400000,
 700000,
 5500000,
 135000,
 200000,
 300000,
 360000,
 230000,
 750000,
 190000,
 580000,
 445000,
 395000,
 260000,
 555000,
 500000,
 53453,
 390000,
 525000,
 225000,
 815000,
 500000,
 935000,
 159999,
 575000,
 1375000,
 678000,
 379999,
 240000,
 100000,
 515000,
 850000,
 95000,
 1691000,
 620000,
 295000,
 160000,
 300000,
 120000,
 544900,
 399999,
 525000,
 875000,
 495000,
 775000,
 5700000,
 595000,
 255000,
 900000,
 270000,
 490000,
 6200000,
 790000,
 300000,
 360000,
 115000,
 345000,
 2060000,
 875000,
 850000,
 375000,
 370000,
 750000,
 4500000,
 135000,
 3249000,
 295000,
 188000,
 461000,
 365000,
 1030000,
 480000,
 115000,
 70000,
 915000,
 450000,
 2100000,
 725000,
 290000,
 6000000,
 170000,
 160000,
 235000,
 500000,
 155000,
 850000,
 625000,
 225000,
 680000,
 1025000,
 600000,
 475000,
 1065000,
 90000,
 510000,
 655000,
 410000,
 185000,
 721000,
 660000,
 349000,
 875000,
 250000,
 845000,
 2325000,
 575000,
 635000,
 440000,
 1500000,
 625000,
 325000,
 790000,
 149000,
 145000,
 500000,
 1875000,
 800000,
 1350000,
 1075000,
 490000,
 495000,
 895000,
 495000,
 1025000,
 731000,
 475000,
 440000,
 425000,
 850000,
 665000,
 300000,
 550000,
 775000,
 260000,
 340000,
 540000,
 445000,
 515000,
 640000,
 1025000,
 725000,
 640000,
 499000,
 2390000,
 655000,
 890000,
 325000,
 500000,
 360000,
 499000,
 560000,
 695000,
 2951000,
 465000,
 220000,
 1590000,
 605000,
 290000,
 699999,
 345000,
 565000,
 745000,
 3999999,
 255000,
 1181000,
 295000,
 365000,
 750000,
 195000,
 299000,
 325000,
 765000,
 650000,
 400000,
 200000,
 1125000,
 995000,
 260000,
 345000,
 2000000,
 325000,
 890000,
 965000,
 158000,
 1085000,
 725000,
 700000,
 695000,
 650000,
 970000,
 165000,
 705500,
 350000,
 150000,
 150000,
 595000,
 500000,
 465000,
 365000,
 675000,
 625000,
 440000,
 195000,
 650000,
 1666000,
 180000,
 290000,
 145000,
 675000,
 2400000,
 695000,
 2650000,
 351000,
 675000,
 550000,
 120000,
 50000,
 315000,
 390000,
 690000,
 195000,
 300000,
 51000,
 2190000,
 550000,
 1525000,
 82000,
 1550000,
 148000,
 291000,
 2150000,
 349000,
 160000,
 274000,
 825000,
 470000,
 300000,
 160000,
 210000,
 545000,
 290000,
 270000,
 515000,
 900000,
 80000,
 285000,
 395000,
 175000,
 249700,
 1495000,
 2850000,
 630000,
 350000,
 275000,
 55000,
 400000,
 460000,
 130000,
 710000,
 2125000,
 1275000,
 130000,
 949000,
 525000,
 165000,
 825000,
 310000,
 775000,
 220000,
 690000,
 8175000,
 245000,
 170000,
 390000,
 225000,
 400000,
 400000,
 1700000,
 700000,
 180000,
 425000,
 175000,
 515000,
 250000,
 825000,
 170000,
 300000,
 151000,
 150000,
 139000,
 510000,
 421000,
 310000,
 125000,
 95000,
 200000,
 65000,
 175000,
 450000,
 230000,
 2695000,
 378000,
 139000,
 665000,
 599999,
 390000,
 870000,
 480000,
 690000,
 720000,
 550000,
 565000,
 140000,
 100000,
 260000,
 245000,
 270000,
 145000,
 500000,
 385000,
 210000,
 3000000,
 370000,
 365000,
 130000,
 1825000,
 599999,
 155000,
 275000,
 375000,
 755000,
 575000,
 295000,
 460000,
 1248399,
 385000,
 300000,
 280000,
 200000,
 285000,
 180000,
 43000,
 130000,
 460000,
 55000,
 450000,
 685000,
 480000,
 220000,
 1411111,
 570000,
 130000,
 170000,
 125000,
 695000,
 79000,
 850000,
 210000,
 295000,
 220000,
 550000,
 125000,
 180000,
 230000,
 375000,
 99000,
 315000,
 230000,
 142533,
 1395000,
 675000,
 525000,
 210000,
 250000,
 330000,
 530000,
 851000,
 575000,
 390000,
 190000,
 430000,
 695000,
 385000,
 110000,
 920000,
 260000,
 649500,
 5800000,
 40000,
 1250000,
 850000,
 550000,
 200000,
 650000,
 310000,
 1150000,
 55000,
 471000,
 85000,
 250000,
 620000,
 130000,
 140000,
 775000,
 300000,
 60000,
 1350000,
 125000,
 490000,
 1050000,
 510000,
 495000,
 160000,
 42000,
 110000,
 150000,
 290000,
 370000,
 785000,
 125000,
 1975000,
 180000,
 241000,
 227253,
 700000,
 1590000,
 160000,
 600000,
 1700000,
 200000,
 1285000,
 2150000,
 130000,
 750000,
 195000,
 1050000,
 300000,
 135000,
 140000,
 125000,
 99000,
 580000,
 240000,
 379000,
 485000,
 130000,
 545000,
 790000,
 110000,
 500000,
 525000,
 350000,
 180000,
 145000,
 40000,
 300000,
 550000,
 251253,
 215000,
 90000,
 260000,
 550000,
 675000,
 165000,
 460000,
 1065000,
 7500000,
 900000,
 475000]

In [167]:
#Fetching data from olx for Year

for y6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Year_6.append(y6.text.split('-')[0])

In [169]:
#Converting the column into integer type

for i in range(0, len(Year_6)):
    Year_6[i] = int(Year_6[i])

In [170]:
#Printing after conversion

Year_6

[2011,
 2013,
 2009,
 2016,
 2013,
 2013,
 2017,
 2017,
 2013,
 2011,
 2013,
 2006,
 2012,
 2017,
 2011,
 2015,
 2010,
 2010,
 2021,
 2016,
 2017,
 2015,
 2009,
 2020,
 2019,
 2016,
 2017,
 2015,
 2019,
 2014,
 2015,
 2017,
 2019,
 2012,
 2019,
 2013,
 2016,
 2013,
 2016,
 2008,
 2019,
 2014,
 2009,
 2018,
 2007,
 2007,
 2015,
 2010,
 2012,
 2014,
 2018,
 2017,
 2014,
 2012,
 2017,
 2010,
 2012,
 2014,
 2014,
 2013,
 1996,
 2019,
 2008,
 2009,
 2008,
 2017,
 2012,
 2021,
 2011,
 2016,
 2011,
 2011,
 2010,
 2011,
 2020,
 2009,
 2016,
 2009,
 2014,
 2013,
 2014,
 2016,
 2014,
 2016,
 2021,
 2014,
 2016,
 2012,
 2006,
 2015,
 2020,
 2008,
 2018,
 2019,
 2011,
 2007,
 2011,
 2007,
 2014,
 2012,
 2016,
 2019,
 2007,
 2016,
 2021,
 2018,
 2011,
 2019,
 2010,
 2020,
 2019,
 2018,
 2012,
 2015,
 2012,
 2014,
 2016,
 2018,
 2008,
 2014,
 2010,
 2019,
 2021,
 2004,
 2018,
 2019,
 2009,
 2018,
 2013,
 2019,
 2018,
 2011,
 2007,
 2019,
 2015,
 2015,
 2017,
 2009,
 2017,
 2004,
 2003,
 2013,
 2020,
 2011,
 2015,
 2013,
 2008,
 2020,
 2015,
 2015,
 2019,
 2019,
 2008,
 2014,
 2018,
 2013,
 2010,
 2011,
 2016,
 2014,
 2015,
 2007,
 2017,
 2014,
 2013,
 2017,
 2014,
 2017,
 2018,
 2017,
 2017,
 2008,
 2007,
 2018,
 2016,
 2018,
 2013,
 2019,
 2016,
 2016,
 2019,
 2014,
 2014,
 2016,
 2013,
 2017,
 2013,
 2009,
 2016,
 2009,
 2016,
 2017,
 2015,
 2016,
 2019,
 2010,
 2018,
 2017,
 2018,
 2015,
 2015,
 2013,
 2021,
 2016,
 2012,
 2018,
 2009,
 2016,
 2014,
 2016,
 2015,
 2018,
 2014,
 2015,
 2020,
 2017,
 2010,
 2017,
 2015,
 2016,
 2016,
 2017,
 2011,
 2012,
 2013,
 2013,
 2021,
 2012,
 2009,
 2014,
 2017,
 2018,
 2012,
 2010,
 2020,
 2015,
 2012,
 2010,
 2018,
 2012,
 2012,
 2018,
 2007,
 2020,
 2019,
 2021,
 2020,
 2020,
 2019,
 2006,
 2019,
 2012,
 2008,
 2016,
 2016,
 2013,
 2016,
 2007,
 2016,
 2013,
 2014,
 2005,
 2017,
 2021,
 2010,
 2015,
 2010,
 2013,
 2015,
 2018,
 2015,
 2017,
 2016,
 2018,
 2010,
 2003,
 2014,
 2013,
 2017,
 2013,
 2012,
 1999,
 2015,
 2016,
 2018,
 2005,
 2011,
 2016,
 2012,
 2018,
 2011,
 2010,
 2010,
 2019,
 2018,
 2012,
 2008,
 2017,
 2014,
 2012,
 2017,
 2009,
 2016,
 2008,
 2013,
 2013,
 2010,
 2011,
 2016,
 2016,
 2017,
 2014,
 2017,
 2021,
 2008,
 2014,
 2004,
 2019,
 2015,
 2021,
 2004,
 2014,
 2013,
 2017,
 2019,
 2017,
 2017,
 2010,
 2019,
 2019,
 2006,
 2016,
 2018,
 2011,
 2007,
 2006,
 2014,
 2017,
 2011,
 2018,
 2007,
 2017,
 2016,
 2019,
 2019,
 2006,
 2008,
 2010,
 2010,
 2012,
 2012,
 2012,
 2011,
 2004,
 2009,
 2004,
 2007,
 2016,
 2008,
 2017,
 2014,
 2007,
 2020,
 2015,
 2014,
 2018,
 2013,
 2013,
 2017,
 2016,
 2016,
 2015,
 2011,
 2008,
 2014,
 2010,
 2009,
 2009,
 2014,
 2012,
 2018,
 2011,
 2020,
 2009,
 2019,
 2014,
 2008,
 2014,
 2014,
 2015,
 2015,
 2013,
 2017,
 2018,
 2013,
 2014,
 2016,
 2007,
 2017,
 2009,
 2021,
 2009,
 2018,
 2017,
 2016,
 2020,
 2020,
 2007,
 2013,
 2014,
 2007,
 2011,
 2010,
 2018,
 2007,
 2017,
 2010,
 2015,
 2015,
 2013,
 2005,
 2011,
 2009,
 2011,
 2008,
 2013,
 2013,
 2008,
 2019,
 2017,
 2016,
 2009,
 2011,
 2014,
 2009,
 2010,
 2018,
 2013,
 2008,
 2020,
 2015,
 2009,
 2008,
 2011,
 2016,
 2013,
 2019,
 2020,
 2012,
 2015,
 2015,
 2009,
 2021,
 2012,
 2019,
 2004,
 2014,
 2008,
 2012,
 2018,
 2010,
 2010,
 2015,
 2007,
 2007,
 2018,
 2007,
 2016,
 2011,
 2015,
 2010,
 2016,
 2010,
 2008,
 2010,
 2016,
 2011,
 2012,
 2009,
 2019,
 2008,
 2015,
 2012,
 2018,
 2016,
 2013,
 2019,
 2015,
 2010,
 2012,
 2013,
 2006,
 2016,
 2003,
 2011,
 2019,
 2008,
 2008,
 2010,
 2012,
 2018,
 2010,
 2014,
 2014,
 2019,
 2018,
 2018,
 2007,
 2016,
 2017,
 2012,
 2012,
 2012,
 2021,
 1997,
 2017,
 2011,
 2007,
 2003,
 2010,
 2014,
 2017,
 2011,
 2018,
 2005,
 2019,
 2018,
 2014]

In [171]:
#Fetching data from olx for Km used, Company, Location, Date of posting

for k6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Km_6.append(k6.text.split('-')[1])
for c6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[2]"):
    Company_6.append(c6.text)
for l6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]"):
    Location_6.append(l6.text)
for d6 in driver6.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]/span"):
    Date_6.append(d6.text)

In [172]:
#Making a dataframe named Cars storing 500 data into that

CARS6=pd.DataFrame({})
CARS6['PRICE']=Price_6[0:500]
CARS6['YEAR']=Year_6[0:500]
CARS6['KM']=Km_6[0:500]
CARS6['COMPANY']=Company_6[0:500]
CARS6['LOCATION']=Location_6[0:500]
CARS6['POSTED-DATE']=Date_6[0:500]

In [173]:
#Printing the dataframe

CARS6

,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE
0,1950000,2011,"58,000 km",Mercedes-Benz CLS-Class,North Kalamassery\nDec 06,Dec 06
1,275000,2013,"60,000 km",Maruti Suzuki Wagon R,Brijlalpura\nJan 05,Jan 05
2,1350000,2009,"113,000 km",BMW X5,RS Puram\nDec 29,Dec 29
3,545000,2016,"23,000 km",Maruti Suzuki Baleno,Kalyan\nToday,Today
4,475000,2013,"75,000 km",Skoda Superb,Kalyan\nToday,Today
...,...,...,...,...,...,...
495,300000,2019,"10,470 km",Maruti Suzuki Alto 800,Peer Muchalla\nToday,Today
496,135000,2008,"119,000 km",Maruti Suzuki Alto,Omkar Nagar\nToday,Today
497,140000,2008,"106,706 km",Maruti Suzuki Omni,Attapur\nToday,Today
498,125000,2010,"100,000 km",Maruti Suzuki Alto,Daryapur MIDC\nToday,Today
499,99000,2012,"82,000 km",Tata Indigo Ecs,Mohammadpur Hayak\nToday,Today

In [174]:
#Getting the information abput the dataset

CARS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRICE        500 non-null    int64
 1   YEAR         500 non-null    int64
 2   KM           500 non-null    object
 3   COMPANY      500 non-null    object
 4   LOCATION     500 non-null    object
 5   POSTED-DATE  500 non-null    object
dtypes: int64(2), object(4)
memory usage: 23.6+ KB

In [175]:
driver6.close()

# 3498 IN TOTAL NOW

In [176]:
#Creating an instance of the chrome driver to get to the url

driver7 = webdriver.Chrome(r'E:/CHROME-DRIVER/chromedriver_win32/chromedriver.exe')

In [179]:
#Getting into the website

driver7.get('https://www.olx.in/en-in/lucknow_g4059306/cars_c84')

In [180]:
#Creating empty lists so that we can fetch the data

Price_7=[]
Year_7=[]
Km_7=[]
Company_7=[]
Location_7=[]
Date_7=[]

In [182]:
#Fetching the data from olx for Price

for p7 in driver7.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/span"):
    Price_7.append(p7.text.replace("â‚¹","").replace(",",""))

In [183]:
#Printing price

Price_7

[' 750000',
 ' 1700000',
 ' 4675000',
 ' 200000',
 ' 1800000',
 ' 190000',
 ' 1025000',
 ' 550000',
 ' 460000',
 ' 1050000',
 ' 1950000',
 ' 900000',
 ' 690000',
 ' 325000',
 ' 490000',
 ' 1350000',
 ' 750000',
 ' 375000',
 ' 775000',
 ' 1790000',
 ' 465000',
 ' 5500000',
 ' 6200000',
 ' 249000',
 ' 160000',
 ' 499000',
 ' 1075000',
 ' 585000',
 ' 625000',
 ' 290000',
 ' 220000',
 ' 315000',
 ' 2350000',
 ' 375000',
 ' 265000',
 ' 350000',
 ' 170000',
 ' 340000',
 ' 385000',
 ' 2750000',
 ' 530000',
 ' 225000',
 ' 4250000',
 ' 445000',
 ' 64000',
 ' 250000',
 ' 1270000',
 ' 120000',
 ' 745000',
 ' 290000',
 ' 775000',
 ' 950000',
 ' 3450000',
 ' 165000',
 ' 4950000',
 ' 62500',
 ' 295000',
 ' 285000',
 ' 3650000',
 ' 190000',
 ' 1550000',
 ' 1450000',
 ' 440000',
 ' 1950000',
 ' 590000',
 ' 315000',
 ' 625000',
 ' 700000',
 ' 235000',
 ' 375000',
 ' 380000',
 ' 265000',
 ' 1130000',
 ' 219000',
 ' 695000',
 ' 685000',
 ' 400000',
 ' 389000',
 ' 1790000',
 ' 1490000',
 ' 625000',
 ' 1375000',
 ' 585000',
 ' 1375000',
 ' 185000',
 ' 550000',
 ' 925000',
 ' 540000',
 ' 665000',
 ' 580000',
 ' 160000',
 ' 170000',
 ' 690000',
 ' 4850000',
 ' 4100000',
 ' 225000',
 ' 275000',
 ' 285000',
 ' 195000',
 ' 350000',
 ' 575000',
 ' 700000',
 ' 425000',
 ' 525000',
 ' 475000',
 ' 350000',
 ' 875000',
 ' 850000',
 ' 790000',
 ' 185000',
 ' 3350000',
 ' 695000',
 ' 8500000',
 ' 120000',
 ' 425000',
 ' 600000',
 ' 275000',
 ' 270000',
 ' 315000',
 ' 365000',
 ' 525000',
 ' 5400000',
 ' 3350000',
 ' 890000',
 ' 386000',
 ' 210000',
 ' 775000',
 ' 475000',
 ' 155000',
 ' 285000',
 ' 6300000',
 ' 216000',
 ' 350000',
 ' 110000',
 ' 375000',
 ' 590000',
 ' 520000',
 ' 450000',
 ' 625000',
 ' 360000',
 ' 245000',
 ' 855000',
 ' 460000',
 ' 450000',
 ' 135000',
 ' 265000',
 ' 195000',
 ' 145000',
 ' 125000',
 ' 975000',
 ' 690000',
 ' 325000',
 ' 740000',
 ' 425000',
 ' 310000',
 ' 635000',
 ' 435000',
 ' 540000',
 ' 1575000',
 ' 725000',
 ' 675000',
 ' 590000',
 ' 610000',
 ' 640000',
 ' 9500000',
 ' 490000',
 ' 1690000',
 ' 650000',
 ' 835000',
 ' 93000',
 ' 425000',
 ' 549000',
 ' 620000',
 ' 445000',
 ' 775000',
 ' 2650000',
 ' 2475000',
 ' 225000',
 ' 285000',
 ' 685000',
 ' 310000',
 ' 235000',
 ' 225000',
 ' 365000',
 ' 140000',
 ' 225000',
 ' 215000',
 ' 235000',
 ' 355000',
 ' 725000',
 ' 495000',
 ' 490000',
 ' 800000',
 ' 395000',
 ' 295000',
 ' 1175000',
 ' 785000',
 ' 825000',
 ' 400000',
 ' 675000',
 ' 2875000',
 ' 575000',
 ' 850000',
 ' 365000',
 ' 300000',
 ' 680000',
 ' 475000',
 ' 425000',
 ' 345000',
 ' 295000',
 ' 710000',
 ' 525000',
 ' 5500000',
 ' 1500000',
 ' 180000',
 ' 625000',
 ' 185000',
 ' 180000',
 ' 1800000',
 ' 345000',
 ' 985000',
 ' 985000',
 ' 900000',
 ' 470000',
 ' 935000',
 ' 635000',
 ' 1025000',
 ' 495000',
 ' 1150000',
 ' 255000',
 ' 585000',
 ' 475000',
 ' 1000000',
 ' 150000',
 ' 390000',
 ' 410000',
 ' 235000',
 ' 280000',
 ' 1000000',
 ' 725000',
 ' 12300000',
 ' 1290000',
 ' 850000',
 ' 590000',
 ' 199000',
 ' 300000',
 ' 220000',
 ' 440000',
 ' 90000',
 ' 355000',
 ' 275000',
 ' 169000',
 ' 325000',
 ' 150000',
 ' 210000',
 ' 520000',
 ' 500000',
 ' 159000',
 ' 615000',
 ' 265000',
 ' 395000',
 ' 1600000',
 ' 395000',
 ' 280000',
 ' 2100000',
 ' 555000',
 ' 90000',
 ' 965000',
 ' 435000',
 ' 499000',
 ' 3900000',
 ' 5600000',
 ' 9500000',
 ' 5600000',
 ' 5800000',
 ' 1100000',
 ' 465000',
 ' 100000',
 ' 425000',
 ' 52000',
 ' 575000',
 ' 400000',
 ' 750000',
 ' 6300000',
 ' 5000000',
 ' 750000',
 ' 550000',
 ' 290000',
 ' 550000',
 ' 490000',
 ' 650000',
 ' 525000',
 ' 360000',
 ' 1410000',
 ' 275000',
 ' 250000',
 ' 250000',
 ' 700000',
 ' 1025000',
 ' 12500000',
 ' 770000',
 ' 235000',
 ' 325000',
 ' 160000',
 ' 75000',
 ' 360000',
 ' 450000',
 ' 499000',
 ' 825000',
 ' 240000',
 ' 375000',
 ' 650000',
 ' 490000',
 ' 310000',
 ' 175000',
 ' 4650000',
 ' 7300000',
 ' 275000',
 ' 1299999',
 ' 475000',
 ' 250000',
 ' 290000',
 ' 350000',
 ' 240000',
 ' 425000',
 ' 699000',
 ' 590000',
 ' 399000',
 ' 365000',
 ' 250000',
 ' 130000',
 ' 225000',
 ' 225000',
 ' 220000',
 ' 450000',
 ' 735000',
 ' 425000',
 ' 199000',
 ' 425000',
 ' 425000',
 ' 740000',
 ' 475000',
 ' 775000',
 ' 515000',
 ' 825000',
 ' 395000',
 ' 1310000',
 ' 220000',
 ' 310000',
 ' 865000',
 ' 238000',
 ' 275000',
 ' 575000',
 ' 360000',
 ' 240000',
 ' 495000',
 ' 675000',
 ' 510000',
 ' 520000',
 ' 500000',
 ' 750000',
 ' 360000',
 ' 420000',
 ' 915000',
 ' 495000',
 ' 500000',
 ' 350000',
 ' 475000',
 ' 500000',
 ' 245000',
 ' 495000',
 ' 495000',
 ' 475000',
 ' 175000',
 ' 625000',
 ' 550000',
 ' 4000000',
 ' 195000',
 ' 400000',
 ' 150000',
 ' 450000',
 ' 160000',
 ' 69000',
 ' 190000',
 ' 146000',
 ' 285000',
 ' 205000',
 ' 1039000',
 ' 165000',
 ' 5650000',
 ' 265000',
 ' 295000',
 ' 250000',
 ' 115000',
 ' 2700000',
 ' 2950000',
 ' 235000',
 ' 360000',
 ' 575000',
 ' 575000',
 ' 62000',
 ' 6950000',
 ' 350000',
 ' 420000',
 ' 1490000',
 ' 1490000',
 ' 700000',
 ' 245000',
 ' 1000000',
 ' 795000',
 ' 245000',
 ' 1500000',
 ' 775000',
 ' 225000',
 ' 685000',
 ' 475000',
 ' 699000',
 ' 300000',
 ' 2250000',
 ' 50000',
 ' 265000',
 ' 465000',
 ' 42000',
 ' 190000',
 ' 695000',
 ' 175000',
 ' 2250000',
 ' 2850000',
 ' 300000',
 ' 395000',
 ' 825000',
 ' 5600000',
 ' 5100000',
 ' 160000',
 ' 6200000',
 ' 5500000',
 ' 700000',
 ' 675000',
 ' 180000',
 ' 2000000',
 ' 132000',
 ' 350000',
 ' 729999',
 ' 565000',
 ' 250000',
 ' 650000',
 ' 425000',
 ' 725000',
 ' 13900000',
 ' 221000',
 ' 290000',
 ' 330000',
 ' 665000',
 ' 275000',
 ' 1475000',
 ' 2500000',
 ' 295000',
 ' 775000',
 ' 120000',
 ' 500000',
 ' 250000',
 ' 225000',
 ' 850000',
 ' 140000',
 ' 1070000',
 ' 445000',
 ' 790000',
 ' 325000',
 ' 680000',
 ' 350000',
 ' 585000',
 ' 235000',
 ' 1890000',
 ' 160000',
 ' 450000',
 ' 275000',
 ' 225000',
 ' 230000',
 ' 900000',
 ' 280000',
 ' 490000',
 ' 725000',
 ' 250000',
 ' 575000',
 ' 325000',
 ' 600000',
 ' 550000',
 ' 225000',
 ' 1450000',
 ' 3900000',
 ' 85000',
 ' 350000',
 ' 2650000',
 ' 1450000',
 ' 3100000',
 ' 290000',
 ' 148000',
 ' 230000',
 ' 1890000',
 ' 4600000',
 ' 490000',
 ' 750000',
 ' 695000',
 ' 265000',
 ' 510000',
 ' 200000',
 ' 1750000',
 ' 3375000',
 ' 750000',
 ' 4650000',
 ' 190000',
 ' 350000',
 ' 1750000',
 ' 2000000',
 ' 245000',
 ' 1000000',
 ' 1750000',
 ' 625000',
 ' 2975000',
 ' 875000',
 ' 350000',
 ' 3900000',
 ' 6500000',
 ' 3750000',
 ' 2450000',
 ' 2600000',
 ' 4200000',
 ' 4200000',
 ' 2400000',
 ' 190000',
 ' 3400000',
 ' 650000',
 ' 2900000',
 ' 5500000',
 ' 190000',
 ' 2750000',
 ' 2290000',
 ' 1400000',
 ' 2350000',
 ' 850000',
 ' 630000']

In [184]:
#Converting the column into integer type

for i in range(0, len(Price_7)):
    Price_7[i] = int(Price_7[i])

In [185]:
#Printing after conversion

Price_7

[750000,
 1700000,
 4675000,
 200000,
 1800000,
 190000,
 1025000,
 550000,
 460000,
 1050000,
 1950000,
 900000,
 690000,
 325000,
 490000,
 1350000,
 750000,
 375000,
 775000,
 1790000,
 465000,
 5500000,
 6200000,
 249000,
 160000,
 499000,
 1075000,
 585000,
 625000,
 290000,
 220000,
 315000,
 2350000,
 375000,
 265000,
 350000,
 170000,
 340000,
 385000,
 2750000,
 530000,
 225000,
 4250000,
 445000,
 64000,
 250000,
 1270000,
 120000,
 745000,
 290000,
 775000,
 950000,
 3450000,
 165000,
 4950000,
 62500,
 295000,
 285000,
 3650000,
 190000,
 1550000,
 1450000,
 440000,
 1950000,
 590000,
 315000,
 625000,
 700000,
 235000,
 375000,
 380000,
 265000,
 1130000,
 219000,
 695000,
 685000,
 400000,
 389000,
 1790000,
 1490000,
 625000,
 1375000,
 585000,
 1375000,
 185000,
 550000,
 925000,
 540000,
 665000,
 580000,
 160000,
 170000,
 690000,
 4850000,
 4100000,
 225000,
 275000,
 285000,
 195000,
 350000,
 575000,
 700000,
 425000,
 525000,
 475000,
 350000,
 875000,
 850000,
 790000,
 185000,
 3350000,
 695000,
 8500000,
 120000,
 425000,
 600000,
 275000,
 270000,
 315000,
 365000,
 525000,
 5400000,
 3350000,
 890000,
 386000,
 210000,
 775000,
 475000,
 155000,
 285000,
 6300000,
 216000,
 350000,
 110000,
 375000,
 590000,
 520000,
 450000,
 625000,
 360000,
 245000,
 855000,
 460000,
 450000,
 135000,
 265000,
 195000,
 145000,
 125000,
 975000,
 690000,
 325000,
 740000,
 425000,
 310000,
 635000,
 435000,
 540000,
 1575000,
 725000,
 675000,
 590000,
 610000,
 640000,
 9500000,
 490000,
 1690000,
 650000,
 835000,
 93000,
 425000,
 549000,
 620000,
 445000,
 775000,
 2650000,
 2475000,
 225000,
 285000,
 685000,
 310000,
 235000,
 225000,
 365000,
 140000,
 225000,
 215000,
 235000,
 355000,
 725000,
 495000,
 490000,
 800000,
 395000,
 295000,
 1175000,
 785000,
 825000,
 400000,
 675000,
 2875000,
 575000,
 850000,
 365000,
 300000,
 680000,
 475000,
 425000,
 345000,
 295000,
 710000,
 525000,
 5500000,
 1500000,
 180000,
 625000,
 185000,
 180000,
 1800000,
 345000,
 985000,
 985000,
 900000,
 470000,
 935000,
 635000,
 1025000,
 495000,
 1150000,
 255000,
 585000,
 475000,
 1000000,
 150000,
 390000,
 410000,
 235000,
 280000,
 1000000,
 725000,
 12300000,
 1290000,
 850000,
 590000,
 199000,
 300000,
 220000,
 440000,
 90000,
 355000,
 275000,
 169000,
 325000,
 150000,
 210000,
 520000,
 500000,
 159000,
 615000,
 265000,
 395000,
 1600000,
 395000,
 280000,
 2100000,
 555000,
 90000,
 965000,
 435000,
 499000,
 3900000,
 5600000,
 9500000,
 5600000,
 5800000,
 1100000,
 465000,
 100000,
 425000,
 52000,
 575000,
 400000,
 750000,
 6300000,
 5000000,
 750000,
 550000,
 290000,
 550000,
 490000,
 650000,
 525000,
 360000,
 1410000,
 275000,
 250000,
 250000,
 700000,
 1025000,
 12500000,
 770000,
 235000,
 325000,
 160000,
 75000,
 360000,
 450000,
 499000,
 825000,
 240000,
 375000,
 650000,
 490000,
 310000,
 175000,
 4650000,
 7300000,
 275000,
 1299999,
 475000,
 250000,
 290000,
 350000,
 240000,
 425000,
 699000,
 590000,
 399000,
 365000,
 250000,
 130000,
 225000,
 225000,
 220000,
 450000,
 735000,
 425000,
 199000,
 425000,
 425000,
 740000,
 475000,
 775000,
 515000,
 825000,
 395000,
 1310000,
 220000,
 310000,
 865000,
 238000,
 275000,
 575000,
 360000,
 240000,
 495000,
 675000,
 510000,
 520000,
 500000,
 750000,
 360000,
 420000,
 915000,
 495000,
 500000,
 350000,
 475000,
 500000,
 245000,
 495000,
 495000,
 475000,
 175000,
 625000,
 550000,
 4000000,
 195000,
 400000,
 150000,
 450000,
 160000,
 69000,
 190000,
 146000,
 285000,
 205000,
 1039000,
 165000,
 5650000,
 265000,
 295000,
 250000,
 115000,
 2700000,
 2950000,
 235000,
 360000,
 575000,
 575000,
 62000,
 6950000,
 350000,
 420000,
 1490000,
 1490000,
 700000,
 245000,
 1000000,
 795000,
 245000,
 1500000,
 775000,
 225000,
 685000,
 475000,
 699000,
 300000,
 2250000,
 50000,
 265000,
 465000,
 42000,
 190000,
 695000,
 175000,
 2250000,
 2850000,
 300000,
 395000,
 825000,
 5600000,
 5100000,
 160000,
 6200000,
 5500000,
 700000,
 675000,
 180000,
 2000000,
 132000,
 350000,
 729999,
 565000,
 250000,
 650000,
 425000,
 725000,
 13900000,
 221000,
 290000,
 330000,
 665000,
 275000,
 1475000,
 2500000,
 295000,
 775000,
 120000,
 500000,
 250000,
 225000,
 850000,
 140000,
 1070000,
 445000,
 790000,
 325000,
 680000,
 350000,
 585000,
 235000,
 1890000,
 160000,
 450000,
 275000,
 225000,
 230000,
 900000,
 280000,
 490000,
 725000,
 250000,
 575000,
 325000,
 600000,
 550000,
 225000,
 1450000,
 3900000,
 85000,
 350000,
 2650000,
 1450000,
 3100000,
 290000,
 148000,
 230000,
 1890000,
 4600000,
 490000,
 750000,
 695000,
 265000,
 510000,
 200000,
 1750000,
 3375000,
 750000,
 4650000,
 190000,
 350000,
 1750000,
 2000000,
 245000,
 1000000,
 1750000,
 625000,
 2975000,
 875000,
 350000,
 3900000,
 6500000,
 3750000,
 2450000,
 2600000,
 4200000,
 4200000,
 2400000,
 190000,
 3400000,
 650000,
 2900000,
 5500000,
 190000,
 2750000,
 2290000,
 1400000,
 2350000,
 850000,
 630000]

In [186]:
#Fetching data from olx for Year

for y7 in driver7.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Year_7.append(y7.text.split('-')[0])

In [195]:
#Converting the column into integer type

for i in range(0, len(Year_7)):
    Year_7[i] = float(Year_7[i])

In [196]:
#Printing the Year

Year_7

[1996.0,
 2016.0,
 2018.0,
 2016.0,
 2014.0,
 2011.0,
 2018.0,
 2014.0,
 2018.0,
 2020.0,
 2021.0,
 2015.0,
 2016.0,
 2017.0,
 2015.0,
 2013.0,
 2016.0,
 2018.0,
 2017.0,
 2012.0,
 2012.0,
 2019.0,
 2019.0,
 2011.0,
 2011.0,
 2015.0,
 2017.0,
 2018.0,
 2015.0,
 2016.0,
 2009.0,
 2013.0,
 2020.0,
 2016.0,
 2011.0,
 2015.0,
 2011.0,
 2012.0,
 2014.0,
 2017.0,
 2015.0,
 2015.0,
 2012.0,
 2016.0,
 2007.0,
 2017.0,
 2014.0,
 2015.0,
 2018.0,
 2011.0,
 2015.0,
 2011.0,
 2019.0,
 2011.0,
 2020.0,
 2007.0,
 2013.0,
 2017.0,
 2018.0,
 2010.0,
 2019.0,
 2020.0,
 2014.0,
 2018.0,
 2020.0,
 2008.0,
 2014.0,
 2016.0,
 2009.0,
 2014.0,
 2017.0,
 2017.0,
 2016.0,
 2010.0,
 2015.0,
 2017.0,
 2016.0,
 2014.0,
 2013.0,
 2013.0,
 2016.0,
 2012.0,
 2016.0,
 2012.0,
 2010.0,
 2014.0,
 2020.0,
 2015.0,
 2017.0,
 2015.0,
 2007.0,
 2006.0,
 2014.0,
 2019.0,
 2019.0,
 2006.0,
 2015.0,
 2014.0,
 2011.0,
 2017.0,
 2018.0,
 2010.0,
 2016.0,
 2014.0,
 2013.0,
 2015.0,
 2020.0,
 2015.0,
 2015.0,
 2011.0,
 2014.0,
 2017.0,
 2017.0,
 2008.0,
 2015.0,
 2017.0,
 2012.0,
 2011.0,
 2015.0,
 2013.0,
 2017.0,
 2015.0,
 2017.0,
 2011.0,
 2014.0,
 2014.0,
 2019.0,
 2015.0,
 2011.0,
 2013.0,
 2018.0,
 2010.0,
 2013.0,
 2010.0,
 2012.0,
 2016.0,
 2017.0,
 2015.0,
 2017.0,
 2013.0,
 2012.0,
 2011.0,
 2015.0,
 2012.0,
 2010.0,
 2014.0,
 2009.0,
 2008.0,
 2010.0,
 2019.0,
 2017.0,
 2012.0,
 2018.0,
 2012.0,
 2018.0,
 2017.0,
 2014.0,
 2016.0,
 2014.0,
 2017.0,
 2018.0,
 2013.0,
 2017.0,
 2018.0,
 2020.0,
 2015.0,
 2020.0,
 2017.0,
 2018.0,
 2005.0,
 2015.0,
 2017.0,
 2014.0,
 2011.0,
 2020.0,
 2016.0,
 2017.0,
 2013.0,
 2016.0,
 2018.0,
 2017.0,
 2015.0,
 2015.0,
 2015.0,
 2008.0,
 2014.0,
 2015.0,
 2012.0,
 2018.0,
 2017.0,
 2014.0,
 2017.0,
 2020.0,
 2016.0,
 2016.0,
 2018.0,
 2018.0,
 2020.0,
 2015.0,
 2017.0,
 2016.0,
 2016.0,
 2017.0,
 2013.0,
 2014.0,
 2018.0,
 2013.0,
 2013.0,
 2012.0,
 2010.0,
 2017.0,
 2015.0,
 2018.0,
 2018.0,
 2014.0,
 2017.0,
 2011.0,
 2010.0,
 2018.0,
 2005.0,
 2013.0,
 2016.0,
 2011.0,
 2014.0,
 2015.0,
 2016.0,
 2014.0,
 2015.0,
 2015.0,
 2012.0,
 2016.0,
 2014.0,
 2014.0,
 2008.0,
 2017.0,
 2012.0,
 2017.0,
 2011.0,
 2014.0,
 2018.0,
 2019.0,
 2014.0,
 2018.0,
 2018.0,
 2011.0,
 2011.0,
 2016.0,
 2015.0,
 2008.0,
 2009.0,
 2013.0,
 2009.0,
 2012.0,
 2014.0,
 2006.0,
 2015.0,
 2021.0,
 2007.0,
 2014.0,
 2012.0,
 2012.0,
 2018.0,
 2012.0,
 2011.0,
 2013.0,
 2017.0,
 2007.0,
 2020.0,
 2017.0,
 2015.0,
 2018.0,
 2017.0,
 2018.0,
 2019.0,
 2020.0,
 2012.0,
 2007.0,
 2008.0,
 2009.0,
 2003.0,
 2016.0,
 2011.0,
 2017.0,
 2020.0,
 2017.0,
 2017.0,
 2016.0,
 2011.0,
 2014.0,
 2016.0,
 2016.0,
 2017.0,
 2010.0,
 2014.0,
 2011.0,
 2017.0,
 2009.0,
 2018.0,
 2016.0,
 2019.0,
 2014.0,
 2009.0,
 2010.0,
 2014.0,
 2005.0,
 2015.0,
 2015.0,
 2014.0,
 2014.0,
 2011.0,
 2013.0,
 2016.0,
 2013.0,
 2018.0,
 2012.0,
 2018.0,
 2019.0,
 2014.0,
 2018.0,
 2015.0,
 2009.0,
 2013.0,
 2015.0,
 2012.0,
 2012.0,
 2018.0,
 2011.0,
 2012.0,
 2013.0,
 2011.0,
 2007.0,
 2011.0,
 2012.0,
 2013.0,
 2013.0,
 2021.0,
 2012.0,
 2011.0,
 2016.0,
 2019.0,
 2016.0,
 2016.0,
 2017.0,
 2017.0,
 2012.0,
 2013.0,
 2019.0,
 2009.0,
 2015.0,
 2018.0,
 2011.0,
 2011.0,
 2013.0,
 2013.0,
 2010.0,
 2016.0,
 2016.0,
 2016.0,
 2016.0,
 2016.0,
 2018.0,
 2011.0,
 2016.0,
 2011.0,
 2015.0,
 2016.0,
 2005.0,
 2019.0,
 2021.0,
 2012.0,
 2016.0,
 2016.0,
 2016.0,
 2010.0,
 2012.0,
 2021.0,
 2019.0,
 2010.0,
 2010.0,
 2011.0,
 2014.0,
 2009.0,
 2010.0,
 2011.0,
 2008.0,
 2018.0,
 2012.0,
 2013.0,
 2010.0,
 2021.0,
 2012.0,
 2016.0,
 2011.0,
 2017.0,
 2017.0,
 2019.0,
 2012.0,
 2009.0,
 2014.0,
 2014.0,
 2002.0,
 2020.0,
 2017.0,
 2014.0,
 2013.0,
 2013.0,
 2011.0,
 2013.0,
 2017.0,
 2012.0,
 2014.0,
 2018.0,
 2017.0,
 2012.0,
 2015.0,
 2013.0,
 2018.0,
 2014.0,
 2016.0,
 1999.0,
 2018.0,
 2018.0,
 2000.0,
 2013.0,
 2018.0,
 2013.0,
 2019.0,
 2018.0,
 2012.0,
 2012.0,
 2018.0,
 2020.0,
 2018.0,
 2009.0,
 2020.0,
 2016.0,
 2020.0,
 2016.0,
 2006.0,
 2014.0,
 2009.0,
 2011.0,
 2021.0,
 2017.0,
 2015.0,
 2019.0,
 2011.0,
 2018.0,
 2018.0,
 2009.0,
 2017.0,
 2012.0,
 2017.0,
 2010.0,
 2017.0,
 2014.0,
 2017.0,
 2011.0,
 2006.0,
 2021.0,
 2009.0,
 2011.0,
 2018.0,
 2012.0,
 2019.0,
 2014.0,
 2015.0,
 2019.0,
 2020.0,
 2016.0,
 2010.0,
 2011.0,
 2014.0,
 2010.0,
 2013.0,
 2012.0,
 2012.0,
 2017.0,
 2015.0,
 2011.0,
 2016.0,
 2016.0,
 2008.0,
 2018.0,
 2009.0,
 2014.0,
 2011.0,
 2012.0,
 2016.0,
 2019.0,
 2007.0,
 2018.0,
 2014.0,
 2019.0,
 2020.0,
 2011.0,
 2011.0,
 2011.0,
 2019.0,
 2020.0,
 2019.0,
 2016.0,
 2011.0,
 2011.0,
 2014.0,
 2006.0,
 2020.0,
 2020.0,
 2020.0,
 2018.0,
 2009.0,
 2014.0,
 2013.0,
 2012.0,
 2014.0,
 2011.0,
 2015.0,
 2014.0,
 2015.0,
 2018.0,
 2017.0,
 2015.0,
 2017.0,
 2021.0,
 2013.0,
 2016.0,
 2013.0,
 2012.0,
 2014.0,
 2014.0,
 2013.0,
 2017.0,
 2016.0,
 2016.0,
 2011.0,
 2016.0,
 2014.0,
 2012.0,
 2015.0,
 2018.0,
 2016.0]

In [197]:
#Fetching data from olx for Km used, Company, Location, Date of posting

for k7 in driver7.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Km_7.append(k7.text.split('-')[1])
for c7 in driver7.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[2]"):
    Company_7.append(c7.text)
for l7 in driver7.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]"):
    Location_7.append(l7.text)
for d7 in driver7.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]/span"):
    Date_7.append(d7.text)

In [198]:
#Making a dataframe named Cars storing 500 data into that

CARS7=pd.DataFrame({})
CARS7['PRICE']=Price_7[0:500]
CARS7['YEAR']=Year_7[0:500]
CARS7['KM']=Km_7[0:500]
CARS7['COMPANY']=Company_7[0:500]
CARS7['LOCATION']=Location_7[0:500]
CARS7['POSTED-DATE']=Date_7[0:500]

In [199]:
#Printing the dataframe

CARS7

,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE
0,750000,1996.0,"56,000 km",Hindustan Motors Contessa,Hazratganj\nDec 25,Dec 25
1,1700000,2016.0,"115,000 km",Ford Endeavour,Hazratganj\nDec 20,Dec 20
2,4675000,2018.0,"58,000 km",Land Rover Discovery Sport,Hindustan Aeronautics Limited\nJun 10,Jun 10
3,200000,2016.0,"30,000 km",Maruti Suzuki Omni,Rakabganj\nJan 12,Jan 12
4,1800000,2014.0,"70,000 km",BMW X3,Butler Palace Colony\nJan 12,Jan 12
...,...,...,...,...,...,...
495,290000,2011.0,"120,000 km",Tata Safari,Kursi Road\n6 days ago,6 days ago
496,148000,2011.0,"70,000 km",Fiat Grande Punto,Husaria\nJan 16,Jan 16
497,230000,2011.0,"70,000 km",Hyundai i20,Jalalpur\nJan 10,Jan 10
498,1890000,2019.0,"25,000 km",Toyota Innova Crysta,Vijyant Khand\nJun 10,Jun 10
499,4600000,2020.0,"10,000 km",BMW 3 Series GT,Chinhat\nMar 17,Mar 17

In [200]:
#Getting the information of the dataset

CARS7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRICE        500 non-null    int64
 1   YEAR         500 non-null    float64
 2   KM           500 non-null    object
 3   COMPANY      500 non-null    object
 4   LOCATION     500 non-null    object
 5   POSTED-DATE  500 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 23.6+ KB

In [201]:
driver7.close()

# 3998 IN TOTAL NOW

In [202]:
#Creating an instance of the chrome driver to get to the url

driver8 = webdriver.Chrome(r'E:/CHROME-DRIVER/chromedriver_win32/chromedriver.exe')

In [203]:
#Getting into the website

driver8.get('https://www.olx.in/en-in/punjab_g2001170/cars_c84')

In [204]:
#Creating empty lists so that we can fetch the data

Price_8=[]
Year_8=[]
Km_8=[]
Company_8=[]
Location_8=[]
Date_8=[]

In [205]:
#Fetching the data from olx for Price

for p8 in driver8.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/span"):
    Price_8.append(p8.text.replace("â‚¹","").replace(",",""))

In [206]:
Price_8

[' 600000',
 ' 2350000',
 ' 2800000',
 ' 198000',
 ' 275000',
 ' 1850000',
 ' 850000',
 ' 850000',
 ' 270000',
 ' 145000',
 ' 1325000',
 ' 175000',
 ' 190000',
 ' 190000',
 ' 80000',
 ' 390000',
 ' 160000',
 ' 75000',
 ' 178000',
 ' 140000',
 ' 495000',
 ' 4950000',
 ' 1150000',
 ' 220000',
 ' 470000',
 ' 180000',
 ' 1475000',
 ' 600000',
 ' 435000',
 ' 1099999',
 ' 1725000',
 ' 48000',
 ' 850000',
 ' 375000',
 ' 80000',
 ' 390000',
 ' 525000',
 ' 815000',
 ' 625000',
 ' 550000',
 ' 385000',
 ' 345000',
 ' 925000',
 ' 460000',
 ' 230000',
 ' 460000',
 ' 220000',
 ' 95000',
 ' 270000',
 ' 180000',
 ' 140000',
 ' 775000',
 ' 785000',
 ' 300000',
 ' 790000',
 ' 725000',
 ' 1315000',
 ' 95000',
 ' 115000',
 ' 189999',
 ' 220000',
 ' 630000',
 ' 265000',
 ' 405000',
 ' 390000',
 ' 720000',
 ' 500000',
 ' 85000',
 ' 480000',
 ' 630000',
 ' 600000',
 ' 160000',
 ' 330000',
 ' 75000',
 ' 85000',
 ' 180000',
 ' 470000',
 ' 15000',
 ' 115000',
 ' 180000',
 ' 1075000',
 ' 1150000',
 ' 390000',
 ' 429000',
 ' 128000',
 ' 550000',
 ' 195000',
 ' 141000',
 ' 265000',
 ' 32000',
 ' 1200000',
 ' 950000',
 ' 3500000',
 ' 4005000',
 ' 1790000',
 ' 140000',
 ' 135000',
 ' 410000',
 ' 745000',
 ' 365000',
 ' 160000',
 ' 935000',
 ' 565000',
 ' 295000',
 ' 375000',
 ' 679000',
 ' 400000',
 ' 230000',
 ' 59500',
 ' 415000',
 ' 38000',
 ' 1390000',
 ' 350000',
 ' 42000',
 ' 190000',
 ' 31500',
 ' 43000',
 ' 1600000',
 ' 140000',
 ' 1475000',
 ' 770000',
 ' 215000',
 ' 995000',
 ' 825000',
 ' 100000',
 ' 230000',
 ' 695000',
 ' 135000',
 ' 165000',
 ' 238999',
 ' 505000',
 ' 250000',
 ' 95000',
 ' 475000',
 ' 170000',
 ' 465000',
 ' 1100000',
 ' 160000',
 ' 435000',
 ' 225000',
 ' 925000',
 ' 425000',
 ' 125000',
 ' 310000',
 ' 425000',
 ' 125000',
 ' 400000',
 ' 68000',
 ' 390000',
 ' 145000',
 ' 530000',
 ' 285000',
 ' 665000',
 ' 725000',
 ' 530000',
 ' 650000',
 ' 425000',
 ' 925000',
 ' 155000',
 ' 250000',
 ' 650000',
 ' 925000',
 ' 369000',
 ' 192000',
 ' 710000',
 ' 155000',
 ' 51000',
 ' 210000',
 ' 262000',
 ' 550000',
 ' 650000',
 ' 160000',
 ' 85000',
 ' 43000',
 ' 235000',
 ' 690000',
 ' 26500',
 ' 486000',
 ' 110000',
 ' 155000',
 ' 249000',
 ' 1075000',
 ' 395000',
 ' 168000',
 ' 130000',
 ' 180000',
 ' 135999',
 ' 410000',
 ' 75000',
 ' 262000',
 ' 250000',
 ' 255000',
 ' 174000',
 ' 685000',
 ' 845000',
 ' 1650000',
 ' 435000',
 ' 500000',
 ' 800000',
 ' 135000',
 ' 750000',
 ' 265000',
 ' 515000',
 ' 250000',
 ' 400000',
 ' 850000',
 ' 285000',
 ' 1625000',
 ' 95000',
 ' 360000',
 ' 65000',
 ' 455000',
 ' 485000',
 ' 725000',
 ' 49000',
 ' 130000',
 ' 119999',
 ' 485000',
 ' 135000',
 ' 320000',
 ' 2600000',
 ' 750000',
 ' 760000',
 ' 315000',
 ' 160000',
 ' 925000',
 ' 1200000',
 ' 975000',
 ' 950000',
 ' 185000',
 ' 350000',
 ' 260000',
 ' 100000',
 ' 160000',
 ' 275000',
 ' 450000',
 ' 435000',
 ' 75000',
 ' 195000',
 ' 170000',
 ' 1310000',
 ' 875000',
 ' 965000',
 ' 500000',
 ' 330000',
 ' 220000',
 ' 65000',
 ' 200000',
 ' 625000',
 ' 515000',
 ' 310000',
 ' 690000',
 ' 1250000',
 ' 960000',
 ' 115000',
 ' 72000',
 ' 225000',
 ' 450000',
 ' 1400000',
 ' 145000',
 ' 1275000',
 ' 765000',
 ' 1865000',
 ' 399999',
 ' 170000',
 ' 190000',
 ' 98000',
 ' 420000',
 ' 310000',
 ' 230000',
 ' 150000',
 ' 625000',
 ' 130000',
 ' 490000',
 ' 250000',
 ' 410000',
 ' 395000',
 ' 460000',
 ' 178000',
 ' 390000',
 ' 840000',
 ' 1750000',
 ' 120000',
 ' 965000',
 ' 425000',
 ' 580000',
 ' 485000',
 ' 1050000',
 ' 295000',
 ' 550000',
 ' 240000',
 ' 200000',
 ' 650000',
 ' 200000',
 ' 265000',
 ' 165000',
 ' 110000',
 ' 2400000',
 ' 399999',
 ' 340000',
 ' 1675000',
 ' 1880000',
 ' 310000',
 ' 210000',
 ' 75000',
 ' 270000',
 ' 425000',
 ' 750000',
 ' 445000',
 ' 245000',
 ' 400000',
 ' 194000',
 ' 250000',
 ' 90000',
 ' 2020000',
 ' 190000',
 ' 170000',
 ' 675000',
 ' 192000',
 ' 372000',
 ' 430000',
 ' 975000',
 ' 260000',
 ' 180000',
 ' 350000',
 ' 720000',
 ' 470000',
 ' 135000',
 ' 1080000',
 ' 245000',
 ' 1200000',
 ' 1349000',
 ' 140000',
 ' 1375000',
 ' 275000',
 ' 330000',
 ' 410000',
 ' 155000',
 ' 820000',
 ' 625000',
 ' 260000',
 ' 2775000',
 ' 500000',
 ' 180000',
 ' 475000',
 ' 315000',
 ' 1135000',
 ' 440000',
 ' 1050000',
 ' 370000',
 ' 525000',
 ' 650000',
 ' 975000',
 ' 219000',
 ' 110000',
 ' 1080000',
 ' 65000',
 ' 265000',
 ' 250000',
 ' 710000',
 ' 3799999',
 ' 1255000',
 ' 310000',
 ' 70000',
 ' 419000',
 ' 2575000',
 ' 135000',
 ' 175000',
 ' 110000',
 ' 425000',
 ' 310000',
 ' 2099000',
 ' 695000',
 ' 590000',
 ' 160000',
 ' 415000',
 ' 330000',
 ' 90000',
 ' 675000',
 ' 215000',
 ' 840000',
 ' 675000',
 ' 630000',
 ' 150000',
 ' 350000',
 ' 825000',
 ' 920000',
 ' 395000',
 ' 850000',
 ' 1065000',
 ' 340000',
 ' 875000',
 ' 218000',
 ' 1020000',
 ' 293000',
 ' 85000',
 ' 175000',
 ' 1050000',
 ' 285000',
 ' 2100000',
 ' 325000',
 ' 645000',
 ' 135000',
 ' 810000',
 ' 235000',
 ' 235000',
 ' 360000',
 ' 550000',
 ' 140000',
 ' 155000',
 ' 159000',
 ' 975000',
 ' 495000',
 ' 765000',
 ' 745000',
 ' 55000',
 ' 460000',
 ' 280000',
 ' 190000',
 ' 1049000',
 ' 450000',
 ' 295000',
 ' 550000',
 ' 150000',
 ' 51000',
 ' 450000',
 ' 220000',
 ' 28500',
 ' 300000',
 ' 3200000',
 ' 1250000',
 ' 1750000',
 ' 1125000',
 ' 315000',
 ' 130000',
 ' 52000',
 ' 109999',
 ' 650000',
 ' 110000',
 ' 1025000',
 ' 950000',
 ' 1200000',
 ' 245000',
 ' 225000',
 ' 325000',
 ' 470000',
 ' 61000',
 ' 36000',
 ' 1550000',
 ' 1050000',
 ' 725000',
 ' 43000',
 ' 225000',
 ' 480000',
 ' 200000',
 ' 425000',
 ' 350000',
 ' 495000',
 ' 345000',
 ' 2899000',
 ' 340000',
 ' 275000',
 ' 1600000',
 ' 175000',
 ' 1295000',
 ' 82000',
 ' 470000',
 ' 60000',
 ' 245000',
 ' 170000',
 ' 2500000',
 ' 125000',
 ' 160000',
 ' 247000',
 ' 243000',
 ' 450000',
 ' 290000',
 ' 1950000',
 ' 710000',
 ' 585000',
 ' 699999',
 ' 265000',
 ' 470000',
 ' 350000',
 ' 270000',
 ' 540000',
 ' 775000',
 ' 270000',
 ' 425000',
 ' 250000',
 ' 700000',
 ' 60000',
 ' 625000',
 ' 580000',
 ' 220000',
 ' 350000',
 ' 150000',
 ' 350000',
 ' 64000']

In [207]:
#Converting the column into integer type

for i in range(0, len(Price_8)):
    Price_8[i] = int(Price_8[i])

In [208]:
#Printing after conversion

Price_8

[600000,
 2350000,
 2800000,
 198000,
 275000,
 1850000,
 850000,
 850000,
 270000,
 145000,
 1325000,
 175000,
 190000,
 190000,
 80000,
 390000,
 160000,
 75000,
 178000,
 140000,
 495000,
 4950000,
 1150000,
 220000,
 470000,
 180000,
 1475000,
 600000,
 435000,
 1099999,
 1725000,
 48000,
 850000,
 375000,
 80000,
 390000,
 525000,
 815000,
 625000,
 550000,
 385000,
 345000,
 925000,
 460000,
 230000,
 460000,
 220000,
 95000,
 270000,
 180000,
 140000,
 775000,
 785000,
 300000,
 790000,
 725000,
 1315000,
 95000,
 115000,
 189999,
 220000,
 630000,
 265000,
 405000,
 390000,
 720000,
 500000,
 85000,
 480000,
 630000,
 600000,
 160000,
 330000,
 75000,
 85000,
 180000,
 470000,
 15000,
 115000,
 180000,
 1075000,
 1150000,
 390000,
 429000,
 128000,
 550000,
 195000,
 141000,
 265000,
 32000,
 1200000,
 950000,
 3500000,
 4005000,
 1790000,
 140000,
 135000,
 410000,
 745000,
 365000,
 160000,
 935000,
 565000,
 295000,
 375000,
 679000,
 400000,
 230000,
 59500,
 415000,
 38000,
 1390000,
 350000,
 42000,
 190000,
 31500,
 43000,
 1600000,
 140000,
 1475000,
 770000,
 215000,
 995000,
 825000,
 100000,
 230000,
 695000,
 135000,
 165000,
 238999,
 505000,
 250000,
 95000,
 475000,
 170000,
 465000,
 1100000,
 160000,
 435000,
 225000,
 925000,
 425000,
 125000,
 310000,
 425000,
 125000,
 400000,
 68000,
 390000,
 145000,
 530000,
 285000,
 665000,
 725000,
 530000,
 650000,
 425000,
 925000,
 155000,
 250000,
 650000,
 925000,
 369000,
 192000,
 710000,
 155000,
 51000,
 210000,
 262000,
 550000,
 650000,
 160000,
 85000,
 43000,
 235000,
 690000,
 26500,
 486000,
 110000,
 155000,
 249000,
 1075000,
 395000,
 168000,
 130000,
 180000,
 135999,
 410000,
 75000,
 262000,
 250000,
 255000,
 174000,
 685000,
 845000,
 1650000,
 435000,
 500000,
 800000,
 135000,
 750000,
 265000,
 515000,
 250000,
 400000,
 850000,
 285000,
 1625000,
 95000,
 360000,
 65000,
 455000,
 485000,
 725000,
 49000,
 130000,
 119999,
 485000,
 135000,
 320000,
 2600000,
 750000,
 760000,
 315000,
 160000,
 925000,
 1200000,
 975000,
 950000,
 185000,
 350000,
 260000,
 100000,
 160000,
 275000,
 450000,
 435000,
 75000,
 195000,
 170000,
 1310000,
 875000,
 965000,
 500000,
 330000,
 220000,
 65000,
 200000,
 625000,
 515000,
 310000,
 690000,
 1250000,
 960000,
 115000,
 72000,
 225000,
 450000,
 1400000,
 145000,
 1275000,
 765000,
 1865000,
 399999,
 170000,
 190000,
 98000,
 420000,
 310000,
 230000,
 150000,
 625000,
 130000,
 490000,
 250000,
 410000,
 395000,
 460000,
 178000,
 390000,
 840000,
 1750000,
 120000,
 965000,
 425000,
 580000,
 485000,
 1050000,
 295000,
 550000,
 240000,
 200000,
 650000,
 200000,
 265000,
 165000,
 110000,
 2400000,
 399999,
 340000,
 1675000,
 1880000,
 310000,
 210000,
 75000,
 270000,
 425000,
 750000,
 445000,
 245000,
 400000,
 194000,
 250000,
 90000,
 2020000,
 190000,
 170000,
 675000,
 192000,
 372000,
 430000,
 975000,
 260000,
 180000,
 350000,
 720000,
 470000,
 135000,
 1080000,
 245000,
 1200000,
 1349000,
 140000,
 1375000,
 275000,
 330000,
 410000,
 155000,
 820000,
 625000,
 260000,
 2775000,
 500000,
 180000,
 475000,
 315000,
 1135000,
 440000,
 1050000,
 370000,
 525000,
 650000,
 975000,
 219000,
 110000,
 1080000,
 65000,
 265000,
 250000,
 710000,
 3799999,
 1255000,
 310000,
 70000,
 419000,
 2575000,
 135000,
 175000,
 110000,
 425000,
 310000,
 2099000,
 695000,
 590000,
 160000,
 415000,
 330000,
 90000,
 675000,
 215000,
 840000,
 675000,
 630000,
 150000,
 350000,
 825000,
 920000,
 395000,
 850000,
 1065000,
 340000,
 875000,
 218000,
 1020000,
 293000,
 85000,
 175000,
 1050000,
 285000,
 2100000,
 325000,
 645000,
 135000,
 810000,
 235000,
 235000,
 360000,
 550000,
 140000,
 155000,
 159000,
 975000,
 495000,
 765000,
 745000,
 55000,
 460000,
 280000,
 190000,
 1049000,
 450000,
 295000,
 550000,
 150000,
 51000,
 450000,
 220000,
 28500,
 300000,
 3200000,
 1250000,
 1750000,
 1125000,
 315000,
 130000,
 52000,
 109999,
 650000,
 110000,
 1025000,
 950000,
 1200000,
 245000,
 225000,
 325000,
 470000,
 61000,
 36000,
 1550000,
 1050000,
 725000,
 43000,
 225000,
 480000,
 200000,
 425000,
 350000,
 495000,
 345000,
 2899000,
 340000,
 275000,
 1600000,
 175000,
 1295000,
 82000,
 470000,
 60000,
 245000,
 170000,
 2500000,
 125000,
 160000,
 247000,
 243000,
 450000,
 290000,
 1950000,
 710000,
 585000,
 699999,
 265000,
 470000,
 350000,
 270000,
 540000,
 775000,
 270000,
 425000,
 250000,
 700000,
 60000,
 625000,
 580000,
 220000,
 350000,
 150000,
 350000,
 64000]

In [209]:
#Fetching data from olx for Year

for y8 in driver8.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Year_8.append(y8.text.split('-')[0])

In [210]:
#Converting the column into integer type

for i in range(0, len(Year_8)):
    Year_8[i] = int(Year_8[i])

In [211]:
#Printing after conversion

Year_8

[2016,
 2013,
 2011,
 2012,
 2013,
 2015,
 2007,
 2008,
 2011,
 2007,
 2019,
 2012,
 2009,
 2012,
 2006,
 2011,
 2009,
 2009,
 2013,
 2007,
 2012,
 2015,
 2017,
 2010,
 2011,
 2007,
 2021,
 2017,
 2016,
 2018,
 2018,
 1998,
 2017,
 2014,
 2000,
 2016,
 2009,
 2013,
 2013,
 2016,
 2013,
 2013,
 2010,
 2011,
 2005,
 2014,
 2010,
 2004,
 2010,
 2009,
 2010,
 2015,
 2012,
 2019,
 2018,
 2020,
 2018,
 2004,
 2007,
 2012,
 2007,
 2019,
 2012,
 2013,
 2013,
 2021,
 2016,
 2003,
 2018,
 2017,
 2021,
 2011,
 2017,
 2006,
 2002,
 2010,
 2013,
 2021,
 2007,
 2008,
 2019,
 2013,
 2012,
 2013,
 2007,
 2012,
 2008,
 2011,
 2015,
 2001,
 2012,
 2018,
 2013,
 2013,
 2019,
 2004,
 2011,
 2016,
 2019,
 2010,
 2008,
 2015,
 2019,
 2012,
 2014,
 2020,
 2013,
 2008,
 2012,
 2014,
 2020,
 2013,
 2013,
 1998,
 2013,
 2001,
 2004,
 2018,
 2006,
 2011,
 2018,
 2008,
 2019,
 2011,
 2007,
 2011,
 2017,
 2012,
 2009,
 2011,
 2015,
 2014,
 2005,
 2014,
 2007,
 2014,
 2021,
 2011,
 2013,
 2013,
 2017,
 2012,
 2007,
 2010,
 2017,
 2007,
 2011,
 2005,
 2013,
 2013,
 2017,
 2009,
 2016,
 2017,
 2015,
 2008,
 2014,
 2015,
 2012,
 2013,
 2012,
 2021,
 2011,
 2013,
 2008,
 2010,
 2006,
 2011,
 2011,
 2019,
 2020,
 2003,
 2007,
 1997,
 2012,
 2017,
 2000,
 2013,
 2012,
 2011,
 2008,
 2011,
 2012,
 2007,
 2011,
 2011,
 2007,
 2015,
 2004,
 2011,
 2014,
 2012,
 2013,
 2018,
 2020,
 2016,
 2011,
 2015,
 2019,
 2009,
 2014,
 2017,
 2014,
 2008,
 2009,
 2011,
 2012,
 2013,
 2001,
 2011,
 2003,
 2013,
 2018,
 2015,
 2007,
 2008,
 2007,
 2012,
 2005,
 2011,
 2020,
 2018,
 2017,
 2012,
 2007,
 2019,
 2010,
 2019,
 2011,
 2010,
 2014,
 2009,
 2007,
 2009,
 2011,
 2012,
 2013,
 2004,
 2008,
 2009,
 2012,
 2010,
 2019,
 2015,
 2013,
 2010,
 2004,
 2011,
 2018,
 2015,
 2012,
 2020,
 2011,
 2020,
 2007,
 2002,
 2009,
 2011,
 2012,
 2002,
 2012,
 2014,
 2021,
 2013,
 2005,
 2007,
 2005,
 2013,
 2012,
 2009,
 2007,
 2012,
 2009,
 2013,
 2011,
 2012,
 2013,
 2014,
 2010,
 2013,
 2017,
 2016,
 2003,
 2011,
 2017,
 2010,
 2016,
 2012,
 2008,
 2015,
 2016,
 2011,
 2015,
 2013,
 2012,
 1984,
 2006,
 2017,
 2019,
 2012,
 2017,
 2020,
 2012,
 2011,
 2004,
 2013,
 2017,
 2019,
 2015,
 2010,
 2012,
 2013,
 2009,
 2008,
 2010,
 2001,
 2012,
 2013,
 2013,
 2013,
 2019,
 2012,
 2012,
 2012,
 2012,
 2018,
 2018,
 2008,
 2015,
 2009,
 2010,
 2013,
 2007,
 2014,
 2010,
 2019,
 2013,
 2009,
 2018,
 2013,
 2008,
 2018,
 2013,
 2007,
 2015,
 2011,
 2013,
 2014,
 2013,
 2009,
 2011,
 2015,
 2012,
 2012,
 2007,
 2012,
 1995,
 2011,
 2014,
 2017,
 2016,
 2012,
 2016,
 2005,
 2017,
 2015,
 2008,
 2012,
 2008,
 2011,
 2013,
 2012,
 2021,
 2013,
 2011,
 2015,
 2012,
 2000,
 2013,
 2008,
 2016,
 2015,
 2016,
 2006,
 2019,
 2016,
 2010,
 2012,
 2012,
 2012,
 2010,
 2013,
 2013,
 2019,
 2012,
 2005,
 2008,
 2014,
 2011,
 2021,
 2015,
 2016,
 2008,
 2014,
 2009,
 2013,
 2012,
 2012,
 2005,
 2007,
 2009,
 2018,
 2015,
 2020,
 2019,
 2000,
 2014,
 2019,
 2008,
 2011,
 2011,
 2010,
 2012,
 2006,
 2003,
 2012,
 2020,
 2000,
 2007,
 2013,
 2012,
 2021,
 2020,
 2016,
 2006,
 2002,
 2004,
 2016,
 2006,
 2020,
 2019,
 2012,
 2011,
 2006,
 2012,
 2013,
 2007,
 2003,
 2016,
 2010,
 2018,
 2007,
 2007,
 2012,
 2011,
 2014,
 2017,
 2015,
 2012,
 2015,
 2016,
 2012,
 2012,
 2008,
 2013,
 2003,
 2012,
 2001,
 2008,
 2008,
 2016,
 2007,
 2006,
 2011,
 2011,
 2021,
 2010,
 2011,
 2019,
 2013,
 2007,
 2012,
 2013,
 2009,
 2012,
 2013,
 2020,
 2015,
 2012,
 2008,
 2020,
 2002,
 2019,
 2017,
 2018,
 2012,
 2014,
 2011,
 2001]

In [212]:
#Fetching data from olx for Km used, Company, Location, Date of posting

for k8 in driver8.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Km_8.append(k8.text.split('-')[1])
for c8 in driver8.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[2]"):
    Company_8.append(c8.text)
for l8 in driver8.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]"):
    Location_8.append(l8.text)
for d8 in driver8.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]/span"):
    Date_8.append(d8.text)

In [213]:
#Making a dataframe named Cars storing 500 data into that

CARS8=pd.DataFrame({})
CARS8['PRICE']=Price_8[0:500]
CARS8['YEAR']=Year_8[0:500]
CARS8['KM']=Km_8[0:500]
CARS8['COMPANY']=Company_8[0:500]
CARS8['LOCATION']=Location_8[0:500]
CARS8['POSTED-DATE']=Date_8[0:500]

In [214]:
#Printing the dataframe

CARS8

,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE
0,600000,2016,"68,000 km",Maruti Suzuki Ciaz,Model Gram\nDec 12,Dec 12
1,2350000,2013,"91,000 km",Land Rover Range Rover Evoque,Sector 82\nJan 14,Jan 14
2,2800000,2011,"31,000 km",BMW 6 Series,Sector 82\nSep 23,Sep 23
3,198000,2012,"120,000 km",Maruti Suzuki Ritz,Ward No 7\nToday,Today
4,275000,2013,"120,000 km",Maruti Suzuki Swift Dzire Tour,Improvement Trust Bagar\nToday,Today
...,...,...,...,...,...,...
494,220000,2018,"7,500 km",Tata Others,Sector 68\nToday,Today
495,350000,2012,"65,000 km",Nissan Sunny,Nijam Nagar\nToday,Today
496,150000,2014,"112,452 km",Tata Indigo Ecs,Prem Nagar\nToday,Today
497,350000,2011,"68,000 km",Hyundai i20,Nijam Nagar\nToday,Today
498,64000,2001,"67,000 km",Maruti Suzuki Zen,Ward No 12\nToday,Today

In [215]:
#Getting the information about the dataset

CARS8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRICE        499 non-null    int64
 1   YEAR         499 non-null    int64
 2   KM           499 non-null    object
 3   COMPANY      499 non-null    object
 4   LOCATION     499 non-null    object
 5   POSTED-DATE  499 non-null    object
dtypes: int64(2), object(4)
memory usage: 23.5+ KB

In [216]:
driver8.close()

# 4497 IN TOTAL NOW

In [217]:
#Creating an instance of the chrome driver to get to the url

driver9 = webdriver.Chrome(r'E:/CHROME-DRIVER/chromedriver_win32/chromedriver.exe')

In [218]:
#Getting into the website

driver9.get('https://www.olx.in/en-in/haryana_g2001155/cars_c84?isSearchCall=false')

In [219]:
#Creating empty lists so that we can fetch the data

Price_9=[]
Year_9=[]
Km_9=[]
Company_9=[]
Location_9=[]
Date_9=[]

In [220]:
#Fetching the data from olx for Price

for p9 in driver9.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/span"):
    Price_9.append(p9.text.replace("â‚¹","").replace(",",""))

In [221]:
#Printing the price

Price_9

[' 1380000',
 ' 915000',
 ' 1050000',
 ' 400000',
 ' 160000',
 ' 175000',
 ' 1300000',
 ' 110000',
 ' 550000',
 ' 80000',
 ' 95000',
 ' 480000',
 ' 435000',
 ' 340000',
 ' 5700000',
 ' 150000',
 ' 725000',
 ' 160000',
 ' 365000',
 ' 310000',
 ' 713400',
 ' 300000',
 ' 3350000',
 ' 350000',
 ' 295000',
 ' 150000',
 ' 426000',
 ' 165000',
 ' 340000',
 ' 650000',
 ' 115000',
 ' 990000',
 ' 560000',
 ' 950000',
 ' 1680000',
 ' 405000',
 ' 370000',
 ' 280000',
 ' 185000',
 ' 640000',
 ' 590000',
 ' 886000',
 ' 713400',
 ' 650000',
 ' 750000',
 ' 550000',
 ' 2125000',
 ' 225000',
 ' 425000',
 ' 599999',
 ' 300000',
 ' 85000',
 ' 250000',
 ' 125000',
 ' 300000',
 ' 135000',
 ' 490000',
 ' 240000',
 ' 370000',
 ' 225000',
 ' 270000',
 ' 135000',
 ' 1099000',
 ' 145000',
 ' 430000',
 ' 5700000',
 ' 230000',
 ' 260000',
 ' 52000',
 ' 410000',
 ' 350000',
 ' 80000',
 ' 300000',
 ' 235000',
 ' 70000',
 ' 4490000',
 ' 2250000',
 ' 250000',
 ' 270000',
 ' 850000',
 ' 13900000',
 ' 580000',
 ' 950000',
 ' 140000',
 ' 400000',
 ' 140000',
 ' 250000',
 ' 550000',
 ' 1370000',
 ' 380000',
 ' 1450000',
 ' 1650000',
 ' 495000',
 ' 6489000',
 ' 435000',
 ' 825000',
 ' 5580000',
 ' 115000',
 ' 375000',
 ' 350000',
 ' 3699000',
 ' 340000',
 ' 3700000',
 ' 330000',
 ' 240000',
 ' 460000',
 ' 360000',
 ' 415000',
 ' 399000',
 ' 325000',
 ' 290000',
 ' 500000',
 ' 340000',
 ' 335000',
 ' 425000',
 ' 415000',
 ' 355000',
 ' 610000',
 ' 90000',
 ' 305000',
 ' 189000',
 ' 808312',
 ' 1195000',
 ' 250000',
 ' 155000',
 ' 625000',
 ' 195000',
 ' 320000',
 ' 295000',
 ' 400000',
 ' 515000',
 ' 595000',
 ' 225000',
 ' 650000',
 ' 1690000',
 ' 115000',
 ' 235000',
 ' 850000',
 ' 340000',
 ' 265000',
 ' 740600',
 ' 250000',
 ' 238200',
 ' 250000',
 ' 1350000',
 ' 475000',
 ' 460000',
 ' 475000',
 ' 485000',
 ' 2150000',
 ' 485000',
 ' 375000',
 ' 390000',
 ' 755000',
 ' 240000',
 ' 270000',
 ' 280000',
 ' 300000',
 ' 1675000',
 ' 520000',
 ' 635000',
 ' 11300000',
 ' 737200',
 ' 400000',
 ' 140000',
 ' 455000',
 ' 325000',
 ' 325000',
 ' 350000',
 ' 319999',
 ' 525000',
 ' 1700000',
 ' 1700000',
 ' 1025000',
 ' 915000',
 ' 230000',
 ' 300000',
 ' 120000',
 ' 275000',
 ' 100000',
 ' 425000',
 ' 1399000',
 ' 9699999',
 ' 250000',
 ' 120000',
 ' 80999',
 ' 375000',
 ' 585000',
 ' 1700000',
 ' 350000',
 ' 730400',
 ' 90000',
 ' 120000',
 ' 460000',
 ' 150000',
 ' 350000',
 ' 265000',
 ' 145000',
 ' 485000',
 ' 350000',
 ' 525000',
 ' 4250000',
 ' 759500',
 ' 49000',
 ' 65000',
 ' 245000',
 ' 1275000',
 ' 585000',
 ' 2750000',
 ' 130000',
 ' 70000',
 ' 100000',
 ' 820000',
 ' 560000',
 ' 345000',
 ' 300000',
 ' 4450000',
 ' 439000',
 ' 170000',
 ' 850000',
 ' 199000',
 ' 4050000',
 ' 3500000',
 ' 210000',
 ' 200000',
 ' 4499000',
 ' 265000',
 ' 320000',
 ' 70000',
 ' 380000',
 ' 270000',
 ' 1080000',
 ' 220000',
 ' 1775000',
 ' 120000',
 ' 2275000',
 ' 610000',
 ' 420000',
 ' 860000',
 ' 480000',
 ' 1380000',
 ' 1450000',
 ' 500000',
 ' 1350000',
 ' 65000',
 ' 50000',
 ' 890000',
 ' 970000',
 ' 250000',
 ' 225000',
 ' 200000',
 ' 150000',
 ' 380000',
 ' 350000',
 ' 150000',
 ' 420000',
 ' 550000',
 ' 400000',
 ' 1300000',
 ' 80000',
 ' 238200',
 ' 1599000',
 ' 450000',
 ' 150000',
 ' 125000',
 ' 580000',
 ' 95000',
 ' 165000',
 ' 670000',
 ' 285000',
 ' 410000',
 ' 75000',
 ' 750000',
 ' 100000',
 ' 175000',
 ' 300000',
 ' 65000',
 ' 430000',
 ' 950000',
 ' 550000',
 ' 1800000',
 ' 5750000',
 ' 1450000',
 ' 380000',
 ' 1635000',
 ' 4249000',
 ' 298000',
 ' 255000',
 ' 1980000',
 ' 1750000',
 ' 210000',
 ' 1850000',
 ' 290000',
 ' 1250000',
 ' 425000',
 ' 850000',
 ' 275000',
 ' 102000',
 ' 600000',
 ' 950000',
 ' 249999',
 ' 740600',
 ' 280000',
 ' 300000',
 ' 120000',
 ' 1875000',
 ' 320000',
 ' 195000',
 ' 1225000',
 ' 850000',
 ' 735000',
 ' 605000',
 ' 1200000',
 ' 3500000',
 ' 2275000',
 ' 330000',
 ' 8795000',
 ' 75000',
 ' 460000',
 ' 575000',
 ' 959000',
 ' 785000',
 ' 750000',
 ' 450000',
 ' 550000',
 ' 1200000',
 ' 130000',
 ' 370000',
 ' 110000',
 ' 280000',
 ' 189000',
 ' 1375000',
 ' 280000',
 ' 285000',
 ' 175000',
 ' 1400000',
 ' 245000',
 ' 150000',
 ' 900000',
 ' 165000',
 ' 525000',
 ' 3350000',
 ' 740600',
 ' 435000',
 ' 300000',
 ' 150000',
 ' 599999',
 ' 350000',
 ' 148000',
 ' 2075000',
 ' 2350000',
 ' 945000',
 ' 1099000',
 ' 295000',
 ' 550000',
 ' 55000',
 ' 160000',
 ' 75000',
 ' 1150000',
 ' 600000',
 ' 1250000',
 ' 330000',
 ' 320000',
 ' 190000',
 ' 170000',
 ' 250000',
 ' 350000',
 ' 289000',
 ' 450000',
 ' 345000',
 ' 475000',
 ' 375000',
 ' 150000',
 ' 194000',
 ' 180000',
 ' 260000',
 ' 310000',
 ' 200000',
 ' 350000',
 ' 135000',
 ' 1680000',
 ' 300000',
 ' 6700000',
 ' 275000',
 ' 490000',
 ' 290000',
 ' 970000',
 ' 286000',
 ' 425000',
 ' 95000',
 ' 325000',
 ' 870000',
 ' 185000',
 ' 435000',
 ' 120000',
 ' 165000',
 ' 145000',
 ' 225000',
 ' 625000',
 ' 350000',
 ' 450000',
 ' 238200',
 ' 759500',
 ' 253000',
 ' 300000',
 ' 850000',
 ' 649000',
 ' 739000',
 ' 1475000',
 ' 2950000',
 ' 140000',
 ' 230000',
 ' 200000',
 ' 420000',
 ' 620000',
 ' 650000',
 ' 290000',
 ' 835000',
 ' 2450000',
 ' 360000',
 ' 737200',
 ' 280000',
 ' 960000',
 ' 425000',
 ' 400000',
 ' 350000',
 ' 351000',
 ' 70000',
 ' 280000',
 ' 270000',
 ' 170000',
 ' 850000',
 ' 513003',
 ' 825000',
 ' 875000',
 ' 215000',
 ' 375000',
 ' 550000',
 ' 135000',
 ' 525000',
 ' 360000',
 ' 425000',
 ' 916000',
 ' 950000',
 ' 295000',
 ' 495000',
 ' 480000',
 ' 500000',
 ' 295000',
 ' 395000',
 ' 450000',
 ' 515000',
 ' 360000',
 ' 850000',
 ' 330000',
 ' 515000',
 ' 445000',
 ' 835000',
 ' 970000',
 ' 869000',
 ' 1145000',
 ' 4950000',
 ' 299900',
 ' 87500',
 ' 200000',
 ' 1850000',
 ' 4485000',
 ' 242000',
 ' 350000',
 ' 170000',
 ' 333000',
 ' 490000',
 ' 250000',
 ' 115000',
 ' 295000',
 ' 210000',
 ' 340000',
 ' 865000',
 ' 1289000',
 ' 115000',
 ' 4000000',
 ' 200000',
 ' 860000',
 ' 350000',
 ' 450000',
 ' 139999',
 ' 95000',
 ' 270000',
 ' 12900000',
 ' 155000',
 ' 1225000',
 ' 950000',
 ' 1050000',
 ' 3449000',
 ' 870000',
 ' 1390000',
 ' 280000',
 ' 45000',
 ' 325000',
 ' 700000']

In [222]:
#Converting the column into integer type

for i in range(0, len(Price_9)):
    Price_9[i] = int(Price_9[i])

In [223]:
#Printing after conversion

Price_9

[1380000,
 915000,
 1050000,
 400000,
 160000,
 175000,
 1300000,
 110000,
 550000,
 80000,
 95000,
 480000,
 435000,
 340000,
 5700000,
 150000,
 725000,
 160000,
 365000,
 310000,
 713400,
 300000,
 3350000,
 350000,
 295000,
 150000,
 426000,
 165000,
 340000,
 650000,
 115000,
 990000,
 560000,
 950000,
 1680000,
 405000,
 370000,
 280000,
 185000,
 640000,
 590000,
 886000,
 713400,
 650000,
 750000,
 550000,
 2125000,
 225000,
 425000,
 599999,
 300000,
 85000,
 250000,
 125000,
 300000,
 135000,
 490000,
 240000,
 370000,
 225000,
 270000,
 135000,
 1099000,
 145000,
 430000,
 5700000,
 230000,
 260000,
 52000,
 410000,
 350000,
 80000,
 300000,
 235000,
 70000,
 4490000,
 2250000,
 250000,
 270000,
 850000,
 13900000,
 580000,
 950000,
 140000,
 400000,
 140000,
 250000,
 550000,
 1370000,
 380000,
 1450000,
 1650000,
 495000,
 6489000,
 435000,
 825000,
 5580000,
 115000,
 375000,
 350000,
 3699000,
 340000,
 3700000,
 330000,
 240000,
 460000,
 360000,
 415000,
 399000,
 325000,
 290000,
 500000,
 340000,
 335000,
 425000,
 415000,
 355000,
 610000,
 90000,
 305000,
 189000,
 808312,
 1195000,
 250000,
 155000,
 625000,
 195000,
 320000,
 295000,
 400000,
 515000,
 595000,
 225000,
 650000,
 1690000,
 115000,
 235000,
 850000,
 340000,
 265000,
 740600,
 250000,
 238200,
 250000,
 1350000,
 475000,
 460000,
 475000,
 485000,
 2150000,
 485000,
 375000,
 390000,
 755000,
 240000,
 270000,
 280000,
 300000,
 1675000,
 520000,
 635000,
 11300000,
 737200,
 400000,
 140000,
 455000,
 325000,
 325000,
 350000,
 319999,
 525000,
 1700000,
 1700000,
 1025000,
 915000,
 230000,
 300000,
 120000,
 275000,
 100000,
 425000,
 1399000,
 9699999,
 250000,
 120000,
 80999,
 375000,
 585000,
 1700000,
 350000,
 730400,
 90000,
 120000,
 460000,
 150000,
 350000,
 265000,
 145000,
 485000,
 350000,
 525000,
 4250000,
 759500,
 49000,
 65000,
 245000,
 1275000,
 585000,
 2750000,
 130000,
 70000,
 100000,
 820000,
 560000,
 345000,
 300000,
 4450000,
 439000,
 170000,
 850000,
 199000,
 4050000,
 3500000,
 210000,
 200000,
 4499000,
 265000,
 320000,
 70000,
 380000,
 270000,
 1080000,
 220000,
 1775000,
 120000,
 2275000,
 610000,
 420000,
 860000,
 480000,
 1380000,
 1450000,
 500000,
 1350000,
 65000,
 50000,
 890000,
 970000,
 250000,
 225000,
 200000,
 150000,
 380000,
 350000,
 150000,
 420000,
 550000,
 400000,
 1300000,
 80000,
 238200,
 1599000,
 450000,
 150000,
 125000,
 580000,
 95000,
 165000,
 670000,
 285000,
 410000,
 75000,
 750000,
 100000,
 175000,
 300000,
 65000,
 430000,
 950000,
 550000,
 1800000,
 5750000,
 1450000,
 380000,
 1635000,
 4249000,
 298000,
 255000,
 1980000,
 1750000,
 210000,
 1850000,
 290000,
 1250000,
 425000,
 850000,
 275000,
 102000,
 600000,
 950000,
 249999,
 740600,
 280000,
 300000,
 120000,
 1875000,
 320000,
 195000,
 1225000,
 850000,
 735000,
 605000,
 1200000,
 3500000,
 2275000,
 330000,
 8795000,
 75000,
 460000,
 575000,
 959000,
 785000,
 750000,
 450000,
 550000,
 1200000,
 130000,
 370000,
 110000,
 280000,
 189000,
 1375000,
 280000,
 285000,
 175000,
 1400000,
 245000,
 150000,
 900000,
 165000,
 525000,
 3350000,
 740600,
 435000,
 300000,
 150000,
 599999,
 350000,
 148000,
 2075000,
 2350000,
 945000,
 1099000,
 295000,
 550000,
 55000,
 160000,
 75000,
 1150000,
 600000,
 1250000,
 330000,
 320000,
 190000,
 170000,
 250000,
 350000,
 289000,
 450000,
 345000,
 475000,
 375000,
 150000,
 194000,
 180000,
 260000,
 310000,
 200000,
 350000,
 135000,
 1680000,
 300000,
 6700000,
 275000,
 490000,
 290000,
 970000,
 286000,
 425000,
 95000,
 325000,
 870000,
 185000,
 435000,
 120000,
 165000,
 145000,
 225000,
 625000,
 350000,
 450000,
 238200,
 759500,
 253000,
 300000,
 850000,
 649000,
 739000,
 1475000,
 2950000,
 140000,
 230000,
 200000,
 420000,
 620000,
 650000,
 290000,
 835000,
 2450000,
 360000,
 737200,
 280000,
 960000,
 425000,
 400000,
 350000,
 351000,
 70000,
 280000,
 270000,
 170000,
 850000,
 513003,
 825000,
 875000,
 215000,
 375000,
 550000,
 135000,
 525000,
 360000,
 425000,
 916000,
 950000,
 295000,
 495000,
 480000,
 500000,
 295000,
 395000,
 450000,
 515000,
 360000,
 850000,
 330000,
 515000,
 445000,
 835000,
 970000,
 869000,
 1145000,
 4950000,
 299900,
 87500,
 200000,
 1850000,
 4485000,
 242000,
 350000,
 170000,
 333000,
 490000,
 250000,
 115000,
 295000,
 210000,
 340000,
 865000,
 1289000,
 115000,
 4000000,
 200000,
 860000,
 350000,
 450000,
 139999,
 95000,
 270000,
 12900000,
 155000,
 1225000,
 950000,
 1050000,
 3449000,
 870000,
 1390000,
 280000,
 45000,
 325000,
 700000]

In [224]:
#Fetching data from olx for Year

for y9 in driver9.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Year_9.append(y9.text.split('-')[0])

In [225]:
#Converting the column into integer type

for i in range(0, len(Year_9)):
    Year_9[i] = int(Year_9[i])

In [226]:
#Printing after conversion

Year_9

[2018,
 2019,
 2016,
 2012,
 2010,
 2012,
 2012,
 2010,
 2016,
 2007,
 2007,
 2017,
 2015,
 2017,
 2016,
 2014,
 2018,
 2011,
 2016,
 2011,
 2019,
 2013,
 2019,
 2014,
 2013,
 2008,
 2013,
 2011,
 2015,
 2017,
 2004,
 2012,
 2020,
 2019,
 2014,
 2018,
 2015,
 2012,
 2010,
 2015,
 2017,
 2019,
 2019,
 2021,
 2016,
 2014,
 2015,
 2011,
 2018,
 2015,
 2014,
 2008,
 2012,
 2009,
 2012,
 2007,
 2018,
 2011,
 2012,
 2009,
 2015,
 2007,
 2011,
 2012,
 2021,
 2021,
 2016,
 2017,
 1997,
 2018,
 2020,
 2007,
 2017,
 2011,
 2004,
 2017,
 2021,
 2010,
 2011,
 2019,
 2018,
 2018,
 2020,
 2010,
 2014,
 2010,
 2012,
 2021,
 2021,
 2014,
 2014,
 2015,
 2016,
 2020,
 2015,
 2016,
 2021,
 2008,
 2010,
 2013,
 2016,
 2010,
 2016,
 2013,
 2014,
 2015,
 2013,
 2021,
 2016,
 2014,
 2015,
 2017,
 2016,
 2014,
 2015,
 2021,
 2013,
 2015,
 2007,
 2018,
 2008,
 2021,
 2013,
 2014,
 2010,
 2015,
 2010,
 2011,
 2010,
 2014,
 2015,
 2017,
 2013,
 2013,
 2013,
 2008,
 2011,
 2019,
 2015,
 2013,
 2018,
 2011,
 2012,
 2017,
 2013,
 2015,
 2017,
 2015,
 2016,
 2017,
 2016,
 2014,
 2012,
 2018,
 2014,
 2015,
 2015,
 2014,
 2019,
 2015,
 2018,
 2020,
 2017,
 2013,
 2011,
 2015,
 2013,
 2016,
 2014,
 2014,
 2014,
 2015,
 2015,
 2019,
 2018,
 2012,
 2009,
 2008,
 2012,
 2007,
 2017,
 2014,
 2019,
 2011,
 2009,
 2001,
 2012,
 2009,
 2015,
 2020,
 2019,
 2011,
 2011,
 2013,
 2015,
 2021,
 2008,
 2011,
 2012,
 2018,
 2019,
 2019,
 2017,
 2007,
 2005,
 2016,
 2014,
 2017,
 2018,
 2010,
 2011,
 2009,
 2018,
 2016,
 2016,
 2011,
 2015,
 2015,
 2010,
 2016,
 2009,
 2021,
 2018,
 2016,
 2010,
 2016,
 2009,
 2015,
 2006,
 2011,
 2010,
 2012,
 2012,
 2016,
 2009,
 2017,
 2015,
 2012,
 2020,
 2017,
 2014,
 2020,
 2014,
 2015,
 2005,
 1999,
 2014,
 2019,
 2014,
 2016,
 2011,
 2010,
 2012,
 2012,
 2019,
 2012,
 2014,
 2014,
 2019,
 2006,
 2012,
 2014,
 2013,
 2011,
 2010,
 2017,
 2011,
 2010,
 2015,
 2011,
 2017,
 2004,
 2019,
 2009,
 2011,
 2017,
 2011,
 2012,
 2012,
 2017,
 2015,
 2021,
 2019,
 2014,
 2019,
 2019,
 2012,
 2018,
 2015,
 2016,
 2011,
 2015,
 2016,
 2010,
 2015,
 2007,
 2013,
 2018,
 2015,
 2013,
 2012,
 2018,
 2017,
 2016,
 2011,
 2020,
 2014,
 2011,
 2017,
 2008,
 2017,
 2021,
 2021,
 2013,
 2016,
 2014,
 2021,
 2007,
 2014,
 2015,
 2020,
 2014,
 2014,
 2018,
 2015,
 2012,
 2012,
 2013,
 2009,
 2014,
 2013,
 2018,
 2012,
 2013,
 2011,
 2017,
 2011,
 2011,
 2018,
 2009,
 2014,
 2019,
 2018,
 2013,
 2010,
 2009,
 2018,
 2015,
 2011,
 2020,
 2015,
 2017,
 2013,
 2014,
 2014,
 2007,
 2011,
 2004,
 2017,
 2017,
 2014,
 2013,
 2013,
 2013,
 2011,
 2014,
 2013,
 2012,
 2012,
 2012,
 2017,
 2012,
 2012,
 2011,
 2010,
 2014,
 2015,
 2010,
 2019,
 2007,
 2014,
 2014,
 2018,
 2017,
 2015,
 2010,
 2019,
 2017,
 2015,
 2008,
 2015,
 2016,
 2012,
 2014,
 2010,
 2011,
 2011,
 2016,
 2013,
 2019,
 2012,
 2012,
 2017,
 2015,
 2013,
 2015,
 2016,
 2018,
 2016,
 2017,
 2008,
 2012,
 2012,
 2015,
 2019,
 2016,
 2014,
 2018,
 2014,
 2014,
 2017,
 2015,
 2017,
 2015,
 2018,
 2012,
 2015,
 2007,
 2016,
 2014,
 2021,
 2019,
 2016,
 2011,
 2012,
 2012,
 2017,
 2014,
 2007,
 2017,
 2013,
 2014,
 2015,
 2015,
 2016,
 2014,
 2016,
 2012,
 2012,
 2015,
 2014,
 2011,
 2014,
 2010,
 2016,
 2017,
 2017,
 2018,
 2019,
 2019,
 2017,
 2016,
 2013,
 2008,
 2010,
 2019,
 2017,
 2011,
 2017,
 2011,
 2011,
 2014,
 2012,
 2010,
 2018,
 2011,
 2017,
 2017,
 2014,
 2010,
 2018,
 2011,
 2016,
 2014,
 2015,
 2010,
 2011,
 2015,
 2017,
 2010,
 2020,
 2020,
 2020,
 2018,
 2018,
 2014,
 2012,
 2006,
 2017,
 2018]

In [227]:
#Fetching data from olx for Km used, Company, Location, Date of posting

for k9 in driver9.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Km_9.append(k9.text.split('-')[1])
for c9 in driver9.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[2]"):
    Company_9.append(c9.text)
for l9 in driver9.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]"):
    Location_9.append(l9.text)
for d9 in driver9.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]/span"):
    Date_9.append(d9.text)

In [228]:
#Making a dataframe named Cars storing 500 data into that

CARS9=pd.DataFrame({})
CARS9['PRICE']=Price_9[0:500]
CARS9['YEAR']=Year_9[0:500]
CARS9['KM']=Km_9[0:500]
CARS9['COMPANY']=Company_9[0:500]
CARS9['LOCATION']=Location_9[0:500]
CARS9['POSTED-DATE']=Date_9[0:500]

In [229]:
#Printing the dataframe

CARS9

,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE
0,1380000,2018,53134.0 km,Jeep Compass,MG Road\nDec 13,Dec 13
1,915000,2019,"46,000 km",Honda City,Sector 13\nJan 06,Jan 06
2,1050000,2016,"78,000 km",Mahindra Scorpio,Vikas Nagar\n2 days ago,2 days ago
3,400000,2012,"95,000 km",Volkswagen Jetta,Dc Colony\nToday,Today
4,160000,2010,"120,000 km",Maruti Suzuki Ritz,Sohna\nToday,Today
...,...,...,...,...,...,...
495,1390000,2014,"58,000 km",Audi Q3,Sector 80\nToday,Today
496,280000,2012,"80,000 km",Maruti Suzuki Ertiga,Gohana Part\nToday,Today
497,45000,2006,"118,000 km",Maruti Suzuki Alto 800,Prakash Nagar\nToday,Today
498,325000,2017,"88,000 km",Hyundai Xcent,New Grain Market\nToday,Today
499,700000,2018,"73,000 km",Hyundai i20 Active,Tagra Kali Ram\nToday,Today

In [230]:
#Printing the ibnformation of the dataset

CARS9.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRICE        500 non-null    int64
 1   YEAR         500 non-null    int64
 2   KM           500 non-null    object
 3   COMPANY      500 non-null    object
 4   LOCATION     500 non-null    object
 5   POSTED-DATE  500 non-null    object
dtypes: int64(2), object(4)
memory usage: 23.6+ KB

In [231]:
driver9.close()

# 4997 IN TOTAL NOW

In [275]:
#Creating an instance of the chrome driver to get to the url

driver10 = webdriver.Chrome(r'E:/CHROME-DRIVER/chromedriver_win32/chromedriver.exe')

In [276]:
#Getting into the website

driver10.get('https://www.olx.in/en-in/kerala_g2001160/cars_c84')

In [277]:
#Creating empty lists so that we can fetch the data

Price_10=[]
Year_10=[]
Km_10=[]
Company_10=[]
Location_10=[]
Date_10=[]

In [278]:
#Fetching the data from olx for Price

for p10 in driver10.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/span"):
    Price_10.append(p10.text.replace("â‚¹","").replace(",",""))

In [279]:
#Printing the price

Price_10

[' 645000',
 ' 725000',
 ' 13500000',
 ' 35000',
 ' 185000',
 ' 125000',
 ' 145000',
 ' 265000',
 ' 80000',
 ' 585000',
 ' 260000',
 ' 80000',
 ' 1140000',
 ' 245000',
 ' 435000',
 ' 485000',
 ' 1000000',
 ' 3500000',
 ' 400000',
 ' 1950000',
 ' 590000',
 ' 235000',
 ' 1450000',
 ' 210000',
 ' 420000',
 ' 190000',
 ' 485000',
 ' 720000',
 ' 27000',
 ' 250000',
 ' 200000',
 ' 475000',
 ' 465000',
 ' 775000',
 ' 150000',
 ' 450000',
 ' 150000',
 ' 1590000',
 ' 305000',
 ' 230000',
 ' 199999',
 ' 1444444',
 ' 5000000',
 ' 73000',
 ' 1970000',
 ' 350000',
 ' 615000',
 ' 615000',
 ' 750000',
 ' 195000',
 ' 1250000',
 ' 1990000',
 ' 695000',
 ' 310000',
 ' 3400000',
 ' 90000',
 ' 470000',
 ' 150000',
 ' 155000',
 ' 205000',
 ' 125000',
 ' 125000',
 ' 275000',
 ' 650000',
 ' 700000',
 ' 110000',
 ' 230000',
 ' 160000',
 ' 385000',
 ' 290000',
 ' 450000',
 ' 155000',
 ' 390000',
 ' 43000',
 ' 45000',
 ' 161000',
 ' 237000',
 ' 198000',
 ' 303000',
 ' 699000',
 ' 1750000',
 ' 69000',
 ' 745000',
 ' 1085000',
 ' 2580000',
 ' 380000',
 ' 529000',
 ' 320000',
 ' 929000',
 ' 98000',
 ' 259000',
 ' 210000',
 ' 290000',
 ' 60000',
 ' 464901',
 ' 956542',
 ' 325000',
 ' 950000',
 ' 130000',
 ' 210000',
 ' 1700000',
 ' 460000',
 ' 1700000',
 ' 1040000',
 ' 410000',
 ' 535000',
 ' 275000',
 ' 285000',
 ' 365000',
 ' 1050000',
 ' 450000',
 ' 740000',
 ' 775000',
 ' 300000',
 ' 460000',
 ' 28000',
 ' 1250000',
 ' 40000',
 ' 300000',
 ' 205000',
 ' 20000',
 ' 1650000',
 ' 1550000',
 ' 115000',
 ' 80000',
 ' 600000',
 ' 630000',
 ' 390000',
 ' 620000',
 ' 1865000',
 ' 675000',
 ' 149000',
 ' 500000',
 ' 335000',
 ' 370000',
 ' 355000',
 ' 149500',
 ' 120000',
 ' 75000',
 ' 315000',
 ' 999999',
 ' 675000',
 ' 250000',
 ' 850000',
 ' 220000',
 ' 190000',
 ' 589999',
 ' 65000',
 ' 45000',
 ' 160000',
 ' 875000',
 ' 75000',
 ' 265000',
 ' 340000',
 ' 49000',
 ' 365000',
 ' 199000',
 ' 119000',
 ' 1820000',
 ' 760000',
 ' 1425000',
 ' 2650000',
 ' 2300000',
 ' 510000',
 ' 240000',
 ' 49000',
 ' 930000',
 ' 226000',
 ' 60000',
 ' 340000',
 ' 325000',
 ' 2100000',
 ' 685000',
 ' 500000',
 ' 585000',
 ' 245000',
 ' 70000',
 ' 105000',
 ' 70000',
 ' 270000',
 ' 300000',
 ' 1550000',
 ' 1050000',
 ' 130000',
 ' 150000',
 ' 228000',
 ' 215000',
 ' 90000',
 ' 225000',
 ' 320000',
 ' 400000',
 ' 95000',
 ' 120000',
 ' 725000',
 ' 100000',
 ' 140000',
 ' 38000',
 ' 260000',
 ' 305000',
 ' 830000',
 ' 655000',
 ' 590000',
 ' 135000',
 ' 190000',
 ' 60000',
 ' 720000',
 ' 1880000',
 ' 275000',
 ' 315000',
 ' 645000',
 ' 215000',
 ' 80000',
 ' 275000',
 ' 525000',
 ' 115000',
 ' 595000',
 ' 190000',
 ' 450000',
 ' 275000',
 ' 100000',
 ' 6200000',
 ' 4990000',
 ' 680000',
 ' 85000',
 ' 725000',
 ' 94000',
 ' 60000',
 ' 775000',
 ' 110000',
 ' 455000',
 ' 199000',
 ' 1275000',
 ' 560000',
 ' 525000',
 ' 949000',
 ' 745000',
 ' 210000',
 ' 435000',
 ' 170000',
 ' 150000',
 ' 830000',
 ' 1250000',
 ' 260000',
 ' 650000',
 ' 125000',
 ' 490000',
 ' 169000',
 ' 75000',
 ' 375000',
 ' 515000',
 ' 480000',
 ' 325000',
 ' 195000',
 ' 369000',
 ' 93000',
 ' 110000',
 ' 375000',
 ' 298000',
 ' 110000',
 ' 499000',
 ' 400000',
 ' 2300000',
 ' 3800000',
 ' 150000',
 ' 335000',
 ' 525000',
 ' 700000',
 ' 42000',
 ' 230000',
 ' 225000',
 ' 935000',
 ' 678000',
 ' 100000',
 ' 120000',
 ' 399999',
 ' 260000',
 ' 775000',
 ' 255000',
 ' 2060000',
 ' 850000',
 ' 980000',
 ' 435000',
 ' 550000',
 ' 1600000',
 ' 160000',
 ' 135000',
 ' 365000',
 ' 725000',
 ' 660000',
 ' 665000',
 ' 515000',
 ' 500000',
 ' 360000',
 ' 605000',
 ' 699999',
 ' 3999999',
 ' 465000',
 ' 365000',
 ' 180000',
 ' 290000',
 ' 250000',
 ' 310000',
 ' 750000',
 ' 7100000',
 ' 785000',
 ' 145000',
 ' 120000',
 ' 50000',
 ' 315000',
 ' 1525000',
 ' 148000',
 ' 470000',
 ' 545000',
 ' 515000',
 ' 175000',
 ' 710000',
 ' 130000',
 ' 949000',
 ' 310000',
 ' 400000',
 ' 1035000',
 ' 425000',
 ' 450000',
 ' 850000',
 ' 400000',
 ' 515000',
 ' 250000',
 ' 300000',
 ' 150000',
 ' 450000',
 ' 665000',
 ' 145000',
 ' 385000',
 ' 365000',
 ' 1248399',
 ' 385000',
 ' 200000',
 ' 285000',
 ' 450000',
 ' 460000',
 ' 1025000',
 ' 49000',
 ' 515000',
 ' 185000',
 ' 79000',
 ' 315000',
 ' 330000',
 ' 110000',
 ' 260000',
 ' 60000',
 ' 110000',
 ' 180000',
 ' 241000',
 ' 110000',
 ' 300000',
 ' 900000',
 ' 435000',
 ' 485000',
 ' 330000',
 ' 125000',
 ' 640000',
 ' 55000',
 ' 250000',
 ' 700000',
 ' 1900000',
 ' 5000000',
 ' 1999999',
 ' 497000',
 ' 600000',
 ' 300000',
 ' 260000',
 ' 200000',
 ' 180000',
 ' 80000',
 ' 535000',
 ' 159999',
 ' 900000',
 ' 25000',
 ' 735000',
 ' 580000',
 ' 2750000',
 ' 795000',
 ' 690000',
 ' 95000',
 ' 265000',
 ' 112000',
 ' 373000',
 ' 72000',
 ' 73000',
 ' 750000',
 ' 525000',
 ' 2500000',
 ' 1485000',
 ' 875000',
 ' 99999',
 ' 148000',
 ' 160000',
 ' 100000',
 ' 600000',
 ' 1825000',
 ' 153000',
 ' 435000',
 ' 310000',
 ' 41000',
 ' 2222222',
 ' 235000',
 ' 1325000',
 ' 222000',
 ' 270000',
 ' 485000',
 ' 2500000',
 ' 380000',
 ' 140000',
 ' 335000',
 ' 255000',
 ' 255000',
 ' 425000',
 ' 575000',
 ' 615000',
 ' 480000',
 ' 285000',
 ' 1600000',
 ' 45000',
 ' 1650000',
 ' 210000',
 ' 475000',
 ' 398000',
 ' 850000',
 ' 430000',
 ' 125000',
 ' 1075000',
 ' 150000',
 ' 490000',
 ' 540000',
 ' 1249999',
 ' 410000',
 ' 345000',
 ' 220000',
 ' 620000',
 ' 1150000',
 ' 500000',
 ' 3000000',
 ' 150000',
 ' 600000',
 ' 2900000',
 ' 875000',
 ' 1250000',
 ' 395000',
 ' 585000',
 ' 170000',
 ' 720000',
 ' 688888',
 ' 160000',
 ' 625000',
 ' 535000',
 ' 215000',
 ' 150000',
 ' 615000',
 ' 220000',
 ' 665000',
 ' 615000',
 ' 550000',
 ' 775000',
 ' 725000',
 ' 380000',
 ' 545000',
 ' 295000',
 ' 775000',
 ' 990000',
 ' 195000',
 ' 435000',
 ' 1250000',
 ' 665000',
 ' 625000',
 ' 950000',
 ' 850000',
 ' 465000',
 ' 235000',
 ' 1075000',
 ' 160000',
 ' 3000000',
 ' 1075000',
 ' 68000',
 ' 265000',
 ' 635000',
 ' 535000',
 ' 350000',
 ' 250000',
 ' 130000',
 ' 125000',
 ' 345000',
 ' 800000',
 ' 460000',
 ' 575000',
 ' 650000',
 ' 135000',
 ' 61000',
 ' 1250000',
 ' 640000',
 ' 2600000',
 ' 890000',
 ' 350000',
 ' 130000',
 ' 730000',
 ' 200000',
 ' 280000',
 ' 685000',
 ' 575000',
 ' 260000',
 ' 465000',
 ' 650000',
 ' 165000',
 ' 440000',
 ' 310000',
 ' 170000',
 ' 160000',
 ' 115000',
 ' 252000',
 ' 1815000',
 ' 1615000',
 ' 115000',
 ' 662000',
 ' 45000',
 ' 115000',
 ' 180000',
 ' 950000',
 ' 95000',
 ' 499999',
 ' 115000',
 ' 140000',
 ' 380000',
 ' 390000',
 ' 380000',
 ' 385000',
 ' 417000',
 ' 113000',
 ' 585000',
 ' 235000']

In [280]:
#Converting the column into integer type

for i in range(0, len(Price_10)):
    Price_10[i] = int(Price_10[i])

In [281]:
#Printing after conversion

Price_10

[645000,
 725000,
 13500000,
 35000,
 185000,
 125000,
 145000,
 265000,
 80000,
 585000,
 260000,
 80000,
 1140000,
 245000,
 435000,
 485000,
 1000000,
 3500000,
 400000,
 1950000,
 590000,
 235000,
 1450000,
 210000,
 420000,
 190000,
 485000,
 720000,
 27000,
 250000,
 200000,
 475000,
 465000,
 775000,
 150000,
 450000,
 150000,
 1590000,
 305000,
 230000,
 199999,
 1444444,
 5000000,
 73000,
 1970000,
 350000,
 615000,
 615000,
 750000,
 195000,
 1250000,
 1990000,
 695000,
 310000,
 3400000,
 90000,
 470000,
 150000,
 155000,
 205000,
 125000,
 125000,
 275000,
 650000,
 700000,
 110000,
 230000,
 160000,
 385000,
 290000,
 450000,
 155000,
 390000,
 43000,
 45000,
 161000,
 237000,
 198000,
 303000,
 699000,
 1750000,
 69000,
 745000,
 1085000,
 2580000,
 380000,
 529000,
 320000,
 929000,
 98000,
 259000,
 210000,
 290000,
 60000,
 464901,
 956542,
 325000,
 950000,
 130000,
 210000,
 1700000,
 460000,
 1700000,
 1040000,
 410000,
 535000,
 275000,
 285000,
 365000,
 1050000,
 450000,
 740000,
 775000,
 300000,
 460000,
 28000,
 1250000,
 40000,
 300000,
 205000,
 20000,
 1650000,
 1550000,
 115000,
 80000,
 600000,
 630000,
 390000,
 620000,
 1865000,
 675000,
 149000,
 500000,
 335000,
 370000,
 355000,
 149500,
 120000,
 75000,
 315000,
 999999,
 675000,
 250000,
 850000,
 220000,
 190000,
 589999,
 65000,
 45000,
 160000,
 875000,
 75000,
 265000,
 340000,
 49000,
 365000,
 199000,
 119000,
 1820000,
 760000,
 1425000,
 2650000,
 2300000,
 510000,
 240000,
 49000,
 930000,
 226000,
 60000,
 340000,
 325000,
 2100000,
 685000,
 500000,
 585000,
 245000,
 70000,
 105000,
 70000,
 270000,
 300000,
 1550000,
 1050000,
 130000,
 150000,
 228000,
 215000,
 90000,
 225000,
 320000,
 400000,
 95000,
 120000,
 725000,
 100000,
 140000,
 38000,
 260000,
 305000,
 830000,
 655000,
 590000,
 135000,
 190000,
 60000,
 720000,
 1880000,
 275000,
 315000,
 645000,
 215000,
 80000,
 275000,
 525000,
 115000,
 595000,
 190000,
 450000,
 275000,
 100000,
 6200000,
 4990000,
 680000,
 85000,
 725000,
 94000,
 60000,
 775000,
 110000,
 455000,
 199000,
 1275000,
 560000,
 525000,
 949000,
 745000,
 210000,
 435000,
 170000,
 150000,
 830000,
 1250000,
 260000,
 650000,
 125000,
 490000,
 169000,
 75000,
 375000,
 515000,
 480000,
 325000,
 195000,
 369000,
 93000,
 110000,
 375000,
 298000,
 110000,
 499000,
 400000,
 2300000,
 3800000,
 150000,
 335000,
 525000,
 700000,
 42000,
 230000,
 225000,
 935000,
 678000,
 100000,
 120000,
 399999,
 260000,
 775000,
 255000,
 2060000,
 850000,
 980000,
 435000,
 550000,
 1600000,
 160000,
 135000,
 365000,
 725000,
 660000,
 665000,
 515000,
 500000,
 360000,
 605000,
 699999,
 3999999,
 465000,
 365000,
 180000,
 290000,
 250000,
 310000,
 750000,
 7100000,
 785000,
 145000,
 120000,
 50000,
 315000,
 1525000,
 148000,
 470000,
 545000,
 515000,
 175000,
 710000,
 130000,
 949000,
 310000,
 400000,
 1035000,
 425000,
 450000,
 850000,
 400000,
 515000,
 250000,
 300000,
 150000,
 450000,
 665000,
 145000,
 385000,
 365000,
 1248399,
 385000,
 200000,
 285000,
 450000,
 460000,
 1025000,
 49000,
 515000,
 185000,
 79000,
 315000,
 330000,
 110000,
 260000,
 60000,
 110000,
 180000,
 241000,
 110000,
 300000,
 900000,
 435000,
 485000,
 330000,
 125000,
 640000,
 55000,
 250000,
 700000,
 1900000,
 5000000,
 1999999,
 497000,
 600000,
 300000,
 260000,
 200000,
 180000,
 80000,
 535000,
 159999,
 900000,
 25000,
 735000,
 580000,
 2750000,
 795000,
 690000,
 95000,
 265000,
 112000,
 373000,
 72000,
 73000,
 750000,
 525000,
 2500000,
 1485000,
 875000,
 99999,
 148000,
 160000,
 100000,
 600000,
 1825000,
 153000,
 435000,
 310000,
 41000,
 2222222,
 235000,
 1325000,
 222000,
 270000,
 485000,
 2500000,
 380000,
 140000,
 335000,
 255000,
 255000,
 425000,
 575000,
 615000,
 480000,
 285000,
 1600000,
 45000,
 1650000,
 210000,
 475000,
 398000,
 850000,
 430000,
 125000,
 1075000,
 150000,
 490000,
 540000,
 1249999,
 410000,
 345000,
 220000,
 620000,
 1150000,
 500000,
 3000000,
 150000,
 600000,
 2900000,
 875000,
 1250000,
 395000,
 585000,
 170000,
 720000,
 688888,
 160000,
 625000,
 535000,
 215000,
 150000,
 615000,
 220000,
 665000,
 615000,
 550000,
 775000,
 725000,
 380000,
 545000,
 295000,
 775000,
 990000,
 195000,
 435000,
 1250000,
 665000,
 625000,
 950000,
 850000,
 465000,
 235000,
 1075000,
 160000,
 3000000,
 1075000,
 68000,
 265000,
 635000,
 535000,
 350000,
 250000,
 130000,
 125000,
 345000,
 800000,
 460000,
 575000,
 650000,
 135000,
 61000,
 1250000,
 640000,
 2600000,
 890000,
 350000,
 130000,
 730000,
 200000,
 280000,
 685000,
 575000,
 260000,
 465000,
 650000,
 165000,
 440000,
 310000,
 170000,
 160000,
 115000,
 252000,
 1815000,
 1615000,
 115000,
 662000,
 45000,
 115000,
 180000,
 950000,
 95000,
 499999,
 115000,
 140000,
 380000,
 390000,
 380000,
 385000,
 417000,
 113000,
 585000,
 235000]

In [282]:
#Fetching data from olx for Year

for y10 in driver10.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Year_10.append(y10.text.split('-')[0])

In [283]:
#Printing the year

Year_10

['2018 ',
 '2017 ',
 '2020 ',
 '1998 ',
 '2008 ',
 '2006 ',
 '2015 ',
 '2013 ',
 '2006 ',
 '2015 ',
 '2016 ',
 '2010 ',
 '2021 ',
 '2015 ',
 '2014 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2013 ',
 '2014 ',
 '2015 ',
 '2009 ',
 '2017 ',
 '2013 ',
 '2019 ',
 '2009 ',
 '2015 ',
 '2017 ',
 '2003 ',
 '2011 ',
 '2004 ',
 '2015 ',
 '2018 ',
 '2018 ',
 '2011 ',
 '2014 ',
 '2012 ',
 '2014 ',
 '2017 ',
 '2010 ',
 '2011 ',
 '2018 ',
 '2019 ',
 '2007 ',
 '2021 ',
 '2017 ',
 '2020 ',
 '2020 ',
 '2018 ',
 '2010 ',
 '2019 ',
 '2015 ',
 '2019 ',
 '2001 ',
 '2013 ',
 '2009 ',
 '2020 ',
 '2008 ',
 '2009 ',
 '2010 ',
 '2008 ',
 '2009 ',
 '2012 ',
 '2012 ',
 '2011 ',
 '2009 ',
 '2016 ',
 '2004 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2008 ',
 '2012 ',
 '2003 ',
 '2003 ',
 '2011 ',
 '2005 ',
 '2015 ',
 '2012 ',
 '2016 ',
 '2013 ',
 '2001 ',
 '2019 ',
 '2015 ',
 '2015 ',
 '2013 ',
 '2016 ',
 '2012 ',
 '2019 ',
 '2007 ',
 '2014 ',
 '2014 ',
 '2016 ',
 '2000 ',
 '2020 ',
 '2020 ',
 '2015 ',
 '2018 ',
 '2010 ',
 '2010 ',
 '2012 ',
 '2017 ',
 '2017 ',
 '2014 ',
 '2013 ',
 '2016 ',
 '2016 ',
 '2014 ',
 '2014 ',
 '2020 ',
 '2017 ',
 '2018 ',
 '2020 ',
 '2010 ',
 '2014 ',
 '2002 ',
 '2014 ',
 '2002 ',
 '2012 ',
 '2008 ',
 '2021 ',
 '2013 ',
 '2013 ',
 '2004 ',
 '2004 ',
 '2018 ',
 '2017 ',
 '2013 ',
 '2016 ',
 '2018 ',
 '2017 ',
 '2009 ',
 '2015 ',
 '2015 ',
 '2015 ',
 '2007 ',
 '2011 ',
 '2012 ',
 '2004 ',
 '2013 ',
 '2018 ',
 '2018 ',
 '2011 ',
 '2019 ',
 '2017 ',
 '2006 ',
 '2016 ',
 '2005 ',
 '1997 ',
 '2011 ',
 '2017 ',
 '2014 ',
 '2017 ',
 '2019 ',
 '2003 ',
 '2016 ',
 '2011 ',
 '2006 ',
 '2016 ',
 '2011 ',
 '2017 ',
 '2016 ',
 '2019 ',
 '2006 ',
 '2010 ',
 '2007 ',
 '2018 ',
 '2010 ',
 '2004 ',
 '2014 ',
 '2011 ',
 '2015 ',
 '2020 ',
 '2018 ',
 '2016 ',
 '2013 ',
 '2009 ',
 '2008 ',
 '2006 ',
 '2008 ',
 '2008 ',
 '2014 ',
 '2015 ',
 '2006 ',
 '2008 ',
 '2009 ',
 '2014 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '2011 ',
 '1995 ',
 '2003 ',
 '2019 ',
 '2005 ',
 '2011 ',
 '2002 ',
 '2001 ',
 '2012 ',
 '2019 ',
 '2016 ',
 '2015 ',
 '2012 ',
 '2013 ',
 '2003 ',
 '2016 ',
 '2013 ',
 '2017 ',
 '2018 ',
 '2012 ',
 '2011 ',
 '2007 ',
 '2016 ',
 '2009 ',
 '2009 ',
 '2017 ',
 '2007 ',
 '2018 ',
 '2001 ',
 '2007 ',
 '2019 ',
 '2020 ',
 '2018 ',
 '2008 ',
 '2016 ',
 '2004 ',
 '2004 ',
 '2019 ',
 '2015 ',
 '2018 ',
 '2013 ',
 '2016 ',
 '2019 ',
 '2017 ',
 '2013 ',
 '2017 ',
 '2012 ',
 '2012 ',
 '2009 ',
 '2008 ',
 '2018 ',
 '2014 ',
 '2005 ',
 '2012 ',
 '2012 ',
 '2015 ',
 '2014 ',
 '2005 ',
 '2015 ',
 '2016 ',
 '2018 ',
 '2013 ',
 '2006 ',
 '2014 ',
 '2007 ',
 '2001 ',
 '2015 ',
 '2011 ',
 '2004 ',
 '2018 ',
 '2012 ',
 '2012 ',
 '2016 ',
 '2007 ',
 '2016 ',
 '2014 ',
 '1996 ',
 '2007 ',
 '2012 ',
 '2014 ',
 '2016 ',
 '2014 ',
 '2006 ',
 '2007 ',
 '2012 ',
 '2017 ',
 '2016 ',
 '2011 ',
 '2016 ',
 '2008 ',
 '2014 ',
 '2013 ',
 '2016 ',
 '2016 ',
 '2009 ',
 '2004 ',
 '2013 ',
 '2017 ',
 '2016 ',
 '2016 ',
 '2018 ',
 '2009 ',
 '2016 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2016 ',
 '2007 ',
 '2010 ',
 '2015 ',
 '2009 ',
 '2017 ',
 '2010 ',
 '2012 ',
 '2021 ',
 '2010 ',
 '2010 ',
 '2003 ',
 '2014 ',
 '2018 ',
 '2016 ',
 '2018 ',
 '2014 ',
 '2009 ',
 '2010 ',
 '2019 ',
 '2004 ',
 '2014 ',
 '2017 ',
 '2007 ',
 '2019 ',
 '2016 ',
 '2013 ',
 '2015 ',
 '2006 ',
 '2017 ',
 '2016 ',
 '2006 ',
 '2010 ',
 '2016 ',
 '2020 ',
 '2009 ',
 '2014 ',
 '2020 ',
 '2018 ',
 '2013 ',
 '2007 ',
 '2017 ',
 '2016 ',
 '2020 ',
 '2021 ',
 '2003 ',
 '2018 ',
 '2010 ',
 '2007 ',
 '2013 ',
 '2014 ',
 '2008 ',
 '2016 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2015 ',
 '2007 ',
 '1997 ',
 '2018 ',
 '2014 ',
 '2015 ',
 '2013 ',
 '2002 ',
 '2018 ',
 '2005 ',
 '2013 ',
 '2013 ',
 '2012 ',
 '2016 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2015 ',
 '2014 ',
 '2012 ',
 '2011 ',
 '2003 ',
 '2013 ',
 '2013 ',
 '2016 ',
 '2021 ',
 '2018 ',
 '2020 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '1999 ',
 '2011 ',
 '2006 ',
 '2014 ',
 '2008 ',
 '2014 ',
 '2017 ',
 '2016 ',
 '2012 ',
 '2013 ',
 '2006 ',
 '2003 ',
 '2007 ',
 '2008 ',
 '2008 ',
 '2016 ',
 '2014 ',
 '2009 ',
 '2018 ',
 '2015 ',
 '2003 ',
 '2016 ',
 '2016 ',
 '2017 ',
 '2010 ',
 '2012 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2010 ',
 '2012 ',
 '2007 ',
 '2007 ',
 '2013 ',
 '2016 ',
 '2018 ',
 '2016 ',
 '2015 ',
 '2019 ',
 '2000 ',
 '2020 ',
 '2011 ',
 '2019 ',
 '2019 ',
 '2021 ',
 '2014 ',
 '2006 ',
 '2016 ',
 '2016 ',
 '2014 ',
 '2010 ',
 '2012 ',
 '2014 ',
 '2020 ',
 '2010 ',
 '2020 ',
 '2014 ',
 '2019 ',
 '2010 ',
 '2006 ',
 '2015 ',
 '2017 ',
 '2010 ',
 '2014 ',
 '2011 ',
 '2013 ',
 '2009 ',
 '2017 ',
 '2018 ',
 '2009 ',
 '2010 ',
 '2012 ',
 '2009 ',
 '2011 ',
 '2016 ',
 '2014 ',
 '2016 ',
 '2016 ',
 '2013 ',
 '2014 ',
 '2019 ',
 '2007 ',
 '2019 ',
 '2017 ',
 '2019 ',
 '2020 ',
 '2011 ',
 '2016 ',
 '2018 ',
 '2018 ',
 '2021 ',
 '2018 ',
 '2019 ',
 '2018 ',
 '2009 ',
 '2021 ',
 '2012 ',
 '2015 ',
 '2013 ',
 '2002 ',
 '2011 ',
 '2019 ',
 '2015 ',
 '2012 ',
 '2006 ',
 '2010 ',
 '2010 ',
 '2012 ',
 '2014 ',
 '2014 ',
 '2015 ',
 '2020 ',
 '2010 ',
 '2000 ',
 '2013 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2017 ',
 '2011 ',
 '2017 ',
 '2010 ',
 '2017 ',
 '2015 ',
 '2018 ',
 '2014 ',
 '2017 ',
 '2018 ',
 '2009 ',
 '2013 ',
 '2018 ',
 '2009 ',
 '2008 ',
 '2006 ',
 '2012 ',
 '2021 ',
 '2014 ',
 '2007 ',
 '2013 ',
 '2003 ',
 '2007 ',
 '2015 ',
 '2016 ',
 '2013 ',
 '2018 ',
 '2006 ',
 '2004 ',
 '2014 ',
 '2017 ',
 '2014 ',
 '2018 ',
 '2013 ',
 '2019 ',
 '2016 ',
 '2010 ']

In [284]:
#Converting the column into integer type

for i in range(0, len(Year_10)):
    Year_10[i] = int(Year_10[i])

In [285]:
#Printing after conversion

Year_10

[2018,
 2017,
 2020,
 1998,
 2008,
 2006,
 2015,
 2013,
 2006,
 2015,
 2016,
 2010,
 2021,
 2015,
 2014,
 2017,
 2016,
 2016,
 2013,
 2014,
 2015,
 2009,
 2017,
 2013,
 2019,
 2009,
 2015,
 2017,
 2003,
 2011,
 2004,
 2015,
 2018,
 2018,
 2011,
 2014,
 2012,
 2014,
 2017,
 2010,
 2011,
 2018,
 2019,
 2007,
 2021,
 2017,
 2020,
 2020,
 2018,
 2010,
 2019,
 2015,
 2019,
 2001,
 2013,
 2009,
 2020,
 2008,
 2009,
 2010,
 2008,
 2009,
 2012,
 2012,
 2011,
 2009,
 2016,
 2004,
 2016,
 2018,
 2018,
 2008,
 2012,
 2003,
 2003,
 2011,
 2005,
 2015,
 2012,
 2016,
 2013,
 2001,
 2019,
 2015,
 2015,
 2013,
 2016,
 2012,
 2019,
 2007,
 2014,
 2014,
 2016,
 2000,
 2020,
 2020,
 2015,
 2018,
 2010,
 2010,
 2012,
 2017,
 2017,
 2014,
 2013,
 2016,
 2016,
 2014,
 2014,
 2020,
 2017,
 2018,
 2020,
 2010,
 2014,
 2002,
 2014,
 2002,
 2012,
 2008,
 2021,
 2013,
 2013,
 2004,
 2004,
 2018,
 2017,
 2013,
 2016,
 2018,
 2017,
 2009,
 2015,
 2015,
 2015,
 2007,
 2011,
 2012,
 2004,
 2013,
 2018,
 2018,
 2011,
 2019,
 2017,
 2006,
 2016,
 2005,
 1997,
 2011,
 2017,
 2014,
 2017,
 2019,
 2003,
 2016,
 2011,
 2006,
 2016,
 2011,
 2017,
 2016,
 2019,
 2006,
 2010,
 2007,
 2018,
 2010,
 2004,
 2014,
 2011,
 2015,
 2020,
 2018,
 2016,
 2013,
 2009,
 2008,
 2006,
 2008,
 2008,
 2014,
 2015,
 2006,
 2008,
 2009,
 2014,
 2011,
 2011,
 2011,
 2011,
 1995,
 2003,
 2019,
 2005,
 2011,
 2002,
 2001,
 2012,
 2019,
 2016,
 2015,
 2012,
 2013,
 2003,
 2016,
 2013,
 2017,
 2018,
 2012,
 2011,
 2007,
 2016,
 2009,
 2009,
 2017,
 2007,
 2018,
 2001,
 2007,
 2019,
 2020,
 2018,
 2008,
 2016,
 2004,
 2004,
 2019,
 2015,
 2018,
 2013,
 2016,
 2019,
 2017,
 2013,
 2017,
 2012,
 2012,
 2009,
 2008,
 2018,
 2014,
 2005,
 2012,
 2012,
 2015,
 2014,
 2005,
 2015,
 2016,
 2018,
 2013,
 2006,
 2014,
 2007,
 2001,
 2015,
 2011,
 2004,
 2018,
 2012,
 2012,
 2016,
 2007,
 2016,
 2014,
 1996,
 2007,
 2012,
 2014,
 2016,
 2014,
 2006,
 2007,
 2012,
 2017,
 2016,
 2011,
 2016,
 2008,
 2014,
 2013,
 2016,
 2016,
 2009,
 2004,
 2013,
 2017,
 2016,
 2016,
 2018,
 2009,
 2016,
 2017,
 2017,
 2017,
 2016,
 2007,
 2010,
 2015,
 2009,
 2017,
 2010,
 2012,
 2021,
 2010,
 2010,
 2003,
 2014,
 2018,
 2016,
 2018,
 2014,
 2009,
 2010,
 2019,
 2004,
 2014,
 2017,
 2007,
 2019,
 2016,
 2013,
 2015,
 2006,
 2017,
 2016,
 2006,
 2010,
 2016,
 2020,
 2009,
 2014,
 2020,
 2018,
 2013,
 2007,
 2017,
 2016,
 2020,
 2021,
 2003,
 2018,
 2010,
 2007,
 2013,
 2014,
 2008,
 2016,
 2007,
 2008,
 2008,
 2015,
 2007,
 1997,
 2018,
 2014,
 2015,
 2013,
 2002,
 2018,
 2005,
 2013,
 2013,
 2012,
 2016,
 2016,
 2016,
 2017,
 2015,
 2014,
 2012,
 2011,
 2003,
 2013,
 2013,
 2016,
 2021,
 2018,
 2020,
 2016,
 2018,
 2018,
 1999,
 2011,
 2006,
 2014,
 2008,
 2014,
 2017,
 2016,
 2012,
 2013,
 2006,
 2003,
 2007,
 2008,
 2008,
 2016,
 2014,
 2009,
 2018,
 2015,
 2003,
 2016,
 2016,
 2017,
 2010,
 2012,
 2014,
 2014,
 2015,
 2010,
 2012,
 2007,
 2007,
 2013,
 2016,
 2018,
 2016,
 2015,
 2019,
 2000,
 2020,
 2011,
 2019,
 2019,
 2021,
 2014,
 2006,
 2016,
 2016,
 2014,
 2010,
 2012,
 2014,
 2020,
 2010,
 2020,
 2014,
 2019,
 2010,
 2006,
 2015,
 2017,
 2010,
 2014,
 2011,
 2013,
 2009,
 2017,
 2018,
 2009,
 2010,
 2012,
 2009,
 2011,
 2016,
 2014,
 2016,
 2016,
 2013,
 2014,
 2019,
 2007,
 2019,
 2017,
 2019,
 2020,
 2011,
 2016,
 2018,
 2018,
 2021,
 2018,
 2019,
 2018,
 2009,
 2021,
 2012,
 2015,
 2013,
 2002,
 2011,
 2019,
 2015,
 2012,
 2006,
 2010,
 2010,
 2012,
 2014,
 2014,
 2015,
 2020,
 2010,
 2000,
 2013,
 2017,
 2017,
 2017,
 2017,
 2011,
 2017,
 2010,
 2017,
 2015,
 2018,
 2014,
 2017,
 2018,
 2009,
 2013,
 2018,
 2009,
 2008,
 2006,
 2012,
 2021,
 2014,
 2007,
 2013,
 2003,
 2007,
 2015,
 2016,
 2013,
 2018,
 2006,
 2004,
 2014,
 2017,
 2014,
 2018,
 2013,
 2019,
 2016,
 2010]

In [286]:
#Fetching data from olx for Km used, Company, Location, Date of posting

for k10 in driver10.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[1]"):
    Km_10.append(k10.text.split('-')[1])
for c10 in driver10.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[2]"):
    Company_10.append(c10.text)
for l10 in driver10.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]"):
    Location_10.append(l10.text)
for d10 in driver10.find_elements_by_xpath("//*[@id='container']/main/div/div/section/div/div/div[5]/div[2]/div/div[2]/ul/li/a/div[1]/div[2]/div[3]/span"):
    Date_10.append(d10.text)

In [287]:
#Making a dataframe named Cars storing 500 data into that

CARS10=pd.DataFrame({})
CARS10['PRICE']=Price_10[0:500]
CARS10['YEAR']=Year_10[0:500]
CARS10['KM']=Km_10[0:500]
CARS10['COMPANY']=Company_10[0:500]
CARS10['LOCATION']=Location_10[0:500]
CARS10['POSTED-DATE']=Date_10[0:500]

In [288]:
#Printing the dataframe

CARS10

,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE
0,645000,2018,"41,250 km",Maruti Suzuki Baleno,Kowdiar\nJan 03,Jan 03
1,725000,2017,"82,000 km",Maruti Suzuki Swift Dzire,Changubetty\n5 days ago,5 days ago
2,13500000,2020,"5,005 km",BMW 8 Series,Companypadi\nJan 12,Jan 12
3,35000,1998,"50,000 km",Maruti Suzuki 800,Pazhakutty\nToday,Today
4,185000,2008,"141,000 km",Maruti Suzuki Swift,Palarivattom\nToday,Today
...,...,...,...,...,...,...
495,135000,2010,"61,314 km",Chevrolet Beat,Merakatu\nToday,Today
496,61000,2000,"95,000 km",Maruti Suzuki Wagon R,Vailathur\nToday,Today
497,1250000,2013,"130,000 km",Toyota Fortuner,Changubetty\nToday,Today
498,640000,2017,"37,000 km",Maruti Suzuki Baleno,Pattom\nJan 07,Jan 07
499,2600000,2017,"56,000 km",Audi Q3,Anchal\nOct 18,Oct 18

In [289]:
#Gwtting the information about the dataset

CARS10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PRICE        500 non-null    int64
 1   YEAR         500 non-null    int64
 2   KM           500 non-null    object
 3   COMPANY      500 non-null    object
 4   LOCATION     500 non-null    object
 5   POSTED-DATE  500 non-null    object
dtypes: int64(2), object(4)
memory usage: 23.6+ KB

In [252]:
driver10.close()

# 5497 IN TOTAL HAS BEEN NOW SCRAPED FROM THE WEBSITE

In [296]:
#Saving all the fileS into csv format that we have scraped in our all parts

df=CARS.to_csv('CARS-FILE1.csv')
df2=CARS2.to_csv('CARS-FILE2.csv')
df3=CARS3.to_csv('CARS-FILE3.csv')
df4=CARS4.to_csv('CARS-FILE4.csv')
df5=CARS5.to_csv('CARS-FILE5.csv')
df6=CARS6.to_csv('CARS-FILE6.csv')
df7=CARS7.to_csv('CARS-FILE7.csv')
df8=CARS8.to_csv('CARS-FILE8.csv')
df9=CARS9.to_csv('CARS-FILE9.csv')

In [297]:
df01=CARS10.to_csv('CARS-FILE01.csv')

# WE HAVE CREATED THE CSV FILES OF ALL THE PARTS

In [291]:
!pip install glob

ERROR: Could not find a version that satisfies the requirement glob (from versions: none)
ERROR: No matching distribution found for glob

In [292]:
#Importing pandas & glob

import pandas as pd
from glob import glob

In [298]:
#Storing our directory of our file into files

files = sorted(glob('E:/TEJ/FLIPROBO/CAR-PRICE/DATAA/CARS-FILE*.csv'))
files

['E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\\CARS-FILE01.csv',
 'E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\\CARS-FILE1.csv',
 'E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\\CARS-FILE10.csv',
 'E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\\CARS-FILE2.csv',
 'E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\\CARS-FILE3.csv',
 'E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\\CARS-FILE4.csv',
 'E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\\CARS-FILE5.csv',
 'E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\\CARS-FILE6.csv',
 'E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\\CARS-FILE7.csv',
 'E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\\CARS-FILE8.csv',
 'E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\\CARS-FILE9.csv']

# NOW WE WILL MERGE THE DATA WITH THE HELP OF CONCAT FUNCTION

In [299]:
#Using concat function & saving all the 6 files into one with the help of for loop

merge_data = pd.concat(pd.read_csv(datafile).assign(soucefilename = datafile)
                      for datafile in files)

In [300]:
#Printing the merged data that we have created from 6 different files

merge_data

,Unnamed: 0,PRICE,YEAR,KM,COMPANY,LOCATION,POSTED-DATE,soucefilename
0,0,645000.0,2018.0,"41,250 km",Maruti Suzuki Baleno,Kowdiar\nJan 03,Jan 03,E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\CARS-FILE01.csv
1,1,725000.0,2017.0,"82,000 km",Maruti Suzuki Swift Dzire,Changubetty\n5 days ago,5 days ago,E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\CARS-FILE01.csv
2,2,13500000.0,2020.0,"5,005 km",BMW 8 Series,Companypadi\nJan 12,Jan 12,E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\CARS-FILE01.csv
3,3,35000.0,1998.0,"50,000 km",Maruti Suzuki 800,Pazhakutty\nToday,Today,E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\CARS-FILE01.csv
4,4,185000.0,2008.0,"141,000 km",Maruti Suzuki Swift,Palarivattom\nToday,Today,E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\CARS-FILE01.csv
...,...,...,...,...,...,...,...,...
495,495,1390000.0,2014.0,"58,000 km",Audi Q3,Sector 80\nToday,Today,E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\CARS-FILE9.csv
496,496,280000.0,2012.0,"80,000 km",Maruti Suzuki Ertiga,Gohana Part\nToday,Today,E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\CARS-FILE9.csv
497,497,45000.0,2006.0,"118,000 km",Maruti Suzuki Alto 800,Prakash Nagar\nToday,Today,E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\CARS-FILE9.csv
498,498,325000.0,2017.0,"88,000 km",Hyundai Xcent,New Grain Market\nToday,Today,E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\CARS-FILE9.csv
499,499,700000.0,2018.0,"73,000 km",Hyundai i20 Active,Tagra Kali Ram\nToday,Today,E:/TEJ/FLIPROBO/CAR-PRICE/DATAA\CARS-FILE9.csv

# NOW HERE WE HAVE ADDED ALL THE FILES IN ONE NOW WE WILL SAVE IT IN ONE CSV FILE

In [301]:
#Now we will save the entire file into one csv file 

merge_data.to_csv('CAR-PRICE-DATA-FINAL.csv')

In [302]:
#END